### ISSUE TITLE
SGML to XML man page conversion

### ISSUE THREAD

**Issue by okias** [iputils/iputils#1]
current format doesn't seems much friendly these days, so I'd consider conversion.

xmltoman seems to be better build-able and supported these days than openjade & docbook-sgml-utils.

**Comment by pavlix** [comment]
FYI, building from SGML works for me on gentoo with one small change in the Makefile.

https://github.com/okias/ixit/blob/master/net-misc/iputils/iputils-99999999.ebuild

    diff --git a/doc/Makefile b/doc/Makefile
    index 5136c70..b461664 100644
    --- a/doc/Makefile
    +++ b/doc/Makefile
    @@ -47,8 +47,8 @@ $(MANFILES): index.db
     	mv $@ ..; \
     	$(CLEAN_TMPDIR)
     
    -fix_sgml2man:
    -	@sed -i -e 's!\\fB\\fIdestination\\fB\\fR \[\\fB/\\fIport\\fB\\fR\]!\\fB\\fIdestination\\fB\\fR[\\fB/\\fIport\\fB\\fR]!g' tracepath.8
    +fix_sgml2man: tracepath.8
    +	@sed -i -e 's!\\fB\\fIdestination\\fB\\fR \[\\fB/\\fIport\\fB\\fR\]!\\fB\\fIdestination\\fB\\fR[\\fB/\\fIport\\fB\\fR]!g' $<
     
     clean:
     	@rm -rf $(MANFILES) $(HTMLFILES) iputils.html tmp.db2html* tmp.db2man*

Without the above patch it sometimes fails for me due to bad parallel make ordering.

**Comment by pavlix** [comment]
The above gets solved by a recent pull request...

https://github.com/iputils/iputils/pull/60

**Comment by okias** [comment]
Conversion had begun, it seems we'll be able use xsltproc (part of libxslt library) same way as systemd use.
