### ISSUE TITLE
CentOS 7 - ping address family not supported by protocol

### ISSUE THREAD

**Issue by adambirds** [iputils/iputils#102]
I get the following error on CentOS 7 when trying to ping:

ping: socket: Address family not supported by protocol

Performing the following commands to downgrade to a previous version fixes it:

yum downgrade http://vault.centos.org/7.2.1511/os/x86_64/Packages/iputils-20121221-7.el7.x86_64.rpm
add "exclude=iputils" to "[base]" section of /etc/yum.repos.d/CentOS-Base.repo to prevent the broken version from being automatically reinstalled.

But not ideal as won't get any further updates. CentOS 7 is being run on VPSDime using OpenVZ.

The faulty version installed is:  20160308-10.el7

**Comment by okias** [comment]
Hello Adam,

could you be more specific, which type of address you trying to ping? Also could you share your network settings?

**Comment by adambirds** [comment]
I was trying to ping an IPv4 address.

```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 0  (Local Loopback)
        RX packets 1363412  bytes 172572443 (164.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1363412  bytes 172572443 (164.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

venet0: flags=211<UP,BROADCAST,POINTOPOINT,RUNNING,NOARP>  mtu 1500
        inet 127.0.0.1  netmask 255.255.255.255  broadcast 0.0.0.0  destination 127.0.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 0  (UNSPEC)
        RX packets 12632199  bytes 1176558094 (1.0 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21822983  bytes 21000959180 (19.5 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

venet0:0: flags=211<UP,BROADCAST,POINTOPOINT,RUNNING,NOARP>  mtu 1500
        inet 105.236.2.51  netmask 255.255.255.255  broadcast 105.236.2.51  destination 105.236.2.51
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 0  (UNSPEC)

```

My IP is not the one listed at the bottom so just added a fake one in its place.

**Comment by bluepowder** [comment]
This has also been reported here: https://bugs.centos.org/view.php?id=12407

**Comment by Serik0** [comment]
Problem is still actual - no update was issued for iputils package, still cannot ping anything.

**Comment by pevik** [comment]
So the report from the site is:
> 20160308-8 appears to work fine on physical boxes and under LXC, but does not work for IPv4 under OpenVZ. I tried several VPSs, all running under 2.6.32-042stab116.2 and they all had the same problem:
> 
> \# ping 8.8.8.8
> ping: socket: Address family not supported by protocol
> \# ping 127.0.0.1
> ping: socket: Address family not supported by protocol
> \# ping -4 127.0.0.1
> ping: socket: Address family not supported by protocol
> 
> Downgrading to 20121221-7 fixed the problem.

@adambirds @Serik0 OpenVZ on ancient 2.6 kernel isn't really a common setup :(. Which OpenVZ and CentOS version do you use? (with proper setup it's hard to fix the problem).
