### ISSUE TITLE
ping6 crash while getifaddrs return entries with if name NULL

### ISSUE THREAD

**Issue by gpb76** [iputils/iputils#112]
ping6 segfault 0 while getifaddrs return entries with ifa->ifa_name == NULL. 
https://sourceware.org/bugzilla/show_bug.cgi?id=21812 --> this bug hit, causing ping6 to crash

crashed here ==> if (!strncmp(ifa->ifa_name, device, sizeof(device) - 1)

**Comment by pevik** [comment]
It looks like a corner case. It would be nice to have a way how to reproduce it.

**Comment by gpb76** [comment]
I don't see any easy way to reproduce it.  the system has feature of adding /removing the interfaces continuously and seen once.

**Comment by kerolasa** [comment]
@gpb76 if you are still around it would be nice to get pull request I just created tested where you have the issue.

**Comment by kerolasa** [comment]
Lets hope commit d52fa39545bfa8dd6656a5bfc6cf119c1d57381e makes code robust enough that this issue will not happen in future.
