### ISSUE TITLE
Question: why do we need `probe_fd` in ping.c?

### ISSUE THREAD

**Issue by amitsaha** [iputils/iputils#125]
I was going through `ping.c` to understand its working. Is there any reason to use a different (new socket) `probe_fd`? Why can't we use the `sock->fd` which is what we eventually use to send the ICMP packets over. Basically:

```
 git diff
diff --git a/ping.c b/ping.c
index efc4c58..6ff19e2 100644
--- a/ping.c
+++ b/ping.c
@@ -599,7 +599,7 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
        if (source.sin_addr.s_addr == 0) {
                socklen_t alen;
                struct sockaddr_in dst = whereto;
-           int probe_fd = socket(AF_INET, SOCK_DGRAM, 0);
+         int probe_fd = sock->fd;

                if (probe_fd < 0) {
                        perror("socket");
@@ -700,7 +700,7 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
                                fprintf(stderr, "ping: Warning: source address might be selected on device other than %s.\n", device);
                }
 #endif
-           close(probe_fd);
+         //close(probe_fd);
        } while (0);

        if (whereto.sin_addr.s_addr == 0)
```

Obviously there is a good reason for using a different socket. Wondering what that is?

Thanks.

**Comment by svagner** [comment]
Hi! I have the same question. Could someone explain why we have  here separate socket?

**Comment by pevik** [comment]
Hm, that code origin from the code imported by YOSHIFUJI Hideaki from ftp://ftp.inr.ac.ru/ip-routing/iputils-ss020927.tar.gz (see 33370345c7).

I guess it's because different protocol: the "working" socket `sock->fd` use `IPPROTO_ICMP` (value `1`) or `IPPROTO_ICMPV6` (value `58`), but `probe_fd` socket use `0` (`IPPROTO_IP`).

I'm not really familiar with socket protocols, see also [protocols(5)](http://man7.org/linux/man-pages/man5/protocols.5.html) and [socket(2)](http://man7.org/linux/man-pages/man2/socket.2.html).

**Comment by zenczykowski** [comment]
It's a well known socket programming trick to use a UDP socket() connect() getsockname() close() to do a route lookup (this generates no network traffic).

The kernel did not support per-protocol specific routing.  (however that's no longer the case)
So you could simply use a udp socket.
Now we should be using an icmp socket...

This should probably be changed now.  But it's probably not entirely trivial to be certain we don't break something.

**Comment by pavlix** [comment]
> The kernel did not support per-protocol specific routing. (however that's no longer the case) So you could simply use a udp socket. Now we should be using an icmp socket...
> 
> This should probably be changed now. But it's probably not entirely trivial to be certain we don't break something.

I see. But the we should probably just need one socket, right? I did big refactoring on ping long time ago and remember (and documented!) all sorts of issues that emerged, so I can definitely help reviewing changes now. But I honestly don't even remember the `probe_fd` part. It is not even properly distributed between `ping4_common` and `ping6_common` compilation units, as far as I see.
