### ISSUE TITLE
checksum always success in IPv4 ping

### ISSUE THREAD

**Issue by pingz** [iputils/iputils#127]
If checksum in ICMP echo reply packet is not correct, ping will still count it as success, not as corrupt as intended and nothing in output to tell a differ instead of displaying a `BAD CHECKSUM!` like below (IP just an example):

`8 bytes from 203.0.113.4: icmp_seq=1 ttl=84 (BAD CHECKSUM!)`

The PR #121 already had been submit as the attempt to fix this issue.

PS: also as tested, a bad checksum will cause windows ping drop the reply packet and count it as lost.

**Comment by okias** [comment]
#121  merged, closing
