### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Rosanna4** [iputils/iputils#128]
Last release was over 1,5 year ago. There were [64 commits](https://github.com/iputils/iputils/compare/s20161105...master) since. Can you make a new release so users who follow them will benefit from all of this great work? Thank you.

**Comment by pevik** [comment]
Thanks for asking for it. I was thinking about opening the ticket as well some time ago.

**Comment by pevik** [comment]
@okias FYI

**Comment by okias** [comment]
definitely agree, only thing is I'm kinda busy and I wanted to review proper meson support in #120 pull request.

**Comment by jsynacek** [comment]
I suggest postponing the meson support and do a release just for the fixes. I would like a release as well.

**Comment by okias** [comment]
@jsynacek  right right, I almost forgot why I created this github iputils repository.. to avoid individual patching in distros..

So, release is available here: https://github.com/iputils/iputils/releases/tag/s20180629

**Comment by pevik** [comment]
@okias Thanks a lot!

**Comment by pevik** [comment]
@okias do we have checksum or sig files for source tarballs?

**Comment by okias** [comment]
@pevik , nope only signed tag..

**Comment by pevik** [comment]
@okias how does signed tag helps to verify downloaded tarball? Am I missing something?

*.asc file would help
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by okias** [comment]
@pevik done thx

**Comment by pevik** [comment]
@okias Thanks a lot!
