### ISSUE TITLE
Continuing issues with SOCK_DGRAM

### ISSUE THREAD

**Issue by bahamat** [iputils/iputils#129]
This is related to #54 and #32.

I'm getting the following

```
[root@2059cce463fb /]# ping -c 1 8.8.8.8
ping: 8.8.8.8: Address family for hostname not supported
```

With strace:

```
[root@2059cce463fb /]# strace -e trace=socket ping -c 1 8.8.8.8
socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP) = -1 EPROTONOSUPPORT (Protocol not supported)
socket(AF_INET6, SOCK_DGRAM, IPPROTO_ICMPV6) = -1 EPROTONOSUPPORT (Protocol not supported)
socket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6) = 3
ping: 8.8.8.8: Address family for hostname not supported
+++ exited with 2 +++
```

This is on arch linux in Docker.

```
[root@2059cce463fb /]# pacman -Q iputils
iputils 20161105.1f2bb12-2
```

**Comment by pevik** [comment]
@bahamat there have been quite a lot of fixes since 1f2bb12 (November 2016) in `ping*.c` and `ping*.h`.
Can you try it on master? In my case it's ok (but not tested in Docker)

```
strace -e trace=socket ./ping -c 1 8.8.8.8
socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP) = -1 EACCES (Permission denied)
socket(AF_INET, SOCK_RAW, IPPROTO_ICMP) = 3
socket(AF_INET6, SOCK_DGRAM, IPPROTO_ICMPV6) = -1 EACCES (Permission denied)
socket(AF_INET6, SOCK_RAW, IPPROTO_ICMPV6) = 4
socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = 5
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=5.13 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 5.130/5.130/5.130/0.000 ms
+++ exited with 0 +++
```

**Comment by Teutone** [comment]
I came across this same error in debian 9.5 instances on Triton Data Center (SmartOS). If I can be of any help, please tell me how!

**Comment by pevik** [comment]
@Teutone can you please test it with latest master build?

@Teutone @bahamat I guess specifying `-4` does not help.
Can you please report kernel version (`uname -a`) and kernel parameters (`cat /proc/cmdline`)?

Paste somewhere your kernel config (`/boot/config-$(uname -r)`) could also help debugging?

Could you please test my development branch, where I enabled fallback to raw protocol also for IPv4 ?
https://github.com/pevik/iputils/tree/ping/fix-EPROTONOSUPPORT-for-IPv4

**Comment by Teutone** [comment]
Just tried latest master build - not working.
Specifying -4 does not make a difference sadly.

But great news: With your development branch, things work as expected!
Just compiled and tried it on a debian 9.5 container.

Here are the outputs of 

`uname -a`
`Linux hostname 4.10 BrandZ virtual linux x86_64 GNU/Linux`

`cat /proc/cmdline` is empty as is `/boot/` in this specific context (triton container) - I still have to figure out these

**Comment by Smithx10** [comment]
I am trying to build ip utils, and am having issues with... 

```
[root@virt-kube iputils]# ./configure 
The Meson build system
Version: 0.48.2
Source dir: /git/iputils
Build dir: /git/iputils/builddir
Build type: native build
Project name: iputils
Project version: s20180629
Native C compiler: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Checking if "struct icmp6_nodeinfo" compiles: NO
Checking if "struct tm time;" compiles: YES
Library m found: YES
Library resolv found: YES
Checking for function "clock_gettime" : YES
Library disabler-appears-to-disable-executable-build found: NO

meson.build:56:1: ERROR:  C library 'cap' not found

A full log can be found at /git/iputils/builddir/meson-logs/meson-log.txt
```

I can't figure out what C Library or package cap is in.

**Comment by okias** [comment]
@Smithx10 try libcap

**Comment by Smithx10** [comment]
@okias,

I did,  I'm trying to build it on CentOS-7,  and ensured that libcap was installed.

Any ideas?  its failing on the ld -lcap
