### ISSUE TITLE
ping fails to work with puny encoded domains with LC_ALL=C

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#130]
This is forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=898978
  
> while researching the culprit for https://bugs.debian.org/895558 I found                                          
> that check_ping sets LC_ALL=C before executing ping, which then reports                                           
> failure if the hostname to check is puny encoded:                                                                 
>                                                                                                                   
>         $ LC_ALL=C ping www.xn--kleine-knig-yfb.de                                                                
>         ping: www.xn--kleine-knig-yfb.de: Parameter string not correctly encoded                                  
>                                                                                                                   
> It could be argued that LC_ALL=C is a bad choice today, but still I                                               
> think that ping should work anyhow given that there is no need to handle                                          
> non-ASCII chars in the above scenario.                                                                            

I've verified the behavior as of db372e378e4cb6fbf8d3e244a5b3e2a30d6c2130 but have not yet investigated further.

**Comment by pevik** [comment]
@nmeyerhans Fixed.
@pavlix @okias Can you please review it?

**Comment by pevik** [comment]
@okias @pavlix  I include  `<locale.h>` in `ping.c`, while it's included conditionally also in `ping.h`. Maybe you prefer it only in `ping.h` (move out of the condition).

**Comment by nmeyerhans** [comment]
I can confirm that the proposed fix in #131 resolves the issue.

**Comment by okias** [comment]
just move locale.h outside ifndef in ping.h, otherwise fine :)

**Comment by pevik** [comment]
@okias Done. Warnings in clang builds in ping aren't caused by this change (it'd be nice to have it fixed, but next time).
