### ISSUE TITLE
[RFE] Add -o flag to ping (like BSD ping) to exit after a successful reply

### ISSUE THREAD

**Issue by e-minguez** [iputils/iputils#132]
It seems quite useful https://twitter.com/Andrew___Morris/status/1000500584842170368

BSD seems to support it https://www.freebsd.org/cgi/man.cgi?ping(8)

**Comment by pevik** [comment]
+1

**Comment by okias** [comment]
sounds like useful feature, I'm open to merging implementation

**Comment by jsynacek** [comment]
The same can be accomplished by using `-c 1 -w <timeout>`, can it not?

**Comment by okias** [comment]
@jsynacek well, I think you can omit `-w <timeout>` and you'll get exact same functionality, but haven't looked into BSD implementation, only man page

**Comment by jsynacek** [comment]
> I wonder, if would make sense to use something like "-1" to infinite timeout (deadline)..

In my opinion, no, because you can set it to something hilariously large, which then practically means "infinity".

**Comment by kerolasa** [comment]
ping already has too many options. Functionality mentioned in twitter message can be implemented with a simple shell oneliner, that can be converted to a script if needed.

```
until ping -W 2 -c 1 -q 185.1.2.3 >/dev/null; do true; done && ssh 185.1.2.3
```

**Comment by polynomialspace** [comment]
A naive attempt at this can be found at 58948a2fd9663d1b00a85b68b21038c465ff95d6.
I was looking to extend it to allow setting a count (rather than exiting after only one successful reply), but that's probably going for a bit too much considering the comment on ping already being too featureful.
