### ISSUE TITLE
Why double "ping: socket: Permission denied, attempting raw socket..." occurs in verbose mode

### ISSUE THREAD

**Issue by initrider** [iputils/iputils#133]
I've installed [this](https://www.archlinux.org/packages/core/x86_64/iputils) `iputils` package on my Arch Linux, which using [Cabatibles](https://wiki.archlinux.org/index.php/Capabilities) instead of SUID to run ping from. The ping works from **root and from normal user** correctly, but if I run ping with -v option on **both** these users, ping will print that message before pinging. See:
`ping google.com -c 1`

> PING google.com (173.194.221.100) 56(84) bytes of data.
64 bytes from lm-in-f100.1e100.net (173.194.221.100): icmp_seq=1 ttl=49 time=17.8 ms

`ping google.com -c 1 -v`

> ping: socket: Permission denied, attempting raw socket...
ping: socket: Permission denied, attempting raw socket...
PING google.com (173.194.221.102) 56(84) bytes of data.
64 bytes from lm-in-f102.1e100.net (173.194.221.102): icmp_seq=1 ttl=49 time=16.7 ms

I've found the same problem here https://bugzilla.redhat.com/show_bug.cgi?id=1501110 and fix here https://github.com/iputils/iputils/pull/107 . The problem seems to be only normal user related, but I have that messages on root user too.

**P.S.** Debian 9 uses SUID, however on root and regular user there is the same behavior.

**Comment by pevik** [comment]
Seeing you closed the ticket. I wonder whether you solved your problem?

**Comment by yankee14** [comment]
What was causing this issue for you? I'm having the same issue in Armbian.
