### ISSUE TITLE
ping does not respect LOCALDOMAIN

### ISSUE THREAD

**Issue by mortya** [iputils/iputils#135]
Most commands on a Linux box respect the environment variable LOCALDOMAIN by way of the standard host resolving libraries.  LOCALDOMAIN lets one set up a user-level DNS/resolving search path.  The ping command does not respect LOCALDOMAIN.  This should be fixed.

The LOCALDOMAIN environment variable is documented in resolv.conf.

**Comment by mortya** [comment]
I tested on Debian 8.11, CentOS 7.5.1804, and Ubuntu 17.10.  All work for LOCALDOMAIN with "regular" commands such as curl, wget, nc, and getent.  nslookup, host, and dig do not work, because those are commands that are specifically intended to debug DNS resolving and therefore have their own resolver libraries.

For example, here is Debian.  (Note that we're getting 404s from the google webservers, because the google servers don't return something for "www", only for "www.google.com".  But you can see that the response is coming from google rather than from my local "www" server.)

```morty@scaramouche:~ 20:04:21 662$ lsb_release -sir
Debian
8.11
morty@scaramouche:~ 20:04:35 663$ env LOCALDOMAIN=google.com curl -s www | grep -ci google
2
morty@scaramouche:~ 20:04:40 664$ env -u LOCALDOMAIN curl -s www | grep -ci google
0
morty@scaramouche:~ 20:06:34 669$ env LOCALDOMAIN=google.com wget www
--2018-10-15 20:06:52--  http://www/
Resolving www (www)... 2607:f8b0:4006:814::2004, 172.217.11.4
Connecting to www (www)|2607:f8b0:4006:814::2004|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-15 20:06:52 ERROR 404: Not Found.

morty@scaramouche:~ 20:06:52 670$ env LOCALDOMAIN=google.com nc www 80
HEAD / HTTP/1.1

HTTP/1.1 200 OK
Date: Mon, 15 Oct 2018 20:07:09 GMT
Expires: -1
Cache-Control: private, max-age=0
Content-Type: text/html; charset=ISO-8859-1
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Server: gws
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: 1P_JAR=2018-10-15-20; expires=Wed, 14-Nov-2018 20:07:09 GMT; path=/; domain=.google.com
Set-Cookie: NID=141=aN7KM1EqDaCQ93NUd9Tytn1752F7sCxnoP_d0dHXQQASvxchfk2FKvFCtVZbWxI5ilmIpMN4MF8NPgrfrIEqBFNwRqkPG6hFQWo25I9J45NoMlhqqzD06dBcmWoFsfAv; expires=Tue, 16-Apr-2019 20:07:09 GMT; path=/; domain=.google.com; HttpOnly
Transfer-Encoding: chunked
Accept-Ranges: none
Vary: Accept-Encoding



^]q
HTTP/1.0 400 Bad Request
Content-Length: 54
Content-Type: text/html; charset=UTF-8
Date: Mon, 15 Oct 2018 20:07:22 GMT

<html><title>Error 400 (Bad Request)!!1</title></html>morty@scaramouche:~ 20:07:22 671$
morty@scaramouche:~ 20:23:45 678$ env LOCALDOMAIN=google.com getent hosts www
2607:f8b0:4006:814::2004 www.google.com
morty@scaramouche:~ 20:23:47 679$
```

**Comment by kerolasa** [comment]
I found my issue. If systemd-resolved.service is running it breaks LOCALDOMAIN.

Second observation, if I ping as root LOCALDOMAIN setting works. Problem seems to be related to getaddrinfo() hints that are messed up by create_socket(&sock6) call. I will need to dig deeper into this sometime later; hopefully soon.

**Comment by kerolasa** [comment]
Correction. There's nothing wrong with create_socket() or hints. While compiling multiple times, trying various things I lost track. After running my tests I have started to think adding any cabability to any binary breaks LOCALDOMAIN lookup. For example:

```
$ cp $(which curl) /tmp/ ; sudo setcap cap_chown+ep /tmp/curl; /tmp/curl www
curl: (6) Could not resolve host: www
```

**Comment by nmeyerhans** [comment]
This is by design. libc has a set of variables that it removes from the environment before executing programs with elevated privileges. See https://manpages.debian.org/stretch/manpages/ld.so.8.en.html#Secure-execution_mode and https://sources.debian.org/src/glibc/2.27-6/sysdeps/generic/unsecvars.h/ for details.

**Comment by kerolasa** [comment]
Thank you @nmeyerhans secure-execution mode seems to the cause why LOCALDOMAIN environment variable is removed. That making ping to go around this security mechanism does not sound feasible.

**Comment by mortya** [comment]
That makes sense.  Thanks!
