### ISSUE TITLE
please document fork status

### ISSUE THREAD

**Issue by vapier** [iputils/iputils#14]
please update the top level README.md to document the status of this repo wrt upstream.  unless you happen to come across the announce buried in the netdev archives [1], it's confusing to people that this might be official.  especially since you've got the "iputils" username and not just a project named "iputils" under your own username.

this repo is also out of sync with the upstream git repo [2].  please merge with the latest master branch, and pull in all of its historical tags.

[1] http://www.spinics.net/lists/netdev/msg279881.html
[2] http://www.linux-ipv6.org/gitweb/gitweb.cgi?p=gitroot/iputils.git

**Comment by okias** [comment]
Thank you. I'll pull remaining commits ASAP (after error 503 disappear from [2]).

About -fork-. Yoshfuji still didn't tried contact me, so I'd like to keep this at is (after merging few new commits it should be in parity with his iputils with additional fixes on top - as usual).

Also we're close to make progress about merging ping and ping6 together, which should be big step forward.
