### ISSUE TITLE
Time rounding breaks time display

### ISSUE THREAD

**Issue by abrasive** [iputils/iputils#141]
Hi,

the rounding correction merged in commit 5f5a34c1b4d418ea68c27c00d3a0c173dd5560d6 causes erroneous output when the fractional part rounds to 1.
For example, the value 4.996ms should be displayed as 5.00ms, but is displayed as 4.100ms:
```
64 bytes from 10.42.4.4: icmp_seq=110 ttl=64 time=2.56 ms
64 bytes from 10.42.4.4: icmp_seq=111 ttl=64 time=4.100 ms
64 bytes from 10.42.4.4: icmp_seq=112 ttl=64 time=4.76 ms
```

**Comment by dhxgit** [comment]
Should be fixed with PR #142
