### ISSUE TITLE
sync with iputils-YH

### ISSUE THREAD

**Issue by xosevp** [iputils/iputils#15]
http://www.linux-ipv6.org/gitweb/gitweb.cgi?p=gitroot/iputils.git brings three new patches since latest sync:

- ping,ping6 doc: More description on CAP_NET_RAW usage.
- iputils ping/ping6: add (non-raw) ICMP socket support
- 4 iputils ping/ping6: Add a function to check if a packet is ours

-thanks-

**Comment by okias** [comment]
Hey,

at this moment  http://www.linux-ipv6.org/gitweb/gitweb.cgi?p=gitroot/iputils.git  gives me error 503.

If you want, you can try merge them, I think they'll have to be changed little bit to fit on our codebase.

In case you'll be not interested in merging them and sending pull request, I'll do it.

Thank you for report :)

**Comment by okias** [comment]
Done.
