### ISSUE TITLE
s20190324 fails to build w/musl

### ISSUE THREAD

**Issue by dtzWill** [iputils/iputils#168]
Release reintroduces problem fixed in #35 -- looks like someone alpha-sorted the headers which broke compilation with musl (4f0cfdb215c47e04f6b0f73306f8e902cb836b17).

`<sys/time.h>` needs to be included before `<linux/errqueue.h>`, as it is in `ping.h` for example.

This patch seems to fix the issue, for example: https://github.com/dtzWill/nixpkgs/blob/edc52397993195f6705dce01c411120d33e53e95/pkgs/os-specific/linux/iputils/timespec.patch .

I'm not sure if there's a way to do these includes "properly" to avoid this sort of problem without needing to build-test on various environments or in a less fragile way, but if there is that would be best for all I'd imagine :).

**Comment by pevik** [comment]
@dtzWill Thanks for report, @kerolasa could you merge it?

**Comment by kerolasa** [comment]
Thank you for regression report. I added a commit that differs a little bit, c9aca1b53324bcd1b5a2de5c645813f80eccd016. What comes to hitting issues there are two things that could be done. All projects, including iputils, need to run tests that catch regressions like this as reported by @pevik in https://github.com/iputils/iputils/issues/169. Secondly, it would be great to get fix to linux/errqueue.h making it less fragile.
