### ISSUE TITLE
Docker based travis CI for better testing builds with different distros (including MUSL)

### ISSUE THREAD

**Issue by pevik** [iputils/iputils#169]
Our travis CI is based on `gcc` and `clang` builds, downloading `ninja` and installing `meson` from `pip. This IMHO inappropriate as we provide basic networking utils, so we should care a bit about 
linux distros. I propose moving into docker base builds to test iputils under current distros. That does not stop us using different compilers. As an example can be travis configuration from LTP (https://github.com/linux-test-project/ltp/blob/master/.travis.yml).

This would help us to test MUSL builds (via Alpine Linux distro) to avoid issues like #168 #117.
\+ We're not testing non-default setup nowadays, which is also bad.

**Comment by kerolasa** [comment]
I agree more testing and especially automatic testing would be great.

That said I have no glue why my archlinux musl (see versions below) did not have the same problem as reported in #168. When I look kernel header linux/errqueue.h it does not do include sys/time.h so I don't know what to think about that. Would this issue been caught by testing or not, that's anyone's guess. But with as little testing we have currently probability of catching issues early on is pretty low.

* kernel-headers-musl 3.12.6_6-1
* musl 1.1.21-1

**Comment by pevik** [comment]
Merged as e3fd528.
