### ISSUE TITLE
ping -N help should output to stdout, exit with 0

### ISSUE THREAD

**Issue by scop** [iputils/iputils#176]
`ping -N help` should produce its output to stdout and exit with status 0. Currently outputs to stderr and exits with 2 which is ok when the handler is invoked on usage error, but `-N help` is not an error so these should indicate success (stdout, 0 as mentioned).

**Comment by kerolasa** [comment]
Thank you @scop for bug report. Printing and exit value are fixed in commit 1d628d132d26c37185a2b480f0b0285579bb0a1b.
