### ISSUE TITLE
tag missing for 20190515 release

### ISSUE THREAD

**Issue by okias** [iputils/iputils#179]
```
$ git describe | awk -F- '{print $1}'
s20190324
```
just tag it correctly and it's perfect :+1:  Thank you

**Comment by pevik** [comment]
Agree. + it'd be nice if tag was signed, as okias did for [s20180629](https://github.com/iputils/iputils/releases/tag/s20180629).

See info:
https://help.github.com/en/articles/signing-commits
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
https://github.com/ensime/ensime-server/issues/174

**Comment by kerolasa** [comment]
Well, I can see the tag here https://github.com/iputils/iputils/tags and it was pushed to origin, and signed. What I forgot was pushing master branch. Done now.

    iputils $ git show s20190515 --show-signature
    tag s20190515
    Tagger: Sami Kerola <kerolasa@iki.fi>
    Date:   Wed May 15 21:14:10 2019 +0100
    
    iputils-s20190515
    -----BEGIN PGP SIGNATURE-----
    
    iQIzBAABCAAdFiEEJZmbQH+2qbcBu/HkDUb+9+Ydu0YFAlzccxIACgkQDUb+9+Yd
    u0YkXBAAqG5lobSiJzhG5GFbj0ZZqAY5m0PA0F5FrwzD6eXABzwUb8UleOZlL522
    gWfqIaGPj4qxOcKQzyTcecA42xCs5cXEiIaA8fBzOmfbwnnPanHul+LqVfsoBKI/
    Rz8/GI/oZZGD+d9alxoYnmsVmQaStwLDSYndzIpfwv/Cj4XjY7ZzwBCCCiFRZRYR
    JPBNd9EbnfHbw9WMwJHncMIjcmMNCQt1jvd+5M+HlKYgD2h/zRBDRxL5f+ceRHsI
    1P/Hbnlw5IQg0Y2RhmdNSKrbZijsKPqrqOULlurS862m4Zm54UnkWpFNXMUMhhMZ
    C5oEEd8QEAx60Z3SWdx3S+BcsBuJgkylqF50XQfF8WfC4VcZeBW1LwncTUMv0fuB
    zZJDo66ST6nXaRBHAljnzciIqxtGA1FjicP7flmuzIgvGGBdqjH/0BlRsW0m36AI
    7mivgDKVWna74KyFV2idFsPqCRN8IWhZFVwnpmP3dhiIB7rh4aT4yGaQS1+WQgO/
    ERILNk9VCUTKJaQSS8ZBCZiHwU7TZP2sV8XNqtAZVrQrT8K1whAuvFyQNEKwf2DN
    FgAOf5I+eEX+b59rEMIFUa45FagpWEesxqcpt8oEuPNylSmDUf7rzqK6NFispJys
    vijtEzNyN2TDP5s7d/j3FK6Nfvb9I3r1FnEwxyFd0oHbCcPhtcU=
    =mHMm
    -----END PGP SIGNATURE-----
    
    commit 37facc7e70139bf5e05448b4412ac71ab3333f62 (HEAD -> master, tag: s20190515)
    gpg: Signature made Wed 15 May 2019 21:14:10 BST
    gpg:                using RSA key 25999B407FB6A9B701BBF1E40D46FEF7E61DBB46
    gpg: Good signature from "Sami Kerola (https://www.iki.fi/kerolasa/) <kerolasa@iki.fi>" [ultimate]
    Author: Sami Kerola <kerolasa@iki.fi>
    Date:   Wed May 15 21:14:10 2019 +0100
    
        release: iputils-s20190515
        
        Signed-off-by: Sami Kerola <kerolasa@iki.fi>

**Comment by pevik** [comment]
Then you should upload `iputils-s20190515.tar.gz.asc` for people to be able to verify signing.
s20180629 is the only release with this file uploaded, see https://github.com/iputils/iputils/releases/tag/s20180629

**Comment by kerolasa** [comment]
Signatures are created & uploadded.

    for i in iputils-s20190* ; do gpg -s -a --detach-sign $i ; done

**Comment by pevik** [comment]
@kerolasa More things about files: signed (GPG) files are `iputils-s20190515.{tar.gz,zip}.asc` but files are without `iputils-`: `s20190515.{tar.gz,zip}`. It'd be nice to if they're the same as for verification they must be the same:

```
$ gpg --verify-files iputils-s20190515.tar.gz.asc s20190515.tar.gz
gpg: no signed data
gpg: can't hash datafile: No data

$ mv iputils-s20190515.tar.gz.asc s20190515.tar.gz.asc

$ gpg --verify-files s20190515.tar.gz.asc s20190515.tar.gz
gpg: assuming signed data in 's20190515.tar.gz'
gpg: Signature made Pá 17. května 2019, 18:30:40 CEST
gpg:                using RSA key 25999B407FB6A9B701BBF1E40D46FEF7E61DBB46
```

**Comment by kerolasa** [comment]
When I download with firefox I get iputils-s20190515.tar.gz iputils-s20190515.zip although link does not have that prefix. Notice that .asc file for s20180629 also had iputils- prefix.

**Comment by kerolasa** [comment]
Please reopen if there is something more to add to this. Notice that due to procedural mishaps I added instructions to avoid repeating mistakes in future.

https://github.com/iputils/iputils/blob/master/Documentation/README.maintainer#L35-L61
