### ISSUE TITLE
arping: Wrong exit code 1 on successfull run

### ISSUE THREAD

**Issue by MarcusRoeckrath** [iputils/iputils#190]
Tests made using:
arping -V
arping from iputils s20190515

Although a run was successfull, arping returns an exit exit code of 1:

arping -f -c 1 -I eth0   192.168.1.1 ; echo $?
ARPING 192.168.1.1 from 192.168.1.3 eth0
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  0.688ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
1

arping  -c 1 -I eth0   192.168.1.1 ; echo $?
ARPING 192.168.1.1 from 192.168.1.3 eth0
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  0.717ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
1

Now using -c 2 resulting in an exit code of 0:

arping  -c 2 -I eth0   192.168.1.1 ; echo $?
ARPING 192.168.1.1 from 192.168.1.3 eth0
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  0.662ms
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  0.706ms
Sent 2 probes (1 broadcast(s))
Received 2 response(s)
0

An older version

./arping -V
arping utility, iputils-s20161105

did not show this issue, returning exit code 0 always:

arping -f -c 1 -I eth0 192.168.1.1 ; echo $?
ARPING 192.168.1.1 from 192.168.1.10 eth0
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  1.634ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
0

arping -c 1 -I eth0 192.168.1.1 ; echo $?
ARPING 192.168.1.1 from 192.168.1.10 eth0
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  1.371ms
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
0

arping -c 2 -I eth0 192.168.1.1 ; echo $?
ARPING 192.168.1.1 from 192.168.1.10 eth0
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  1.348ms
Unicast reply from 192.168.1.1 [11:22:33:44:55:66]  1.237ms
Sent 2 probes (1 broadcast(s))
Received 2 response(s)
0

**Comment by kerolasa** [comment]
Thank you for bug report @MarcusRoeckrath. This turned out to be pretty embarrassing bug from my part. Fixed in commit 84ca65ca980315c73f929fed8b6f16bbd698c3a0.

**Comment by socketpair** [comment]
Fixed in version s20190709
