### ISSUE TITLE
New release 07/2019?

### ISSUE THREAD

**Issue by ffontaine** [iputils/iputils#191]
Could you tag a new release?
It would be nice as we could remove all our patches from buildroot.

Thanks,

Fabrice

**Comment by kerolasa** [comment]
Perhaps after couple recently opened bugs are sorted. But I am in middle of long days in work until a project is delivered so I will not do anything in open source front until August.

**Comment by pevik** [comment]
I guess release can wait until August. Or could @okias make a release? I guess, iputils needs more maintainers :(.

**Comment by okias** [comment]
Please send remainder on the weekend. I'll try my best.

**Comment by pevik** [comment]
@okias gentle reminder for a release :) (I'll be offline during weekend)

**Comment by pevik** [comment]
I've sent 2 PR, but they should probably go for next release. I'll release iputils without sometimes this week.

**Comment by pevik** [comment]
Released: https://github.com/iputils/iputils/releases/tag/s20190709
