### ISSUE TITLE
Question: How do you calculate RTT?

### ISSUE THREAD

**Issue by austin-barrington** [iputils/iputils#192]
Hey, I am just going over how you are calculating RTT for an ICMP ping but it gets really confusing and all over the place (could also be my lack of understanding).

Could someone give me a description to help me understand how it is calculated?

ps. I didn't want to create an issue but I didn't know where else to ask...

**Comment by ValZapod** [comment]
@austin-barrington Here you are https://stackoverflow.com/questions/36976782/how-the-ping-implementation-calculating-the-round-trip-time

But if seriously here is an implementation in C++ https://github.com/ymirsky/burstPing
Maybe it'll be good to have it in our ping. Nanoseconds... Not picoseconds but good enough))
