### ISSUE TITLE
Does the effective bit need to be set?

### ISSUE THREAD

**Issue by amouat** [iputils/iputils#194]
On this line: https://github.com/iputils/iputils/blob/master/build-aux/setcap-setuid.sh#L20, the effective bit is set as well as adding `cap_net_raw` to the permitted set. However, the utilities (or at least ping) are capabilities aware, in that they explicitly add and remove capabilities and set the effective bit in code.

Testing the ping binary with `setcap 'cap_net_raw+p'` only, it seems to work fine.

Could we remove the `e` flag, so things work as described in https://www.kernel.org/doc/ols/2008/ols2008v1-pages-163-172.pdf ? The advantage would be that the window of time the binary holds the cap_net_raw privilege is further reduced.

I'm surprised this hasn't come up before though, so I'm assuming I'm missing something.

**Comment by kerolasa** [comment]
Thank you @amouat for pointing out permission bit could be removed, commit 368c345ff9a648ea28ece9725522f5363b869823 addresses the issue.

**Comment by amouat** [comment]
No problem, but @tamalsaha pointed out that the `echo` line was changed, but not the code :)

https://github.com/iputils/iputils/pull/196 addresses this.
