### ISSUE TITLE
ccc-analyzer hints

### ISSUE THREAD

**Issue by okias** [iputils/iputils#2]
```
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c ping.c -DCAPABILITIES   -o ping.o
ping.c:1095:4: warning: Value stored to 'i' is never read
                        i -= 4;
                        ^    ~
ping.c:1126:5: warning: Value stored to 'cp' is never read
                                cp += i;
                                ^     ~
2 warnings generated.
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c ping_common.c -DCAPABILITIES  -o ping_common.o
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall ping.o ping_common.o -lcap    -o ping
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c clockdiff.c -DCAPABILITIES -o clockdiff.o
clockdiff.c:62:12: warning: Assigned value is garbage or undefined
                                u.c[0] = *(char *)addr;
                                       ^ ~~~~~~~~~~~~~
clockdiff.c:63:12: warning: Assigned value is garbage or undefined
                                u.c[1] = *((char *)addr+1);
                                       ^ ~~~~~~~~~~~~~~~~~
clockdiff.c:67:9: warning: Assigned value is garbage or undefined
                                sum += *addr++;
                                    ^  ~~~~~~~
clockdiff.c:136:18: warning: Value stored to 'icp' during its initialization is never read
        struct icmphdr *icp = (struct icmphdr *) packet;
                        ^~~   ~~~~~~~~~~~~~~~~~~~~~~~~~
clockdiff.c:178:2: warning: Value stored to 'msgcount' is never read
        msgcount = 0;
        ^          ~
clockdiff.c:313:18: warning: Value stored to 'icp' during its initialization is never read
        struct icmphdr *icp = (struct icmphdr *) packet;
                        ^~~   ~~~~~~~~~~~~~~~~~~~~~~~~~
clockdiff.c:355:2: warning: Value stored to 'msgcount' is never read
        msgcount = 0;
        ^          ~
clockdiff.c:637:29: warning: Assigned value is garbage or undefined
                ((__u32*)(rspace+4))[0*2] = myaddr.sin_addr.s_addr;
                                          ^ ~~~~~~~~~~~~~~~~~~~~~~
8 warnings generated.
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall clockdiff.o -lcap   -o clockdiff
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c rdisc.c  -o rdisc.o
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall rdisc.o    -o rdisc
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c arping.c  -DCAPABILITIES   -o arping.o
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall arping.o  -lcap    -o arping
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c tftpd.c  -o tftpd.o
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c tftpsubs.c  -o tftpsubs.o
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall tftpd.o tftpsubs.o    -o tftpd
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c rarpd.c  -o rarpd.o
rarpd.c:435:22: warning: The left operand of '!=' is a garbage value
        if (sll.sll_pkttype != PACKET_BROADCAST &&
            ~~~~~~~~~~~~~~~ ^
1 warning generated.
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall rarpd.o    -o rarpd
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c tracepath6.c  -o tracepath6.o
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall tracepath6.o    -o tracepath6
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c traceroute6.c -DCAPABILITIES  -o traceroute6.o
traceroute6.c:612:6: warning: Value stored to 'reset_timer' is never read
                                        reset_timer = 1;
                                        ^             ~
1 warning generated.
ccc-analyzer   -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall traceroute6.o -lcap    -o traceroute6
ccc-analyzer -O3 -g -fno-strict-aliasing -Wstrict-prototypes -Wall -D_GNU_SOURCE  -c ping6.c -DCAPABILITIES    -DUSE_GNUTLS -o ping6.o
ping6.c:1496:8: warning: Value stored to 'p' during its initialization is never read
        __u8 *p = h + 4;
              ^   ~~~~~
1 warning generated.
```

**Comment by pavlix** [comment]
The unused values seem to be pretty easy. But the *garbage* messages seem to be nonsense. Is there any documentation for those?

    diff --git a/clockdiff.c b/clockdiff.c
    index 4473b93..8c6ff04 100644
    --- a/clockdiff.c
    +++ b/clockdiff.c
    @@ -133,7 +133,7 @@ measure(struct sockaddr_in * addr)
     	long delta1, delta2;
     	struct timeval tv1, tout;
     	unsigned char packet[PACKET_IN], opacket[64];
    -	struct icmphdr *icp = (struct icmphdr *) packet;
    +	struct icmphdr *icp;
     	struct icmphdr *oicp = (struct icmphdr *) opacket;
     	struct iphdr *ip = (struct iphdr *) packet;
     
    @@ -175,7 +175,7 @@ empty:
     	((__u32*)(oicp+1))[1] = 0;
     	((__u32*)(oicp+1))[2] = 0;
     	FD_ZERO(&ready);
    -	msgcount = 0;
    +	msgcount;
     
     	acked = seqno = seqno0 = 0;
     
    @@ -310,7 +310,7 @@ measure_opt(struct sockaddr_in * addr)
     	long delta1, delta2;
     	struct timeval tv1, tout;
     	unsigned char packet[PACKET_IN], opacket[64];
    -	struct icmphdr *icp = (struct icmphdr *) packet;
    +	struct icmphdr *icp;
     	struct icmphdr *oicp = (struct icmphdr *) opacket;
     	struct iphdr *ip = (struct iphdr *) packet;
     
    @@ -352,7 +352,7 @@ empty:
     	((__u32*)(oicp+1))[2] = 0;
     
     	FD_ZERO(&ready);
    -	msgcount = 0;
    +	msgcount;
     
     	acked = seqno = seqno0 = 0;
     
    diff --git a/ping.c b/ping.c
    index 4455091..b07f718 100644
    --- a/ping.c
    +++ b/ping.c
    @@ -1357,8 +1357,6 @@ void pr_options(unsigned char * cp, int hlen)
     		case IPOPT_LSRR:
     			printf("\n%cSRR: ", *cp==IPOPT_SSRR ? 'S' : 'L');
     			j = *++cp;
    -			i = *++cp;
    -			i -= 4;
     			cp++;
     			if (j > IPOPT_MINOFF) {
     				for (;;) {
    @@ -1391,8 +1389,6 @@ void pr_options(unsigned char * cp, int hlen)
     			    && !memcmp(cp, old_rr, i)
     			    && !(options & F_FLOOD)) {
     				printf("\t(same route)");
    -				i = ((i + 3) / 4) * 4;
    -				cp += i;
     				break;
     			}
     			old_rrlen = i;
    diff --git a/ping6_common.c b/ping6_common.c
    index d6965dc..1665b01 100644
    --- a/ping6_common.c
    +++ b/ping6_common.c
    @@ -1294,7 +1294,7 @@ static
     void pr_niquery_reply_addr(struct ni_hdr *nih, int len)
     {
     	__u8 *h = (__u8 *)(nih + 1);
    -	__u8 *p = h + 4;
    +	__u8 *p;
     	__u8 *end = (__u8 *)nih + len;
     	int af;
     	int aflen;
    diff --git a/traceroute6.c b/traceroute6.c
    index fdc916b..48fc5c5 100644
    --- a/traceroute6.c
    +++ b/traceroute6.c
    @@ -609,7 +609,6 @@ int main(int argc, char *argv[])
     			while ((cc = wait_for_reply(icmp_sock, &from, &to, reset_timer)) != 0) {
     				gettimeofday(&t2, &tz);
     				if ((i = packet_ok(packet, cc, &from, &to, seq, &t1))) {
    -					reset_timer = 1;
     					if (memcmp(&from.sin6_addr, &lastaddr, sizeof(from.sin6_addr))) {
     						print(packet, cc, &from);
     						memcpy(&lastaddr,

**Comment by pavlix** [comment]
Some of them might be further simplified if we were able to test the changes.

**Comment by okias** [comment]
Agree, push your patch. Thank you!

**Comment by pavlix** [comment]
I'll close it via commit message...
