### ISSUE TITLE
There are new patches at netdev ml

### ISSUE THREAD

**Issue by xosevp** [iputils/iputils#20]
from Mike Frysinger, https://marc.info/?l=linux-netdev&w=2&r=1&s=iputils&q=b
[PATCH iputils] tftpd: fix syslog setup
[PATCH iputils] ping6: allow disabling of openssl support
[PATCH iputils] ping: fix -i number parsing in locales

and maybe others older.

-thanks-

**Comment by okias** [comment]
If you miss some patch, please send him as pull request :)

Some of these should be already incorporate in code (maybe different commit name), if something missing, let me know

**Comment by xosevp** [comment]
On 06/11/2015 11:44 PM, David Heidelberg wrote:

> If you miss some patch, please send him as pull request :)

CC: Mike Frysinger <vapier@gentoo.org>

> Some of these should be already incorporate in code (maybe
> different commit name), if something missing, let me know

These three from Mike Frysinger, https://marc.info/?l=linux-netdev&w=2&r=1&s=iputils&q=b
[PATCH iputils] tftpd: fix syslog setup
[PATCH iputils] ping6: allow disabling of openssl support
[PATCH iputils] ping: fix -i number parsing in locales

**Comment by pavlix** [comment]
Were those patches added already or is anyone going to make the pull request?

**Comment by pavlix** [comment]
@okias

**Comment by xosevp** [comment]
For unknown reasons some of them were not included in YOSHIFUJI-upstream:  https://sourceforge.net/p/iputils/code/ci/HEAD/tree/

**Comment by okias** [comment]
by brief look it seems we have incorporated these changes.

If there still persist some bug or some patch is missing, please open bug related to specific issue/patch.

Thank you
