### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ValZapod** [iputils/iputils#205]
https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping.c#L666
What is this? It is not do while.

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping6_common.c#L476-L479

Find a typo in a second. 476 and 479 are the same.

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ninfod/ninfod_core.c#L525-L530

I suppose rc < 0 is always false as ni_policy() cannot return anything besides 1 and 0.

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping_common.c#L812

Genius diff!! Space should be there. Maybe also add explicit type cast (double)?
https://github.com/iputils/iputils/commit/a9715fe2c6ec0843ab09e15994c9d925fd17868f#diff-d581b1b286add5cb34d036f5bdf068b8R814

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping6_common.c#L596

 A call of the 'memcpy' function will lead to the 'ai->ai_addr' buffer becoming out of range.

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping6_common.c#L204-L206

Very funny. seq < 0. Really?

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping6_common.c#L218

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping6_common.c#L221

A call of the 'memcmp' function will lead to underflow of the buffer 'digest'.

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping_common.c#L313
`if (waittime < 1000 * (unsigned long)interval)` maybe

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ping.c#L560

pointer hostname is global and hnamebuf[] is in ping4_run(). Not a good idea to use it like this. Scopes you know.

https://github.com/iputils/iputils/blob/991916bf6ee6469285621e47038ee7aeab6ce9e8/rdisc.c#L1144
This is always false.

https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ninfod/ninfod_addrs.c#L288-L292
https://github.com/iputils/iputils/blob/129ad44a1a58b940cb0c1075010f5d16a750eda6/ninfod/ninfod_addrs.c#L118-L123
'init_nodeinfo_ipv4addr' function is fully equivalent to the body of 'init_nodeinfo_ipv6addr' function

**Comment by ValZapod** [comment]
Ah, yes, please allso add docbook-xsl-ns gcrypt20-dev and ninja-built packets to travis...

**Comment by kerolasa** [comment]
Many of the proposed changes were done in b572ac3b41715446714d6e2a8c5b77a160bc470b.

If you want gcrypt20-dev, ninja, or travis changes please contribute.

**Comment by ValZapod** [comment]
@kerolasa And the first was solved in 9e08707. So that one was the worst)) What about memcmp()? Are those of any value? Or it is kernel magic?

**Comment by ValZapod** [comment]
@kerolasa Unfortunately, you fogot to also rename this two places:

https://github.com/iputils/iputils/blob/b572ac3b41715446714d6e2a8c5b77a160bc470b/ninfod/ninfod_core.c#L129

https://github.com/iputils/iputils/blob/b572ac3b41715446714d6e2a8c5b77a160bc470b/ninfod/ninfod_core.c#L141

**Comment by kerolasa** [comment]
I do not see anything wrong in use of memcpy(). If you disagree send a pull request.

And yes, the C++ comment are terrible. Removal done in aed8db0345479db50e2530f1d41ef8c9bc275541.

**Comment by kerolasa** [comment]
@ValZapod Do not hijack bug discussion threads.

**Comment by ValZapod** [comment]
@kerolasa I thought it would be nice to test it for you. 😪😪 Anyway, I thought that microseconds are not supported by ping or are they?
