### ISSUE TITLE
Add instructions how to install into a prefix to INSTALL

### ISSUE THREAD

**Issue by krichter722** [iputils/iputils#21]
or add a `configure` script which should provide an intuitive way to achieve this

**Comment by pavlix** [comment]
While it would be nice to have some docs for it, the DESTDIR is a ubiquitous way to specify the root directory for makefiles. It might be useful to use autotools for the project as it has other advantages as well.

**Comment by pavlix** [comment]
@okias It would be nice to accept this patch and get the bug closed.
