### ISSUE TITLE
unify ping -s packet size checks

### ISSUE THREAD

**Issue by ghormoon** [iputils/iputils#210]
currently, if user does not think about IP packet size limit at all and guesses random numbers to use with ping -s, he might get two different errors:

```
$ ping 8.8.8.8 -s 500000
ping: packet size too large: 500000
$ ping 8.8.8.8 -s 90000
Error: packet size 90000 is too large. Maximum is 65507
```
seems it's handledseparately at two parts of ping.c:

```                case 's':
                        datalen = strtol_or_err(optarg, _("invalid argument"), 0, MAXPACKET - 8);
                        break;
```
where MAXPACKET is defined in pin.h as 128000 - is there any reason for this big number?

and 

```
	if (datalen > 0xFFFF - 8 - optlen - 20)
		error(2, 0, _("packet size %d is too large. Maximum is %d"),
datalen, 0xFFFF - 8 - 20 - optlen);
```

i suggest unifying the output to show the limit properly, so if user inputs some number over 128000, it will tell him the proper limit too. or maybe check for the exact size at that point already.

**Comment by kerolasa** [comment]
These size limitations feel like premature optimisation. I think it would be better to let user to define any size and let sendmsg() or struct sock_extended_err to inform if payload does not fit to package.

**Comment by kerolasa** [comment]
Ping is changed not to be too clever what is, can, or could be allowed package size, see commit a647e2cdbd9772bdaed61bf053b6c92c323b6061.

While working with this I did notice errors vary by telling mtu exceeded or sendmsg() cannot handle packet of that size. When pinging IPv4 / IPv6 addresses size limits appeared to vary somewhat, and localhost appears to allow rather big packages. Now when artificial limits are gone it's interesting to see how os, network, and remote systems are behaving with various size variations.
