### ISSUE TITLE
iputils-arping: -w (deadline) broken

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#211]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935946

arping -w doesn't work anymore. Instead of exiting when the deadline is
reached, it just hangs.

```
# arping -w 2 -f -I eno1 172.17.49.5
ARPING 172.17.49.5 from 172.16.72.51 eno1
<hangs until ^C>
Sent 172 probes (172 broadcast(s))
Received 0 response(s)

It worked fine with 3:20180629-2:
# arping -w 2 -f -I eno1 172.17.49.5
ARPING 172.17.49.5 from 172.16.72.51 eno1
Sent 3 probes (3 broadcast(s))
Received 0 response(s)
```

git bisect suggests that this behavior was introduced with 67e070d08dcbec990e1178360f82b3e2ca4f6d5f

**Comment by kerolasa** [comment]
Bisected to 67e070d08dcbec990e1178360f82b3e2ca4f6d5f, that is my commit. I'll try get this sorted sometime soon.

**Comment by kerolasa** [comment]
It would be nice to hear if f6e2622549770eca8e55d1817de40e650a3c9aab fixes to you, and even better if that does not cause more problems.

**Comment by kerolasa** [comment]
Thank you for bug report and testing @nmeyerhans. Lets hope I did not add new regression(s). Meanwhile I consider this case closed.
