### ISSUE TITLE
Linking <skbuff.net/iputils> here

### ISSUE THREAD

**Issue by es20490446e** [iputils/iputils#221]
Perhaps puting a notice on the [old website](http://www.skbuff.net/iputils/) that the new version is the one here?

And perhaps also [on SourceForge](https://sourceforge.net/p/iputils/code/ci/HEAD/tree/).

**Comment by okias** [comment]
Sadly, previous maintainer not responded to my emails, mailing list post etc., so we don't have access to old website and repository.

**Comment by es20490446e** [comment]
Whoops! 🤯

**Comment by pevik** [comment]
BTW I wonder what happend to Yoshifuji Hideaki. He stopped also to contribute to Linux kernel.

**Comment by es20490446e** [comment]
Well, he's 45. So probably he got a serious job 🤣
