### ISSUE TITLE
ping: -W behaviour with trailing "garbage" changed

### ISSUE THREAD

**Issue by lmb** [iputils/iputils#236]
As of https://github.com/iputils/iputils/commit/918e824dc13a39e4d68fcd82fd2d248c9fba6bbd the following returns an error:

```
$ ping -W 5s 127.0.0.1
ping: bad linger time: 5s
```

Old ping silently ignored the "s" suffix. Since the units are seconds anyways the script that did this worked fine. 

Arguably the current behaviour is better, since `ping -W 1m` looks like it would linger for a minute, when the maximum is really 1 second.

Maybe the fix is to allow specifying non-second units?

cc @kerolasa

**Comment by kerolasa** [comment]
I see few options.

1. Current behaviour is declared correct. The old one was undocumented fluke.
2. Old behaviour was strange but correct, and needs to work again.
    * Though, perhaps this time as documented behaviour.
3. Old behaviour should warn but work.
    * Maybe including deprecation note in the warning with long enough period, such as: defining trash is allowed but will stop working in first release after 2022-02-02.
4. Add support to time units and their short hands
    * Such as: s = seconds, m = minutes, h  = hours, d = days.
    * Notice that this is still ABI breakage compared to olden times because trash was accepted, and if only trash was supplied value meant zero.

@pevik / @okias / @pavlix what do you think? I am leaning toward option 3.

**Comment by pevik** [comment]
@nmeyerhans any opinion on it?

I would be for 1 or 3, but without specifying when it will be removed (it will be removed in the future).
And I guess there is also 5) Current behaviour is declared correct. But improve error message (print `bad linger time, use integer`). I wonder why people invented to put `s`, when it wasn't needed.
Ad 4.: is there any benefit to have something more than seconds? I don't thing so.

BTW FreeBSD ping uses milliseconds
https://www.freebsd.org/cgi/man.cgi?query=ping&apropos=0&sektion=8&manpath=FreeBSD+12.1-RELEASE&arch=default&format=html

**Comment by lmb** [comment]
@pevik I just used '-W 5s' since that made sense to me, and ping didn't complain.

Supporting units would let you side-step the FreeBSD incompatibility a little bit as well. `-W 5s` is pretty clear in that regard.

**Comment by kerolasa** [comment]
I merged commit 562e0d570d93cfcfdebab1215a2f04efa64a24f8 that is option 3. This change will be reverted in year or two from now.

**Comment by pevik** [comment]
@kerolasa Thanks for fixing it.
