### ISSUE TITLE
ping icmpv6 nodeinfo queries use non-random nonce

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#239]
While working on openwrt/packages#10633, I observed some unexpected behavior regarding nonce generation for ICMPv6 node info queries in some scenarios.

If ping is built with `USE_CRYPTO=kernel`, but the kernel does not have support for the md5 algorithm, then we never actually write anything to the buffer allocated for random data, and instead leave it initialized to all zero values. When this happens, the nonce ends up being essentially equivalent to the sequence number, when it should be random. There's no indication given to the user that this has occurred.

Practically speaking, I'm not sure that the risk of spoofed nodeinfo replies is all that great, but [the spec](https://tools.ietf.org/html/rfc4620) does require the nonce to be unpredictable enough to protect against them. I think ping should at the very least print a warning when it's unable to generate a random nonce, and it may be reasonable to abort altogether.

**Comment by kerolasa** [comment]
Great catch @nmeyerhans. I wrote change that will cause execution to stop if / when kernel AF_ALG socket does not work as expected.

But I'm not sure if that is great. Maybe we should copy md5 source code to iputils and get rid of dependency to library or kernel api altogether.  That is what util-linux does, https://github.com/karelzak/util-linux/blob/master/lib/md5.c

**Comment by nmeyerhans** [comment]
When building for a general purpose Linux distro, the openssl dependency isn't a big deal, since it's probably installed already. On the other hand, we have such a limited and specific need for any crypto code, that importing just the md5 routines might make sense. I'll be curious to see what this does to the size of the ping binary.

**Comment by pevik** [comment]
Yep, I wouldn't mind to import md5 code either, if binary size does not dramatically increase.

**Comment by kerolasa** [comment]
Lets measure the size change. After compiling & stripping binary I saw 4096 bytes size difference from 77352 to 81448 bytes. If acceptable earlier 'common: fail execution when USE_CRYPTO=kernel does' change will be removed before merge.

https://github.com/kerolasa/iputils/commit/7cf7bb7a1dc9fe3e55309f2e45c04c2c877367a2

**Comment by pevik** [comment]
Size looks ok for me (~5% increase).
Change not related to this commit: you changed `travis/ubuntu.sh` to be copy of `travis/debian.sh` and `travis/centos.sh` copy of `travis/fedora.sh`. They both are supposed to be a symlinks.

**Comment by kerolasa** [comment]
Oops. My bad with symlinks, thank you for catching that @pevik. Commit 214ed83afcce7f08406b17144040891eb40113cf is hopefully final version. If I don't hear anything I will merge that as-is sometime weekend.

**Comment by kerolasa** [comment]
https://github.com/iputils/iputils/pull/241 is merged that addresses this issue.
