### ISSUE TITLE
libcap 2.29 breaks build of iputils

### ISSUE THREAD

**Issue by fjaell** [iputils/iputils#246]
with libcap 2.29 installed I get the following:

[24/28] Compiling C object 'ninfod/0cb6efe@@ninfod@exe/ninfod.c.o'.
FAILED: ninfod/0cb6efe@@ninfod@exe/ninfod.c.o 

cc -Ininfod/0cb6efe@@ninfod@exe -Ininfod -I../ninfod -Ininfod/.. -I../ninfod/.. -I. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -g -include config.h -include git-version.h '-DGETTEXT_PACKAGE="iputils"' -O2 -march=x86-64 -pthread -MD -MQ 'ninfod/0cb6efe@@ninfod@exe/ninfod.c.o' -MF 'ninfod/0cb6efe@@ninfod@exe/ninfod.c.o.d' -o 'ninfod/0cb6efe@@ninfod@exe/ninfod.c.o' -c ../ninfod/ninfod.c

../ninfod/ninfod.c:457:26: error: 'cap_setuid' redeclared as different kind of symbol
 static const cap_value_t cap_setuid =  CAP_SETUID;
                          ^~~~~~~~~~
In file included from ../ninfod/ninfod.c:117:
/usr/include/sys/capability.h:138:12: note: previous declaration of 'cap_setuid' was here
 extern int cap_setuid(uid_t uid);
            ^~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by kerolasa** [comment]
I changed the problematic variable name in 18f9a84e0e702841d6cc4d5f593de4fbd1348e83 and I am pretty sure this will fix the issue. It would be nice to hear if that worked for you @fjaell.

**Comment by fjaell** [comment]
Yep, that works. Thanks for the quick fix!
