### ISSUE TITLE
arping's exit code for unsolicited ARP mode is non-zero

### ISSUE THREAD

**Issue by jknoos** [iputils/iputils#247]
**Version:**
```shell
$ arping -V 
arping from iputils s20190709
```

**Steps to reproduce:**
```shell
$ arping -I $dev $ip -c1 -U; echo $?
```

**Expected result:**
Since the man page states -U enables `Unsolicited ARP mode to update neighbours' ARP caches. No replies are expected`, an exit code of 0 is expected even when there are no replies (in the absence of other internal errors).

**Actual result:**
Exit code is non-zero:

```shell
$ arping -I $dev $ip -c1 -U; echo $?
ARPING ... from ... ...
Sent 1 probes (1 broadcast(s))
Received 0 response(s)
1 
```

**Comment by kerolasa** [comment]
I just pushed commit to my repository that probably fixes the issue. Reviews are welcome. I'll have another look of this during weekend, and if the change still looks ok and does what I think should be correct merge is likely to happen.

**Comment by kerolasa** [comment]
I merged the commit that should fix the issue. Please inform if that does not help, or has some regression I did not realise.

**Comment by modyngs** [comment]
@kerolasa @jknoos @lac-0073 
Hi,

I have tried arping using apt install but the version was too old (2019) and it didn't work properly on ubuntu 20.04!
So i wanted to know how can i build it from source?


P.S. I could'nt find the way how to build iputils-arping!

Thanks
Best regards

**Comment by pevik** [comment]
@modyngs `./configure && meson build`
Build dependencies are listed in https://github.com/iputils/iputils/blob/master/ci/debian.sh, it's just enough one compiler (`gcc` _or_ `clang`).

**Comment by pevik** [comment]
@modyngs FYI I put some installation info in https://github.com/iputils/iputils#installation

**Comment by modyngs** [comment]
@pevik
Thanks for the reply

i was wondering if there is any prerequisite ( dependencies ) before taking into the installation process?

Thanks 
Best regards

**Comment by modyngs** [comment]
@pevik 
Thanks for the replay

are the dependencies common through all the releases?
I'm using focal but the dependencies are for xenial
