### ISSUE TITLE
ping -6 fails for hosts with link local addresses

### ISSUE THREAD

**Issue by RPigott** [iputils/iputils#252]
Sorry if this is a duplicate, but I didn't see anything like it. I did see #100, but I'm not sure under what circumstance it is intended to allow scope-less link local ping to work.

I see this behavior in the `ping` from the Arch repos and in a build from master.

The issue I see is the following:
```
$ ping -n -c1 -6 _gateway
PING _gateway(fe80::42b0:76ff:feaf:1578) 56 data bytes
ping: sendmsg: Invalid argument
[...]
```

I tracked down why this happens [here](https://bbs.archlinux.org/viewtopic.php?pid=1884995). I concluded that this failure is caused by a missing scope ID after name resolution and is a limitation of getaddrinfo if we want to only query for only the AAAA record. However, it's worth noting that the dual-stack version works fine, and even selects ipv6 over ipv4:

```
$ ping -n -c1 _gateway
PING _gateway(fe80::42b0:76ff:feaf:1578%wlp2s0) 56 data bytes
64 bytes from fe80::42b0:76ff:feaf:1578%wlp2s0: icmp_seq=1 ttl=64 time=6.28 ms
[...]
```

As I described in the post, this is because it is able to use nss_gethostbyname4_r over nss_gethostbyname3_r, so nss-resolve is able to indicate the scope ID to the caller.

So this definitely feels like a bug to me, and I'd consider writing a patch, but I'm not actually certain this is actionable. I have the following questions:

0. Is this really a limitation of getaddrinfo, or is there something more nss-resolve could be doing to indicate the scope ID to the caller with the provided addrinfo hints?

If it is a limitation of getaddrinfo,

1. Is there an alternative method that could be used to discover the correct scope ID? I cannot think of one.
2. Would ping consider using dual-stack name resolution in getaddrinfo even for ping6 to fix this case? This would cause an irrelevant A record request which sucks, but otherwise sounds OK.
3. Would ping consider using an alternative name resolution interface over getaddrinfo to fix this case? I think probably not. Even if it was agreeable and worth the effort it would cause an inconsistency with applications that resolve with the NSS which is probably undesirable.

**Comment by ValZapod** [comment]
You understand you need to use %iface, right?😝

**Comment by RPigott** [comment]
@ValZapod Yes. That's called a scope ID. Please read my description again and the linked post.

The %iface syntax is for numeric addresses only, otherwise the scope ID should be determined by name resolution. It _is_ determined correctly by getaddrinfo in the dual stack case. This bug is about the ping6 case.

**Comment by ValZapod** [comment]
> want to only query for only the AAAA record

BTW, you look like a clever guy, do you know how to made AAAA before A as it should by standard Eye Balls? I do not use systemd resolver or anything. Just resolv.conf

**Comment by RPigott** [comment]
@ValZapod Are you referring to [Happy Eyeballs](https://tools.ietf.org/html/rfc8305#section-3)? I don't think this is possible within the libc resolver.

Either way, it's unrelated to this bug report. I suppose you should open a feature request for ping to implement it, if you want.

**Comment by kerolasa** [comment]
Fix by @RPigott  was merged, so I think this issue can be closed. Please inform if I got that wrong, and thanks again Ronan.
