### ISSUE TITLE
arping -w  xx does not take effect

### ISSUE THREAD

**Issue by lac-0073** [iputils/iputils#259]
1. **When the peer is reachable**
**Version: 20180629，-w take effect**
[root@localhost ~]# arping 9.82.246.187  -w 5 -I eth0
ARPING 9.82.246.187 from 9.82.227.144 eth0
Unicast reply from 9.82.246.187 [52:54:00:FE:A7:59]  2.012ms
Unicast reply from 9.82.246.187 [52:54:00:FE:A7:59]  2.949ms
Unicast reply from 9.82.246.187 [52:54:00:FE:A7:59]  1.109ms
Unicast reply from 9.82.246.187 [52:54:00:FE:A7:59]  2.635ms
Unicast reply from 9.82.246.187 [52:54:00:FE:A7:59]  3.138ms
Unicast reply from 9.82.246.187 [52:54:00:FE:A7:59]  3.255ms
Sent 6 probes (1 broadcast(s))
Received 6 response(s)

      **Version: 20190709，-w don't take effect, arping -w would not stop unless ctrl+c**
      [root@localhost ~]# arping 9.82.227.144 -w **5**
      ARPING 9.82.227.144 from 9.82.246.187 enp3s0
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  4.755ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  3.331ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  3.711ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  3.944ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  1.762ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  1.288ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  5.002ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  3.830ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  1.517ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  4.270ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  1.551ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  3.925ms
      Unicast reply from 9.82.227.144 [52:54:00:D9:EC:F7]  3.916ms
     ^CSent **13** probes (1 broadcast(s))
     Received 13 response(s)

2. **When the peer is unreachable**
**Version: 20180629，-w take effect**
[root@localhost ~]# arping 9.82.246.199  -w **5** -I eth0
ARPING 9.82.246.199 from 9.82.227.144 eth0
Sent 6 probes (6 broadcast(s))
Received 0 response(s)

      **Version: 20190709，-w don't take effect, arping -w would not stop unless ctrl+c**
      [root@localhost ~]# arping 9.82.227.199 -w **5**
      ARPING 9.82.227.199 from 9.82.246.187 enp3s0
      **^C**Sent **16** probes (16 broadcast(s))
      Received 0 response(s)

**Comment by kerolasa** [comment]
Breakage originates to 1df5350bdc952b14901fde356b17b78c2bcd4cff

**Comment by kerolasa** [comment]
I think https://github.com/iputils/iputils/pull/261 will address all the issues. It would be nice to hear feedback if that works for you @lac-0073 before I merge.

**Comment by lac-0073** [comment]
yes ,I confirmed it was resolved on  [#261](https://github.com/iputils/iputils/pull/261/commits/f7d6c011dfa0e17ccf8f6bc53e127ba06fa2273a) ， you are awesome.

**Comment by kerolasa** [comment]
Thank you for confirmation, fixing commit is e594ca52afde89746b7d79c875fe9d6aea1850ac.

**Comment by nuno-silva** [comment]
If anyone needs to patch this on release 20190709, the commits to fix it are (in order):
18f14be80466ddc8fb17a400be82764a779c8dcd
1df5350bdc952b14901fde356b17b78c2bcd4cff
ec821e572a640bd79aecc3922cb9001f4b6b26f2
e594ca52afde89746b7d79c875fe9d6aea1850ac

More info: https://bugs.gentoo.org/730154
