### ISSUE TITLE
tracepath doesnt show ip of host in output anymore post 20071127 version

### ISSUE THREAD

**Issue by sravan1** [iputils/iputils#26]
Is this expected ? or a problem

**Comment by sravan1** [comment]
tracepath -n <nameserver> fails to list ip of hostname

**Comment by okias** [comment]
Can you give us example of working and broken version?

**Comment by sravan1** [comment]
Say ip of host machine is 10.21.1.1
and name server is 9.0.10.1

With iputils-20071127-17
[sra@xxxxx ~]$ tracepath -n 9.0.10.1
 1:  10.21.1.1       0.072ms pmtu 1500
 1:  9.13.189.170       0.549ms 
 1:  9.13.189.170       0.322ms 
 2:  9.38.3.133         0.515ms 
 3:  9.53.157.167       0.520ms 
 4:  9.53.157.13        1.080ms 
 5:  9.41.12.153        1.302ms 
 6:  9.41.12.14         1.016ms 
 7:  9.41.11.14         1.274ms 
 8:  9.41.11.5         14.228ms 

Where as with iputils-20121221-6 and the latest tracepath from git:
[bash ~]$ tracepath -n 9.0.10.1
 1?: [LOCALHOST]                                         pmtu 1500
 1:  9.13.189.170                                           0.633ms 
 1:  9.13.189.170                                           0.407ms 
 2:  9.38.3.133                                             0.613ms 
 3:  9.53.157.167                                           0.621ms 
 4:  9.53.157.13                                            1.174ms 
 5:  9.41.12.145                                            1.204ms 
 6:  9.41.12.2                                              1.154ms 
 7:  9.41.11.14                                             1.234ms 
 8:  9.41.11.5                                             20.386ms 

In the older tracepath output starts from ip of hostname where as in the latest tracepath LOCALHOST is listed instead.

Also if I look at the man pages:http://manpages.ubuntu.com/manpages/lucid/man8/tracepath.8.html and http://linux.die.net/man/8/tracepath
LOCALHOST display seem to be correct.
But I just wanted a confirmation from you guys.

Note: /etc/hosts is properly set with ip and hostname of the machine.

Thanks a lot in advance David!

**Comment by pavlix** [comment]
Were both tested on the same kernel? This difference should be investigated and IMO could be explained using strace.

**Comment by okias** [comment]
I didn't found since initial import in 2006 (git log) any change. It seems to be exactly same.

Are you sure it was ping from iputils suite? Anyway, this could be good feature to have..

**Comment by pevik** [comment]
@sravan1 can we close the ticket? Is it really problem of `tracepath` from iputils project?

**Comment by 6eh01der** [comment]
@okias @pevik I builded 20070202 and 20071127 versions and 20210202 from iputils github repo and results is the same - `1?: [LOCALHOST]     pmtu 1500` as first output entry (hop) so it seems that problem is not in iputils code. Also it is not problem at all.
Quote from man:"...or word [LOCALHOST], if the probe was not sent to the network"
