### ISSUE TITLE
seeing `nagios CRITICAL - Could not interpret output from ping command` on nagios running on debian

### ISSUE THREAD

**Issue by danbf** [iputils/iputils#266]
seeing `nagios CRITICAL - Could not interpret output from ping command` on nagios running on debian.  fixed by adding `RUN chmod u+s /bin/ping` to the Dockerfile.  this was working in the past and suddenly broke.

nagios runs as a non-root user.

**Comment by danbf** [comment]
failing vs non failing installs show the same version of `iputils-ping`

```
was:
dpkg --list | grep iputils-ping
ii  iputils-ping                       3:20180629-2+deb10u1        amd64        Tools to test the reachability of network hosts

now:
dpkg --list | grep iputils-ping
ii  iputils-ping                       3:20180629-2+deb10u1        amd64        Tools to test the reachability of network hosts

```

**Comment by danbf** [comment]
ok, so i think this is a packaging issue.  

what i think happened before is that somehow we didn’t build this often enough and that the installed iputils-ping matched what was going to get installed by the apt-get install so it never kicked off the install.  so we’ve just been lucky here so far.

i think so i think this might be a new edge case for in the container world, where in a container `setcap cap_net_raw+ep /bin/ping` is not telling the truth about if using setcap will work or not.

root@5fa2cf3589e1:/# setcap cap_net_raw+ep /bin/ping
root@5fa2cf3589e1:/# echo $?
0

and so this fails https://salsa.debian.org/debian/iputils/-/blob/ffe8f119c93a37f2d7e1e9f9523b794893641966/debian/iputils-ping.postinst#L11

**Comment by pevik** [comment]
@MofX could you have a look on it?

@danbf It really looks as a packaging issue, e.g. it should be reported to [Debian bug tracker](https://www.debian.org/Bugs/). But @MofX is Debian packager, so we might solve it here. Could you at least wrote some details (which Debian version you use, which packages you use etc. Not everybody is using Nagios and/or Docker, straightforward reproducer speedup fixing the issue).

**Comment by danbf** [comment]
i agree, and i reported it there once i dived deeper. 

root@5fa2cf3589e1:/# setcap cap_net_raw+ep /bin/ping
root@5fa2cf3589e1:/# echo $?
0

root@5fa2cf3589e1:/# uname -a
Linux 5fa2cf3589e1 5.4.20-12.75.amzn2.x86_64 #1 SMP Thu Feb 27 20:41:59 UTC 2020 x86_64 GNU/Linux
root@5fa2cf3589e1:/# dpkg -s iputils-ping | grep Vers
Version: 3:20180629-2
root@5fa2cf3589e1:/# ls -l /bin/ping
-rwsr-xr-x 1 root root 65272 Aug  3  2018 /bin/ping
root@5fa2cf3589e1:/# /sbin/getcap /bin/ping
root@5fa2cf3589e1:/# ping -w3 -c3 debian.org
PING debian.org (130.89.148.77) 56(84) bytes of data.
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=1 ttl=32 time=92.8 ms
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=2 ttl=32 time=94.0 ms
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=3 ttl=32 time=93.7 ms

**Comment by danbf** [comment]
been talking to @nmeyerhans i think on it.

**Comment by danbf** [comment]
i scratched my itch by explicitly adding a `RUN chmod u+s /bin/ping` in my Dockerfile after the `apt-get install iputils-ping` and while i admit my use case is rare it's interesting that `setcap cap_net_raw+ep /bin/ping` doesn't throw an error, but still doesn't function in containers not running under root.

**Comment by nmeyerhans** [comment]
@danbf, It's probably not the case that `setcap` is lying about its ability to set the file capabilities. More likely the problem is that the capabilities are getting lost somewhere in the various filesystem operations that occur between creating and running the container. Neither the packaging system, nor the package itself, can anticipate whatever filesystem transformations may happen between the time that you install the package in a container image and the time that the container image may be unpacked for execution.

Assuming you're running Docker, what happens if you do this:

    docker run -it --rm --net=host debian:buster sh -c "dpkg --purge iputils-ping && apt-get update && apt-get -y install iputils-ping && /sbin/runuser -u nobody -- ping -w3 -c3 debian.org"                                                                                             

I expect that this will work.  The package installation process will print a message containing the string `Setcap failed` if it falls back to using setuid.  If it doesn't print that message, then capabilities are used.

**Comment by danbf** [comment]
we first noticed this issue on an AWS ECS Fargate deployed nagios container.  it think the issue shows up because of using user namespace in docker there.

not sure if something else could be used instead of just https://salsa.debian.org/debian/iputils/-/blob/ffe8f119c93a37f2d7e1e9f9523b794893641966/debian/iputils-ping.postinst#L12 .  it doesn't seem like a `/sbin/getcap` or `setcap -v` will help here as i see this on my container:

```
setcap -v cap_net_raw+ep /bin/ping
/bin/ping: OK
```

any harm is just always using the setuid as well as the setcap?

locally this is what i got on my mac running docker

```
docker run -it --rm --net=host debian:buster sh -c "dpkg --purge iputils-ping && apt-get update && apt-get -y install iputils-ping && /sbin/runuser -u nobody -- ping -w3 -c3 debian.org"
Unable to find image 'debian:buster' locally
buster: Pulling from library/debian
be2ea06d55bb: Pull complete
Digest: sha256:5e31e9c8ddccb855e5ce31b659c89075427c9ca7df94002b7107834dc9ee3f8b
Status: Downloaded newer image for debian:buster
(Reading database ... 6677 files and directories currently installed.)
Removing iputils-ping (3:20180629-2+deb10u1) ...
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [198 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7905 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7380 B]
Fetched 8347 kB in 3s (2805 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  iputils-ping
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 43.3 kB of archives.
After this operation, 106 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 iputils-ping amd64 3:20180629-2+deb10u1 [43.3 kB]
Fetched 43.3 kB in 0s (362 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package iputils-ping.
(Reading database ... 6666 files and directories currently installed.)
Preparing to unpack .../iputils-ping_3%3a20180629-2+deb10u1_amd64.deb ...
Unpacking iputils-ping (3:20180629-2+deb10u1) ...
Setting up iputils-ping (3:20180629-2+deb10u1) ...
PING debian.org (149.20.4.15) 56(84) bytes of data.
64 bytes from mirror-isc3.debian.org (149.20.4.15): icmp_seq=1 ttl=38 time=88.2 ms
64 bytes from mirror-isc3.debian.org (149.20.4.15): icmp_seq=2 ttl=38 time=93.1 ms
64 bytes from mirror-isc3.debian.org (149.20.4.15): icmp_seq=3 ttl=38 time=91.9 ms

--- debian.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 6ms
rtt min/avg/max/mdev = 88.193/91.073/93.140/2.114 ms
```

**Comment by nmeyerhans** [comment]
> any harm is just always using the setuid as well as the setcap?

The whole point of using capabilities is to get rid of a setuid binary on the system. So using both would completely defeat the purpose.

You'll note that the official Debian Docker images set the setuid bit on ping.  Presumably that's because, one way or another, they build on a filesystem that doesn't support capabilities, because I don't see any place in [their code](https://github.com/debuerreotype/debuerreotype) whey're they're explicitly setting the mode.

In any case, you should either run your container builds on some filesystem (or kernel) that has file capabilities disabled, or you should explicitly `chmod +s` the ping binary in your image build process.

**Comment by danbf** [comment]
👍 and thanks for your time on this.  just a heads up that this weird edge case might come up.  especially among people running  monitor in a container like we do.

**Comment by MofX** [comment]
>But @MofX is Debian packager, so we might solve it here. Could you at least wrote some details (which Debian version you use, which packages you use etc. Not everybody is using Nagios and/or Docker, straightforward reproducer speedup fixing the issue).

@pevik I guess you got something wrong here :) I am not a maintainer for debian.

**Comment by pevik** [comment]
> @pevik I guess you got something wrong here :) I am not a maintainer for debian.

I'm sorry, I meant nmeyerhans :)
