### ISSUE TITLE
Loopback Ping6 traffic failed when using interface name in -I option

### ISSUE THREAD

**Issue by itayave** [iputils/iputils#279]
When executing loopback traffic via ping6 and passing the interface name to "-I" option,
the traffic failed.
If I'm passing the IPv6 address instead of the interface name, the traffic passed.

I'm using Fedora32 with the default iputils - iputils-20190515-5.fc32.x86_64

The same flow passed on Fedora27 with iputils-20161105-7.fc27.x86_64

Reproduction steps:

`ping6 -I eth2 ::11:235:255:5` - Failed
`ping6 -I ::11:235:255:5 ::11:235:255:5` - Passed

**Comment by kerolasa** [comment]
Could you compile the latest version and check if it works.

**Comment by hugleo** [comment]
Doesn't work, and is not only ipv6, same problem for ipv4.

wireshark packets are being sent and received but:

ping 192.168.0.120 -I enp3s0
PING 192.168.0.120 (192.168.0.120) from 192.168.0.120 enp3s0: 56(84) bytes of data.
no answer
However for ipv4 it works if i run as root user.


ping -6 fe80::e23f:59ff:feb5:e522 -I enp3s0
PING fe80::e23f:59ff:feb5:e522(fe80::e23f:59ff:feb5:e522) from :: enp3s0: 56 data bytes
no response even running as root user.


I've found something that might be related to the problem.

for ipv4:
source: ping.c
line: 682

`				rc = setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE,
						rts->device, strlen(rts->device) + 1);`
for ipv6:
file: ping6_common.c
line: 173

`			if (setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, rts->device, strlen(rts->device) + 1) == -1 ||
			    setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, rts->device, strlen(rts->device) + 1) == -1) {
				error(2, errno, "setsockopt(SO_BINDTODEVICE) %s", rts->device);
			}`

If I comment on these lines of code the loopback interface binding ping works perfectly!

`				//rc = setsockopt(fd, SOL_SOCKET, SO_BINDTODEVICE,
						rts->device, strlen(rts->device) + 1);`

`			/*if (setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, rts->device, strlen(rts->device) + 1) == -1 ||
			    setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, rts->device, strlen(rts->device) + 1) == -1) {
				error(2, errno, "setsockopt(SO_BINDTODEVICE) %s", rts->device);
			}*/`

**Comment by eaglegai** [comment]
@kerolasa @hugleo @itayave 
in iputils-20221126
ping -6 selfIPV6address -I eth0
it has response

**Comment by hugleo** [comment]
Yes,

Is working now for the last versions.
