### ISSUE TITLE
Build fails if gettext is disabled

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#284]
With build environment configured as follows:

    meson build \
      -Dprefix=/usr \
      -DBUILD_RARPD=false \
      -DBUILD_RDISC=false \
      -DBUILD_TFTPD=false \
      -DBUILD_NINFOD=false \
      -DBUILD_HTML_MANS=false \
      -DBUILD_TRACEROUTE6=true \
      -DNO_SETCAP_OR_SUID=true \
      -DUSE_CRYPTO=gcrypt \
      -DUSE_GETTEXT=false

The build fails with:

    /src/iputils:$ meson compile -C build --verbose
    Found runner: /usr/bin/ninja
    ninja: Entering directory `build'
    ...
    [10/22] cc -Iping/ping.p -Iping -I../ping -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -g -include config.h -include git-version.h -MD -MQ ping/ping.p/ping.c.o -MF ping/ping.p/ping.c.o.d -o ping/ping.p/ping.c.o -c ../ping/ping.c
    FAILED: ping/ping.p/ping.c.o 
    cc -Iping/ping.p -Iping -I../ping -I. -I.. -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -g -include config.h -include git-version.h -MD -MQ ping/ping.p/ping.c.o -MF ping/ping.p/ping.c.o.d -o ping/ping.p/ping.c.o -c ../ping/ping.c
    ../ping/ping.c: In function ‘ping_strtod’:
    ../ping/ping.c:181:2: warning: implicit declaration of function ‘setlocale’ [-Wimplicit-function-declaration]
    181 |  setlocale(LC_ALL, "C");
    |  ^~~~~~~~~
    ../ping/ping.c:181:12: error: ‘LC_ALL’ undeclared (first use in this function); did you mean ‘P_ALL’?
    181 |  setlocale(LC_ALL, "C");
    |            ^~~~~~
    |            P_ALL
    ../ping/ping.c:181:12: note: each undeclared identifier is reported only once for each function it appears in

Maybe missing some preprocessor tests?

The above was observed as of 5393c052ac7493a25f0de28cd86c0b320836ae07

**Comment by pevik** [comment]
@nmeyerhans Thank you for testing! Could you please verify my fix https://github.com/iputils/iputils/pull/287?
I'm going also to add check for travis build (some of them fails without gettext, but not all, probably due installed pkg):
https://travis-ci.org/github/pevik/iputils/jobs/715121860

**Comment by pevik** [comment]
OK, your fix will be also needed.

**Comment by pevik** [comment]
@nmeyerhans should be now fixed with your fix and also covered by travis build + more strict travis.

Verified that it does not fail for any distro: https://travis-ci.org/github/pevik/iputils/builds/715142082
Previously failed for some distros: https://travis-ci.org/github/pevik/iputils/builds/715141978

Thanks for your patch, feel free to reopen if problem persist.

**Comment by pevik** [comment]
OK, I didn't remember that this was affected by d865d4c468965bbff1b9d6b912eee44ade52967d from https://github.com/iputils/iputils/pull/265. 

Now with NLS (the default) using locale decimal delimiter (`,`) triggers warning (as expected):

```
$ LC_ALL=cs_CZ.UTF-8 ./builddir/ping/ping ::1 -c1 -i 2,2 -W 3.3
./builddir/ping/ping: option argument contains garbage: ,2
./builddir/ping/ping: this will become fatal error in future
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.026 ms
```

But without NLS (non-default `-DUSE_GETTEXT=false`) using C locale delimiter (`.`) triggers warning (which is wrong):
```
$ LC_ALL=cs_CZ.UTF-8 ./builddir/ping/ping ::1 -c1 -i 2,2 -W 3.3
/builddir/ping/ping: option argument contains garbage: .3
./builddir/ping/ping: this will become fatal error in future
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.018 ms
```
It looks like my original solution https://github.com/iputils/iputils/pull/287 was somehow close to the correct solution, but we need to include `<locale.h>` always, not via `<iputils_common.h>` as here depends on NLS or gettext related variables (user choice). IMHO locale related code deserve refactoring.

**Comment by pevik** [comment]
WIP: https://github.com/iputils/iputils/pull/288. I also need to fix man page as changed behavior wasn't documented.
@MofX FYI.

**Comment by pevik** [comment]
Continue tracking in #290.
