### ISSUE TITLE
Structure of .po and .mo files makes packaging difficult

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#285]
It's fairly common for multiple binary packages to be build from the iputils source repository. Debian, Ubuntu, and OpenWRT all build packages like "iputils-ping", "iputils-tracepath", etc. I believe Fedora and CentOS/RHEL do as well, but have not confirmed this.

The current implementation of gettext places all localization strings in a single .mo file per locale, e.g. `/usr/share/locale/uk/LC_MESSAGES/iputils.mo`. In order to accommodate this when splitting the package into multiple binary packages, we either need to distribute this file in a shared "iputils-common" package that is installed as a dependency of all the actual binary packages, or we need to duplicate contents of the .mo files for each program (e.g. the "ping" package contains a "ping.mo" file containing the full contents of the iputils.mo file).  Both cases waste disk space by installing translation data for programs that are not necessarily installed on the system.

Distribution would be more efficient if the .mo files could be generated per program, as in "ping.mo", "tracepath.mo", etc, such that they only contain localized strings for the specific program.

**Comment by pevik** [comment]
I'm ok with this idea. @jsynacek will it be ok to do it before release? @yurchor If I manually split all *.po files will weblate handle it ok?

BTW how other distro split the package:
* openSUSE only rarpd (https://build.opensuse.org/package/view_file/network:utilities/iputils/iputils.spec?expand=1)
* Fedora only ninfod (https://src.fedoraproject.org/rpms/iputils/blob/HEAD/f/iputils.spec)

You can also check by searching on https://pkgs.org/ that Debian/Ubuntu way (adopted by OpenWRT) to package binaries separately (single image in iputils-foo package) is not adopted by anything else.

**Comment by yurchor** [comment]
To be honest, I'm not a fun of this idea. Util-linux, coreutils, extfsprogs, gnupg are the similar collections of utils. They all have just one .po file. Binutils is huge so it is split. Both approaches can be used. I'm in the country now with very limited internet connection. So I cannot add more good arguments until the next Monday.

**Comment by pevik** [comment]
@jsynacek any opinion on this?

**Comment by yurchor** [comment]
Ok. I have tested extraction for the separate project dirs and have no objections if the split will benefit the project on embeddables.

Please tell me if you want to split POT catalogs as well so I can rearrange Weblate catalogs accordingly.

**Comment by pevik** [comment]
@nmeyerhans could you please prepare PR which split the po files and notify @yurchor?

**Comment by pevik** [comment]
@nmeyerhans are you still interested in this? Would you have time to split files? Now, after the release it'd be good time.

**Comment by nmeyerhans** [comment]
It's still something I'd like to see. However, it's not clear when I'll be able to prioritize work on it. Additionally, since we're eliminating many of the obsolete tools, the big collection of l10n data may not be quite as much of a concern (though I haven't looked closely).

If nobody else is interested in working on this, then I suppose we can close it.

**Comment by pevik** [comment]
@nmeyerhans FYI tools removed in https://github.com/iputils/iputils/pull/388 don't have any translations https://github.com/iputils/iputils/pull/388/files.
Take your time, you know how long it takes me to handle issues / PR. If you work on it, please reopen this ticket and note that.
