### ISSUE TITLE
trailing dot required

### ISSUE THREAD

**Issue by infragilis** [iputils/iputils#29]
discovered this issue with rhel 6.6  stock, no update, or with update (no other in our env has this issue / rhel 7/ubuntu 14.4) then got the latest version of iputils from here, compiled and see the exact same behavior. If i place the somehost in /etc/hosts, all works fine

[root@ping-rh iputils]# ./ping -I eth0 somehost   (local name, only avail in dnsmasq)
ping: somehost: Name or service not known
[root@ping-rh iputils]# ./ping -I eth0 somehost.
PING somehost (10.155.203.21) from 10.155.203.64 eth0: 56(84) bytes of data.
64 bytes from somehost (10.155.203.21): icmp_seq=1 ttl=64 time=0.571 ms
64 bytes from somehost (10.155.203.21): icmp_seq=2 ttl=64 time=0.585 ms
^C

running against dnsmasq, with nsswitch on the host set to files/dns all the usual suspects.
this might not be the right spot to ask, but i don't see any other place that knows as much about ping  :)

**Comment by pavlix** [comment]
Have you tried with `getent ahosts` instead of `ping`? I don't think `ping` itself enforces any policy on single-segment FQDN names.

**Comment by pavlix** [comment]
@okias I suggest closing this bug due to lack of information. As far as I know ping uses `getaddrinfo()` and doesn't do any specific preprocessing.

**Comment by infragilis** [comment]
yes, please close .. found out that if you add fqdn to /etc/sysconfig/network on centos/RH in stead of alias, all this BS happens .. DO NOT USE fqdn in rhel/centos /etc/sysconfig/network  :)

Thanks guys
