### ISSUE TITLE
Question: Can I disable tools from options?

### ISSUE THREAD

**Issue by JanneTerho1** [iputils/iputils#295]
I need only ping tools. Can I disable other tools from meson_options.txt?

**Comment by kerolasa** [comment]
Use the `meson configure` to disable what  you don't need.

    meson builddir &&
    meson configure builddir -Dprefix=/usr -DBUILD_ARPING=false -DBUILD_CLOCKDIFF=false -DBUILD_NINFOD=false -DBUILD_RDISC=false -DBUILD_TRACEPATH=false &&
    make
