### ISSUE TITLE
remove "ping6" from the man pages

### ISSUE THREAD

**Issue by jsynacek** [iputils/iputils#30]
Since ping6 doesn't exist anymore, I suggest removing every mention about it from the man pages. Maybe also add a small "historical" note saying that ping6 has been merged into ping.

What do you think? I can submit a pull request if there are no objections.

**Comment by jsynacek** [comment]
And while we're at it, I can see that commit ebad35f also adds support for -4 and -6, but man pages didn't change.

**Comment by okias** [comment]
Yeah, 100% no objection. Go ahead and send pull request. Thank you! :)

**Comment by jsynacek** [comment]
https://github.com/iputils/iputils/pull/31

**Comment by lonaowna** [comment]
ping6 should also be removed from README.md
