### ISSUE TITLE
ninfod: policy: IPv6 allow Unique Local Addresses (site-local deprecated since 2004)

### ISSUE THREAD

**Issue by iam-TJ** [iputils/iputils#305]
`ninfod/ninfod_core.c::ni_policy()` uses `IN6_IS_ADDR_SITELOCAL(saddr)`  which tests for deprecated [0] (since 2004) site-local addresses `... == htonl (0xfec00000);` (from `netinet/in.h`) but doesn't test for the replacement, Unique Local Addresses (ULA) [1].

It would be very helpful to enable ULAs.

[0] https://tools.ietf.org/html/rfc3879

[1] https://tools.ietf.org/html/rfc4193

**Comment by ValZapod** [comment]
> It would be very helpful to enable ULAs.

Why?

**Comment by pevik** [comment]
NOTE: https://github.com/iputils/iputils/pull/388 is going to be removed.

**Comment by pevik** [comment]
ninfod has been removed.
