### ISSUE TITLE
Iputils compiler issues using VS CODE in Linux 

### ISSUE THREAD

**Issue by Sobia01** [iputils/iputils#307]
How to debug using visual studio this iputils project? please help, i am having compiler issues with this code? it's urgent.

**Comment by kerolasa** [comment]
Making demands to opensource project is not good way to contribute. If you have a problem with a compiler please find out how to fix it and share the improvement as a pull request. That would be great.

**Comment by pevik** [comment]
Unfortunately, we don't have access to visual studio, so we're unable to help you. This project targets to Linux, which uses gcc, clang and using meson build system.
