### ISSUE TITLE
Release 2021-01

### ISSUE THREAD

**Issue by pevik** [iputils/iputils#308]
I'm planning to release iputils in January.
I plan no code base.
I'll drop `s` from version name (#269).

@iputils/maintainers @ffontaine could you please test iputils?
@yurchor it looks to me there are no translation updates https://translate.fedoraproject.org/projects/iputils/iputils/, could you please ping translators?

**Comment by pevik** [comment]
Prepared CHANGELOG: https://github.com/iputils/iputils/pull/309
Unless there is any bug reported, I'd like to release sometimes next week.

**Comment by pevik** [comment]
@rffontenelle @tomop-tg any change you update iputils translation before release?

**Comment by tomop-tg** [comment]
I updated the Japanese translation on Fedora Weblate.
Thank you.

**Comment by pevik** [comment]
@tomop-tg updated in 3a95613b27ce0a9eb987fa053ba03a14ebab95f8.

**Comment by rffontenelle** [comment]
@pevik Working on it right now.

**Comment by pevik** [comment]
@rffontenelle I see you've been working yesterday on translations. Please let me know when you finish. I wanted today to release iputils, but I can do it sometime week.
Thanks to all translators for your work.
