### ISSUE TITLE
Socket :operation not permitted

### ISSUE THREAD

**Issue by xxllp** [iputils/iputils#314]
systemd rdisc service start error 
log: Socket :operation not permitted
and when delete PrivateUsers=yes  in rdisc.service  the service is ok 
but why?

**Comment by pevik** [comment]
I wonder if this was caused by missing `CAP_NET_ADMIN` capability, which was added in https://github.com/iputils/iputils/commit/710a161770aabd13e4f5028c325c41f63a417e4c. Probably not as the error looks different.
