### ISSUE TITLE
ping: Drop or lower minimal interval for flooding

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#317]
Forwarding this old [feature request from the Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=699238). I'm not necessarily in favor of making this change; pps flooding is still a favored DDoS mechanism. On the other hand, there are plenty of other ways to achieve similar effects.

The original request:

> $ ping -f localhost
> PING localhost (127.0.0.1) 56(84) bytes of data.
> ping: cannot flood; minimal interval, allowed for user, is 200ms
> 
> 200ms is a bit high for [the modern internet], could this limit be dropped? I think there's no good reason for it to exist nowadays.

**Comment by jsegitz** [comment]
I think we should have some limit here just to make sure people don't accidentally DoS themselves, but 200 ms is really high. We could set it to 2 ms. If someone needs to go lower than this then more specialized tooling is easily available

**Comment by pevik** [comment]
@jsynacek @OlafvdSpek FYI

**Comment by OlafvdSpek** [comment]
> If someone needs to go lower than this then more specialized tooling is easily available

Like prefixing the command with sudo? ;)

If you're a bad actor this check isn't going to stop you. If not, is there a real problem?

**Comment by jsegitz** [comment]
yes. I agree that the check will not stop you, so we can set it so low that it allows for better usage but prevents accidental damage. If you want to do damage use sudo ;)

**Comment by ValZapod** [comment]
Wait a second. Are you saying this is an iputils limit!? Wow. I thought there is some internal linux kernel problem. This is totaly not needed. You can always chroot, get root and it will work even if you are not root. An example my linux on dex tablet. I do not have root on it.

**Comment by pevik** [comment]
Chroot is usually protected by root permission. I'm for lowering it to 2 sec to protect *accidental* DoS. As stated previously there are many ways to do DoS if you *want*.

**Comment by ValZapod** [comment]
> Chroot is usually protected by root permission.

What about virtualisation? But my Linux on dex does not use virtualisation, it uses the same kernel as in  Android itself.

**Comment by nmeyerhans** [comment]
> > Chroot is usually protected by root permission.
> 
> What about virtualisation? But my Linux on dex does not use virtualisation, it uses the same kernel as in Android itself. Anyway, I now understand and not surprised why root magic worked for ping and not for apt-get dist-upgrade upgrading kernel. Ha. It cannot update kernel which is part of android.

Any mechanism that lets you bypass this limit requires elevated privileges. Virtualization, chroot, containers, etc are orthogonal to the privilege issue; a completely unprivileged VM won't have the ability to send ICMP packets out a physical interface on the host system, even if you have the ability to generate them internally. Some virtualization or containerization environments make it easy to obtain the necessary privileges, often without you realizing that you've done so. For example it's pretty common to allow unprivileged users to instantiate Docker containers. However, doing so grants additional privileges.
