### ISSUE TITLE
Support RFC 5837 extensions in traceroute

### ISSUE THREAD

**Issue by Ishaangandhi** [iputils/iputils#322]
Per [RFC 5837 Section 3.1](https://tools.ietf.org/html/rfc5837#section-3.1), ICMP TTL Exceeded messages may carry information about the interface on which an error causing message was received, which can be used for an enhanced traceroute.

Would such a patch be welcome in IP Utils? If so, I would be happy to submit a merge request.

**Comment by kerolasa** [comment]
@Ishaangandhi yes, improvements and fixes are always welcome.

**Comment by Ishaangandhi** [comment]
@kerolasa Glad to hear it :-) I've submitted a patch here: https://github.com/iputils/iputils/pull/324

**Comment by pevik** [comment]
Closing as we removed traceroute6 in a1394212fd4b3e3259104467d9861909961b219e.
