### ISSUE TITLE
Add hostname command?

### ISSUE THREAD

**Issue by concatime** [iputils/iputils#327]
Hi.
There are numerous networking packages:
 - inetutils
 - iproute2
 - iputils
 - net-tools

Ideally, I would install only `iproute2` and `iputils` mainly for `ip` and `ping`.
When I added `dhcpcd`, I realized that that a I had an error:
```
/libexec/dhcpcd-hooks/30-hostname: hostname: not found
```
The thing is that I don’t want to install `inetutils` (which provides `hostname`)
because it also provides ping, just like iputils.

Have you considered adding `hostname`? If you’re explicitly against this idea, may I know why?
Thank you.

**Comment by pevik** [comment]
IMHO `hostname` definitely shouldn't be added into iputils.
I guess `hostname` is likely provided in any distro (e.g. in Debian there is `hostname` package [1]).
Which distro do you use? Is it for buildroot? [2]

[1] https://packages.debian.org/sid/hostname
[2] https://git.busybox.net/buildroot/tree/package/dhcpcd/dhcpcd.mk

**Comment by concatime** [comment]
I’m building my own distro and decided to use iputils over inetutils.
And thank you @pevik, I wasn’t aware of debian’s hostname.

**Comment by concatime** [comment]
Out of topic, but have you considered using libcap-ng over regular libcap?

**Comment by pevik** [comment]
I don't think so. I'd certainly use libcap-ng for a new project, but as not sure what would it improve as the code is already written.
