### ISSUE TITLE
ping still using regional settings for interval decimal point

### ISSUE THREAD

**Issue by David-Lor** [iputils/iputils#329]
Issue: "ping" interval setting (`-i`) uses regional setting for decimal point instead of dot (standard POSIX locale).

```bash
david@Ubuntu-Main:~$ ping -i 3.5 8.8.8.8
ping: bad timing interval: 3.5
david@Ubuntu-Main:~$ ping -i 3,5 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=14.4 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=116 time=14.0 ms
^C
--- 8.8.8.8 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 3501ms
rtt min/avg/max/mdev = 13.971/14.208/14.446/0.237 ms
```

Theorically, PR #37 fixed this back in 2015; my ping version is `ping from iputils s20190709` (from Ubuntu 20.04), so I guess such fix should be included.

Related issue: #273

**Comment by pevik** [comment]
Well, reporting buf for 2 years old version  (s20190709) does not make much sense :). We later rethink and decided always use dot, see https://github.com/iputils/iputils/commit/1530bc9719c6bf4d01dd20b26e904995903d82d8, released in s20200821 and ]properly documented](https://github.com/iputils/iputils/releases/tag/s20200821).

**Comment by David-Lor** [comment]
@pevik Thank you for the clarification! I didn't imagine it would be rolled back, that's why I though it was some sort of legit issue.

If somebody wants to force the usage of the "dot notation", I was able to do so by setting the locale at runtime, doing something like this:

```bash
LANG=C ping -i 1.5 8.8.8.8
```

Output:

```bash
david@Ubuntu-Main:~$ ping -i 1.5 8.8.8.8
ping: bad timing interval: 1.5
david@Ubuntu-Main:~$ LANG=C ping -i 1.5 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=116 time=14.5 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=116 time=14.3 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=116 time=14.3 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 14.264/14.354/14.482/0.092 ms
```
