### ISSUE TITLE
ping: No errors if an interface is specified

### ISSUE THREAD

**Issue by tashanamatl** [iputils/iputils#339]
When the ICMP socket is bound to an interface, if trying to ping an
address that is unreachable then no errors will be received, as they come in
through the lo interface. To be able to get useful errors the binding of the icmp socket to the device added in https://github.com/iputils/iputils/commit/f455fee41c077d4b700a473b2f5b3487b8febc1d may need to be removed.

Before that patch:
ping -4 192.168.1.2 -I vlan1000 -c 5
PING 192.168.1.2 (192.168.1.2) from 192.168.1.100 vlan1000: 56(84) bytes of data.
From 192.168.1.100 icmp_seq=1 Destination Host Unreachable
From 192.168.1.100 icmp_seq=2 Destination Host Unreachable
From 192.168.1.100 icmp_seq=3 Destination Host Unreachable
From 192.168.1.100 icmp_seq=4 Destination Host Unreachable
From 192.168.1.100 icmp_seq=5 Destination Host Unreachable

--- 192.168.1.2 ping statistics ---
5 packets transmitted, 0 received, +5 errors, 100% packet loss, time 4179ms

After the patch:
ping -4 192.168.1.2 -I vlan1000 -c 5
PING 192.168.1.2 (192.168.1.2) from 192.168.1.100 vlan1000: 56(84) bytes of data.

--- 192.168.1.2 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4130ms

**Comment by pevik** [comment]
@tashanamatl any change you specify steps to reproduce the issue? Ideally with using network namespaces, see some examples of netns based reproducers:

https://github.com/iputils/iputils/pull/340#issuecomment-987219698
https://github.com/iputils/iputils/pull/296#issuecomment-710044824
https://github.com/iputils/iputils/issues/371#issuecomment-922582756
https://github.com/iputils/iputils/pull/344
https://github.com/iputils/iputils/issues/300

**Comment by pevik** [comment]
@tashanamatl I guess it's the same issue as https://github.com/iputils/iputils/issues/398? I.e. fixed in 5.17 and stable kernels? (https://github.com/iputils/iputils/pull/405#issuecomment-1146359974)

**Comment by tashanamatl** [comment]
> 
I'm not sure, it looks like this issue is  just IPv6 but the issue I was seeing was only IPv4. I actually think #391 might be related.

**Comment by pevik** [comment]
@tashanamatl could you please share more info about your NIC `vlan1000`. e.g `ip link`, I'm not able to reproduce similar case:

```
$ ping -c2 192.168.122.230 -I virbr0
PING 192.168.122.230 (192.168.122.230) from 192.168.122.1 virbr0: 56(84) bytes of data.
64 bytes from 192.168.122.230: icmp_seq=1 ttl=64 time=0.371 ms
64 bytes from 192.168.122.230: icmp_seq=2 ttl=64 time=0.381 ms

--- 192.168.122.230 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1019ms
rtt min/avg/max/mdev = 0.371/0.376/0.381/0.005 ms
```

Ideally steps to reproduce would be great.

**Comment by tashanamatl** [comment]
Hi @pevik, 
This issue was found on s20190709 so it's possible that changes since that release have fixed the issue. 
The problem was that when an interface was specified and the address attempted to ping was unreachable then no errors would be received. It looks like you were pinging an address that is reachable as you're getting a response.

**Comment by pevik** [comment]
@tashanamatl would you mind to test it on latest master? Because I'm not able to reproduce it.

**Comment by eaglegai** [comment]
@pevik 
**in iputils-20210722，can't reproduce：**( maybe this has been fixed)
[root@localhost ping]# ./ping 99.99.99.100 -I 99.99.99.99 -c 2
PING 99.99.99.100 (99.99.99.100) from 99.99.99.99 : 56(84) bytes of data.
From 99.99.99.99 icmp_seq=1 Destination Host Unreachable
From 99.99.99.99 icmp_seq=2 Destination Host Unreachable

--- 99.99.99.100 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1062ms
pipe 2
[root@localhost ping]# ./ping 99.99.99.100  -c 2
PING 99.99.99.100 (99.99.99.100) 56(84) bytes of data.
From 99.99.99.99 icmp_seq=1 Destination Host Unreachable
From 99.99.99.99 icmp_seq=2 Destination Host Unreachable

--- 99.99.99.100 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1058ms
pipe 2


**in  iputils-s20190709 version, can  reproduce:**
[root@localhost x86_64-openEuler-linux-gnu]# ./ping 99.99.99.100  -c 2
PING 99.99.99.100 (99.99.99.100) 56(84) bytes of data.
From 99.99.99.99 icmp_seq=1 Destination Host Unreachable
From 99.99.99.99 icmp_seq=2 Destination Host Unreachable

--- 99.99.99.100 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1020ms
pipe 2
[root@localhost x86_64-openEuler-linux-gnu]# ./ping 99.99.99.100 -I eth0 -c 2
PING 99.99.99.100 (99.99.99.100) from 9.82.227.244 eth0: 56(84) bytes of data.

--- 99.99.99.100 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1048ms

[root@localhost x86_64-openEuler-linux-gnu]#

**Comment by tashanamatl** [comment]
I haven't been able to reproduce this issue again.
