### ISSUE TITLE
New release 202107

### ISSUE THREAD

**Issue by pevik** [iputils/iputils#343]
@iputils/maintainers @yurchor @vapier I'd like to release new version sometime during mid of July. Could you please test it? All changes will have to wait after release.

@yurchor Could you please ping translators? (I noticed only small change in Chinese, which is incompatible with other changes)

**Comment by yurchor** [comment]
> @yurchor Could you please ping translators? (I noticed only small change in Chinese, which is incompatible with other changes)

Done. Thanks for the notice.

**Comment by pevik** [comment]
@yurchor thanks, I see some updates in translation git (added full Czech translation, updated Portuguese (Brazil) and Chinese (Simplified)). There is also empty Bulgarian translation. Do you think I should wait for translation little longer before making the release?

**Comment by yurchor** [comment]
No. I see no substantial reasons to wait.

**Comment by pevik** [comment]
@yurchor Actually I forget to update `iputils.pot`, merged it now, hope https://translate.fedoraproject.org should get updated soon. Thus I'll wait few days for update. Can you ping translators?
@ppisar @rffontenelle FYI

**Comment by yurchor** [comment]
On Sunday. AFK now.

**Comment by ppisar** [comment]
V Fri, Jul 09, 2021 at 02:10:34AM -0700, Petr Vorel napsal(a):
> @yurchor Actually I forget to update `iputils.pot`, merged it now, hope
> https://translate.fedoraproject.org should get updated soon.

That's not enough.

The weblate iputils repository is out of sync with the GitHub repository
<https://translate.fedoraproject.org/projects/iputils/iputils/#alerts>.
A merge conflict on ja.po. I think that an iputil administrator needs to fix
it manually as documented on the link.

-- Petr

**Comment by pevik** [comment]
@ppisar thx for info. I'm not registered, I suppose @yurchor fix that once he gets back.

**Comment by yurchor** [comment]
Done. Everything is synced, the ping is sent.

**Comment by nmeyerhans** [comment]
I've been mostly offline for the past couple of weeks. I'll work on testing this, and will upload to Debian's experimental branch for additional testing.

**Comment by pevik** [comment]
@nmeyerhans FYI the only 2 patches I consider before releasing (ideally resolve that tomorrow:
* https://github.com/iputils/iputils/pull/358
* https://github.com/iputils/iputils/pull/348 (and related https://github.com/iputils/iputils/pull/347 which should be together in single commit)

Not sure if add Korean translation, which has only 26% (https://translate.fedoraproject.org/projects/iputils/iputils/, URL is also git if you clone it).
