### ISSUE TITLE
Remove legacy tools

### ISSUE THREAD

**Issue by pevik** [iputils/iputils#363]
* `ninfod`
Is it still relevant and should be kept? It's packaged for Packaged for [Fedora](https://src.fedoraproject.org/rpms/iputils/blob/rawhide/f/iputils.spec) as a separate package (@jsynacek).

* `rarpd`
Reason: obsoleted by BOOTP and later DHCP protocols.  Packaged for [openSUSE](https://build.opensuse.org/package/view_file/network:utilities/iputils/iputils.spec?expand=1) as a separate package (@pevik).
Debian has [very old version](https://tracker.debian.org/media/packages/r/rarpd/copyright-0.981107-9) from the same author, as a [separate package](https://tracker.debian.org/pkg/rarpd).

* `rdisc`
Is it still relevant and should be kept? Packaged for [Fedora](https://src.fedoraproject.org/rpms/iputils/blob/rawhide/f/iputils.spec) (@jsynacek) and [openSUSE](https://build.opensuse.org/package/view_file/network:utilities/iputils/iputils.spec?expand=1) (@pevik).

* `tftpd`
requires inetd to run, that is quite a rarity nowadays, `dnsmasq` is much better alternative, but maybe the size is relevant (`dnsmasq`: 432K, `tftpd`: 60K). Packaged for [openWRT](https://github.com/openwrt/packages/blob/master/net/iputils/Makefile) (@nmeyerhans)
**UPDATE**: PR https://github.com/iputils/iputils/pull/369

* `traceroute6`
Packaged for [Debian](https://salsa.debian.org/debian/iputils/-/blob/master/debian/rules) (@nmeyerhans), which [traceroute from Dmitry Butskoy](https://tracker.debian.org/pkg/traceroute).
**UPDATE** removed in: https://github.com/iputils/iputils/pull/362.

@jsynacek @nmeyerhans @okias  @nmav @vapier @yurchor @neheb @6eh01der @sevan @zenczykowski @floppym could you please note what you prefer keep and what to remove?

**Comment by jsynacek** [comment]
I'm fine with removing `ninfod` and `rdisc`. Note that I'm not a Fedora/RHEL maintainer anymore and I've stopped working on anything packaging related.

**Comment by 6eh01der** [comment]
rdisc has no alternatives (i mean something that implements ICMP router discovery protocol) and i think that it may be useful in some scanarios. It's very simple and stable tool. I don't know how widely it is used but recently i had need to build package for ubuntu. It does not exist in ubuntu and debian repos. But it included by default in all rpm distros that i know.

**Comment by floppym** [comment]
I'm fine with dropping all of these.

**Comment by nmeyerhans** [comment]
> ninfod

ninfod implements an [obsolete experimental protocol](https://datatracker.ietf.org/doc/html/rfc4620) that hasn't seen any activity since 2006. It's pretty dead at this point. In the unlikely event that anybody ever starts work on this protocol again, the code will still exist in git history, and I think that's enough. We should drop this.

> tftpd

There are additional tftp implementations besides dnsmasq as well. I usually reach for [hpa's implementation](https://git.kernel.org/pub/scm/network/tftp/tftp-hpa.git) if I need one, but [atftp](https://sourceforge.net/projects/atftp/) is another option.

> rarpd

It's only been obsolete since 1985! Maybe if somebody out there needs to bootstrap a 1970's era VAX or something, this might be useful, but I don't see it being worth much maintainer attention. Historical versions of the code are always available in git.

> rdisc has no alternatives (i mean something that implements ICMP router discovery protocol) and i think that it may be useful in some scanarios. It's very simple and stable tool. I don't know how widely it is used but recently i had need to build deb package for work purposes. It does not exist in ubuntu and debian repos. But it included by default in all rpm distros that i know.

There is an [ancient request](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=457059) to package this for Debian, but I've never gotten around to it. I can't envision a scenario where IRDP is preferable in any way to DHCP for these purposes. I'd love to hear a legitimate use case for it.

> traceroute6

Drop it. There's another implementation, and we've got tracepath anyway.

**Comment by 6eh01der** [comment]
@nmeyerhans DHCP is more complex to configure and it will not save your machines from gateway dead and also for DHCP server failover scenarios you should implement some reserve instance. I don't think that all dns server implementations support automatic failover... About gateway - yes, you could announce some VIP for clients,(for example if you have two gateways with keepalived), but not allways you could have a keepalived or something similar,(i know only one another VRRP implementation - vrrpd, for Windows there is no VRRP at all, but Routing and Remote Access role supports IRDP server). And so in some situations it may be appropriate to have some routers with IRDP server and rdisc as client at other machines. Gateway will be choosed by annoucement preference, so if announcement with higher preference is no more seen another with lower will be applied. Work and simple gateway failover. Also i see that IRDP present in Juniper and Cisco documentation and it looks like their devices still support it.

**Comment by Amanuense-del-diavolo** [comment]
to be honest I've just finished writing the systemd units for tftpd, if possible I'd much rather have a tftp server installed with iputils that having to install another package, it's small, it's usable, and it gets the job done

**Comment by vapier** [comment]
the canonical one (tftp hpa) is more featureful. I don't see value in competing in this space, especially when the iputils one is uncommon. just drop it and don't waste more time on it.

**Comment by pevik** [comment]
@Amanuense-del-diavolo "it's small: our `tftpd` has 60K, exactly the same size as `in.tftpd` from hpa. Anyway, really going to remove as agree with @vapier.

**Comment by Amanuense-del-diavolo** [comment]
> @Amanuense-del-diavolo "it's small: our `tftpd` has 60K, exactly the same size as `in.tftpd` from hpa. Anyway, really going to remove as agree with @vapier.

oh well, the irony of implement a thing and the next day it gets dropped, 😂
I admit I wasn't checking tftpd-hpa's dimension but the dnsmasq implementation
cheers

**Comment by pevik** [comment]
@Amanuense-del-diavolo I'm sorry to drop your work, but this is a result of considering a time which requires maintaining things which aren't widely used because others project are more mature. Would you please consider contributing systemd service to hpa project which also lack it? (NOTE dnsmasq - a live project which implements tftpd - already has systemd service).

**Comment by sevan** [comment]
Apologies for never chiming in, I leave it to you to decide. I would've preferred traceroute6 stayed as that makes things easier to jump between different envs (the BSDs and macOS by heritage ship with traceroute6) but I'll seek out the other implementation mentioned here or just pull the removed copy from here back in.
