### ISSUE TITLE
Ping ignores reply from IPv6 Subnet-Router anycast address (RFC4291)

### ISSUE THREAD

**Issue by tsndqst** [iputils/iputils#371]
A change occurred between s20190709 and s20200821 that broke support for receiving a reply when pinging the Subnet-Router anycast address.  The Subnet-Router anycast address is specified in https://datatracker.ietf.org/doc/html/rfc4291#section-2.6.1.

I traced it to the [ping: discard packets with wrong source address](https://github.com/iputils/iputils/commit/5e052ada96c3fc457efe66b2fed5c14ed8de6ae3#diff-86631a19430a9eabf1a2c47fe18364b4a7f81aea07d4cdf5bac35fd1e7ec76e6) commit in `ping/ping6_common.c`.  

I found the commit above using `git bisect` and confirmed that before the commit pinging the Subnet-Router anycast address worked.
I also confirmed on master branch that removing the `if` statement from the commit above resolves the issue.

This snippet shows pinging the Subnet-Router anycast address on Ubuntu Focal with iputils s20190709.
```
root@ubuntu-focal:~# ping6 -V
ping from iputils s20190709
root@ubuntu-focal:~# ping6 -c1 fd42:6356:abfe:1549:: -W5
PING fd42:6356:abfe:1549::(fd42:6356:abfe:1549::) 56 data bytes
64 bytes from fd42:6356:abfe:1549::1: icmp_seq=1 ttl=64 time=0.107 ms

--- fd42:6356:abfe:1549:: ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.107/0.107/0.107/0.000 ms
```
This snippet shows pinging the Subnet-Router anycast address on Ubuntu Groovy with iputils s20200821.
```
root@ubuntu-groovy:~# ping6 -V
ping from iputils s20200821
root@ubuntu-groovy:~# ping6 -c1 fd42:6356:abfe:1549:: -W5
PING fd42:6356:abfe:1549::(fd42:6356:abfe:1549::) 56 data bytes

--- fd42:6356:abfe:1549:: ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

Using `tcpdump` I saw the replies coming back from the router on the fd42:6356:abfe:1549::/64 subnet but the replies were not displayed by the ping command.

**Comment by pevik** [comment]
@teknoraver FYI
@tsndqst any idea how to setup VLAN on which I could reproduce the problem?

**Comment by teknoraver** [comment]
@pevik can you paste the output of `sysctl net.ipv4.ping_group_range`?

**Comment by pevik** [comment]
> @pevik can you paste the output of `sysctl net.ipv4.ping_group_range`?

@tsndqst ^ 

@teknoraver I'm not really sure that strict following of RFC 1122 was a good idea (https://networkengineering.stackexchange.com/questions/76321/configure-virtual-lan-with-subnet-router-anycast-address-to-debug-ping-bug), considering to revert it.

@nmeyerhans @nmav WDYT?

**Comment by tsndqst** [comment]
> @pevik can you paste the output of `sysctl net.ipv4.ping_group_range`?

@teknoraver `net.ipv4.ping_group_range = 65534`.  I'm not sure what has to do with ipv6 ping.

@pevik I'll have to think about it.  I tested with an LXC container since I already had it set up.  I'll see if I can come up with a straight forward way to fully test this.

**Comment by teknoraver** [comment]
The problem here is that you are receiving a response from a different address than the one you are initially trying to ping.

Does it work if you add the `-b` flag?

**Comment by tsndqst** [comment]
@pevik A test VLAN would need at least two hosts with IPv6 IPs in the same subnet and one host that's not the source needs to have IPv6 forwarding enabled. 
For example `net.ipv6.conf.all.forwarding = 1` or for an individual interface on the VLAN.

@teknoraver My understanding is that that's the point of the Subnet-Router anycast address.  Pinging the anycast address will result in a reply from one of the routers on the subnet.  Here is another description of it: https://into6.com.au/2014/03/30/subnet-router-anycast-addresses-what-are-they-how-do-they-work/

**Comment by tsndqst** [comment]
@pevik I found a netns script that sets up an ipv6 network that you can test with.
It's a slightly modified version of https://gist.github.com/dpino/76b0bf7f522bd0d2e442eca06ae9db76
I changed the ipv6 ULA subnet a bit and removed the NAT from the original.

From the shell that starts at the end of the script you should be able to ping `fd00:dead:beef:1234::` and get a reply from `fd00:dead:beef:1234::1`.  I suppose you could automate it by running `ping -c1 -W5 fd00:dead:beef:1234::` instead of bash at the end of the script.

```
#!/usr/bin/env bash

set -x                                                                                       
 
if [[ $EUID -ne 0 ]]; then                                                                   
   echo "You must run this script as root."
   exit 1
fi                                                                                           
 
VETH1_IPV6=fd00:dead:beef:1234::1                                                                           
VPEER1_IPV6=fd00:dead:beef:1234::2                                                                          

# Clean up.                                                                                  
ip netns del ns-ipv6 &>/dev/null                                                             
ip li del veth1 &> /dev/null                                                                 

# Create network namespace.                                                                  
ip netns add ns-ipv6                                                                         

# Create veth pair.                                                                          
ip li add name veth1 type veth peer name vpeer1                                              

# Setup veth1 (host).                                                                        
ip -6 addr add ${VETH1_IPV6}/64 dev veth1                                                    
ip li set dev veth1 up                                                                       

# Setup vpeer1 (network namespace).                                                          
ip li set dev vpeer1 netns ns-ipv6                                                           
ip netns exec ns-ipv6 ip li set dev lo up                                                    
ip netns exec ns-ipv6 ip -6 addr add ${VPEER1_IPV6}/64 dev vpeer1                            
ip netns exec ns-ipv6 ip li set vpeer1 up                                                    

# Direct external traffic to VETH1 through VPEER1 (default gw).                              
ip netns exec ns-ipv6 ip -6 route add default dev vpeer1 via ${VETH1_IPV6}                   

# IP Forwarding.                                                                             
sysctl -w net.ipv6.conf.all.forwarding=1                                                     

# Get into ns-ipv6.                                                                          
ip netns exec ns-ipv6 /bin/bash --rcfile <(echo "PS1=\"ns-ipv6> \"")
```

**Comment by teknoraver** [comment]
Because `-b` is an ipv4 only flag by now. We should make it effective in ipv6 too with:

```patch
--- a/ping/ping6_common.c
+++ b/ping/ping6_common.c
@@ -819,7 +819,7 @@ int ping6_parse_reply(struct ping_rts *rts, socket_st *sock,
 	}
 
 	if (icmph->icmp6_type == ICMP6_ECHO_REPLY) {
-		if (!rts->multicast &&
+		if (!(rts->multicast || rts->broadcast_pings) &&
 		    memcmp(&from->sin6_addr.s6_addr, &rts->whereto6.sin6_addr.s6_addr, 16))
 			return 1;
 		if (!is_ours(rts, sock, icmph->icmp6_id))
```

Can you give it a try?

**Comment by teknoraver** [comment]
Or maybe this is more appropiate:
```patch
--- a/ping/ping6_common.c
+++ b/ping/ping6_common.c
@@ -235,7 +235,7 @@ int ping6_run(struct ping_rts *rts, int argc, char **argv, struct addrinfo *ai,
 		ipi->ipi6_ifindex = if_name2index(rts->device);
 	}
 
-	if (IN6_IS_ADDR_MULTICAST(&rts->whereto6.sin6_addr)) {
+	if (IN6_IS_ADDR_MULTICAST(&rts->whereto6.sin6_addr) || rts->broadcast_pings) {
 		rts->multicast = 1;
 		if (rts->uid) {
 			if (rts->interval < 1000)
```

**Comment by tsndqst** [comment]
I tried the second patch.  Pinging the subnet-router anycast address works with that patch.  Thanks.

**Comment by teknoraver** [comment]
Ok, I will submit a patch along with updated description and help message.

Thanks!

**Comment by pevik** [comment]
@teknoraver thx.

Unfortunately with netns configuration it does not work with your patchset, but it works when reverted 5e052ada96c3fc457efe66b2fed5c14ed8de6ae3. I have to look closely, but whether there is another problem or it's really caused by assumption from RFC 1122.

**Comment by teknoraver** [comment]
I didn't, I asked @tsndqst for test.
Anyway, I can try to repro it with the netns

**Comment by teknoraver** [comment]
@pevik I tried the netns setup, it works for me:
```
root@debian64:~# ip netns exec ns-ipv6 ./ping fd00:dead:beef:1234::
PING fd00:dead:beef:1234::(fd00:dead:beef:1234::) 56 data bytes
^C
--- fd00:dead:beef:1234:: ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1031ms

root@debian64:~# ip netns exec ns-ipv6 ./ping -b fd00:dead:beef:1234::
PING fd00:dead:beef:1234::(fd00:dead:beef:1234::) 56 data bytes
64 bytes from fd00:dead:beef:1234::1: icmp_seq=1 ttl=64 time=0.035 ms
64 bytes from fd00:dead:beef:1234::1: icmp_seq=2 ttl=64 time=0.027 ms
^C
--- fd00:dead:beef:1234:: ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1060ms
rtt min/avg/max/mdev = 0.027/0.031/0.035/0.004 ms
```

**Comment by teknoraver** [comment]
That is the case with anycast, you will get reply for more than host.
Indeed with this change it gets the same limitations of ipv4 broadcast, i.e. can't set a low interval, which can be dangerous

**Comment by pevik** [comment]
@teknoraver FYI still wait for the input from @nmeyerhans, but really tend to revert your original commit 5e052ada96c3fc457efe66b2fed5c14ed8de6ae3 to keep the original functionality.

**Comment by teknoraver** [comment]
@pevik and break RFC 777:

```
   Addresses

      The address of the source in an echo message will be the
      destination of the echo reply message.  To form an echo reply
      message, the source and destination addresses are simply reversed.
```

Can't we simply support all the cases?

**Comment by teknoraver** [comment]
I don't know a way to detect Subnet-Router anycast address. They are the first address of a network, I guess that the user know in advance that the address is one of those.

I propose to change the documentation, saying that `-b` is used to ping broadcast, multicast and ipv6 Subnet-Router anycast addresses. In short, any address which will receive one (or more) replies from a different IP than the source one.

That will honour RFC 777 and allow to ping Subnet-Router anycast addresses

**Comment by tsndqst** [comment]
Sorry if I opened a can of worms with this request.  I don't really have any use for it I just noticed the regression and thought it would be a straight-forward fix.

**Comment by pevik** [comment]
@teknoraver I'll try to research before giving up. Just give me some time (my time for iputils is very limited).
@tsndqst No problem at all.
Thank you both to your work. I'd like to release iputils soon, but this issue is important enough to be solved first.

**Comment by pevik** [comment]
@teknoraver @tsndqst could you please have look on https://github.com/iputils/iputils/pull/376?
