### ISSUE TITLE
ping ignores round robin DNS

### ISSUE THREAD

**Issue by logistiker** [iputils/iputils#377]
I have round robin DNS set up on my internal network and I cannot get ping to recognize the second A record for the same domain.  It always uses the first A record.  I don't have any DNS caching set up on the client that is executing ping.  Other programs I have tested don't have any problems accessing the machine with the second A record (e.g. ssh, firefox, dig, nslookup, php via gethostnamel).

**Comment by nmeyerhans** [comment]
There's really no such thing as round-robin DNS. RFC 3484 specifies that results of the `getaddrinfo()` library call always be returned in the same order. This behavior is configured by the [/etc/gai.conf](https://manpages.debian.org/bullseye/manpages/gai.conf.5.en.html) configuration file on glibc-based Linux systems. Other operating systems or C library implementations may have other knobs for configuring this behavior.

If other applications are choosing to randomize the list of IPs returned by `getaddrinfo()`, that's fine. I don't think ping should be doing this, however. The behavior of ping, including the IP address with which it communicates, should be deterministic.

**Comment by logistiker** [comment]
So how would you ping a domain where one interface is down while the other is up but the first interface (IP) was specified in the DNS?  Or am I supposed to use a different utility to determine whether a host is responding?

**Comment by logistiker** [comment]
Also, editing the client gai.conf file to make this work doesn't seem like the right way to fix this.  If getaddrinfo() is the problem, perhaps ping should not use it.  My guess is that all the other programs that I mentioned don't use it and have a different solution to make this work.

**Comment by pevik** [comment]
You mean https://en.wikipedia.org/wiki/Round-robin_DNS.

Well, `ping` using random order each time you call it:

```
$ dig +nocmd +noall +answer
seznam.cz.		84	IN	A	77.75.74.176
seznam.cz.		84	IN	A	77.75.75.172
seznam.cz.		84	IN	A	77.75.74.172
seznam.cz.		84	IN	A	77.75.75.176

$ ping -c 3 seznam.cz
PING seznam.cz (77.75.75.172) 56(84) bytes of data.
64 bytes from 77.75.75.172 (77.75.75.172): icmp_seq=1 ttl=54 time=27.3 ms
64 bytes from 77.75.75.172 (77.75.75.172): icmp_seq=2 ttl=54 time=17.2 ms
64 bytes from 77.75.75.172 (77.75.75.172): icmp_seq=3 ttl=54 time=13.4 ms

--- seznam.cz ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2004ms
rtt min/avg/max/mdev = 13.423/19.305/27.271/5.842 ms

$ ping -c 3 seznam.cz
PING seznam.cz (77.75.75.176) 56(84) bytes of data.
64 bytes from 77.75.75.176 (77.75.75.176): icmp_seq=1 ttl=54 time=14.1 ms
64 bytes from 77.75.75.176 (77.75.75.176): icmp_seq=2 ttl=54 time=16.6 ms
64 bytes from 77.75.75.176 (77.75.75.176): icmp_seq=3 ttl=54 time=11.6 ms

--- seznam.cz ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2004ms
rtt min/avg/max/mdev = 11.618/14.102/16.629/2.045 ms

$ ping -c 3 seznam.cz
PING seznam.cz (77.75.74.172) 56(84) bytes of data.
64 bytes from www.seznam.cz (77.75.74.172): icmp_seq=1 ttl=54 time=50.2 ms
64 bytes from www.seznam.cz (77.75.74.172): icmp_seq=2 ttl=54 time=12.6 ms
64 bytes from www.seznam.cz (77.75.74.172): icmp_seq=3 ttl=54 time=18.9 ms

--- seznam.cz ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 12.588/27.228/50.199/16.445 ms
```

The same way works [`fping`](https://www.fping.org/) and `ping` from busybox:

```
$ fping -c 3 -d -A seznam.cz
77.75.75.176 (77.75.75.176) : [0], 64 bytes, 23.1 ms (23.1 avg, 0% loss)
77.75.75.176 (77.75.75.176) : [1], 64 bytes, 22.7 ms (22.9 avg, 0% loss)
77.75.75.176 (77.75.75.176) : [2], 64 bytes, 10.7 ms (18.8 avg, 0% loss)

$ busybox ping -c3 seznam.cz
PING seznam.cz (77.75.74.172): 56 data bytes
64 bytes from 77.75.74.172: seq=0 ttl=54 time=10.708 ms
64 bytes from 77.75.74.172: seq=1 ttl=54 time=14.763 ms
64 bytes from 77.75.74.172: seq=2 ttl=54 time=10.686 ms
```

You want it to randomize it during each call which I also don't think it's a good idea to be a default as it's non-deterministic as @nmeyerhans mentioned. Other tools try hard to be connected (with extra functionality put on the top of `getaddrinfo()`), but `ping` is a diagnostic tool (different goal). We could think about adding this feature as a non-default option (but I don't have time to implement it).

Also [`fping`](https://www.fping.org/) has very interesting [`-m`](https://www.fping.org/fping.1.html) option, which queries everything:

```
$ fping  -d -A -m seznam.cz
www.seznam.cz (77.75.74.176) is alive
77.75.75.176 (77.75.75.176) is alive
www.seznam.cz (77.75.74.172) is alive
77.75.75.172 (77.75.75.172) is alive
2a02:598:3333:1::1 (2a02:598:3333:1::1) is unreachable
2a02:598:4444:1::2 (2a02:598:4444:1::2) is unreachable
2a02:598:4444:1::1 (2a02:598:4444:1::1) is unreachable
2a02:598:3333:1::2 (2a02:598:3333:1::2) is unreachable

$ fping -c 1 -d -A -m seznam.cz
77.75.75.172 (77.75.75.172)             : [0], 64 bytes, 23.4 ms (23.4 avg, 0% loss)
www.seznam.cz (77.75.74.172)            : [0], 64 bytes, 15.5 ms (15.5 avg, 0% loss)
77.75.75.176 (77.75.75.176)             : [0], 64 bytes, 7.06 ms (7.06 avg, 0% loss)
www.seznam.cz (77.75.74.176)            : [0], 64 bytes, 41.0 ms (41.0 avg, 0% loss)
2a02:598:3333:1::2 (2a02:598:3333:1::2) : [0], timed out (NaN avg, 100% loss)
2a02:598:4444:1::1 (2a02:598:4444:1::1) : [0], timed out (NaN avg, 100% loss)
2a02:598:4444:1::2 (2a02:598:4444:1::2) : [0], timed out (NaN avg, 100% loss)
2a02:598:3333:1::1 (2a02:598:3333:1::1) : [0], timed out (NaN avg, 100% loss)

77.75.75.172 (77.75.75.172)             : xmt/rcv/%loss = 1/1/0%, min/avg/max = 23.4/23.4/23.4
www.seznam.cz (77.75.74.172)            : xmt/rcv/%loss = 1/1/0%, min/avg/max = 15.5/15.5/15.5
77.75.75.176 (77.75.75.176)             : xmt/rcv/%loss = 1/1/0%, min/avg/max = 7.06/7.06/7.06
www.seznam.cz (77.75.74.176)            : xmt/rcv/%loss = 1/1/0%, min/avg/max = 41.0/41.0/41.0
2a02:598:3333:1::2 (2a02:598:3333:1::2) : xmt/rcv/%loss = 1/0/100%
2a02:598:4444:1::1 (2a02:598:4444:1::1) : xmt/rcv/%loss = 1/0/100%
2a02:598:4444:1::2 (2a02:598:4444:1::2) : xmt/rcv/%loss = 1/0/100%
2a02:598:3333:1::1 (2a02:598:3333:1::1) : xmt/rcv/%loss = 1/0/100%
```

**Comment by nmeyerhans** [comment]
> You mean https://en.wikipedia.org/wiki/Round-robin_DNS.

Some of the web pages linked from that describe the details of `getaddrinfo()` sorting the DNS responses, and some of the problems it caused. However, it's possible that they (along with my understanding of things) are outdated, and `getaddrinfo()` is sorting things more sanely now.

In any case, `ping` doesn't do any additional processing or sorting of the list of responses from `getaddrinfo()`, nor should it in my opinion.

It could be interesting to consider adding a flag like fping's `-m` flag. That might be a pretty significant change given the current codebase, though, and might not be worth the effort if fping is already available.

**Comment by logistiker** [comment]
Ah yes, `fping -m` is exactly what I was looking for which pings both ip addresses of that host.  Thanks for the tip!  I understand the reluctance to implement it if fping already does it.  Then it's up to you guys as to whether you want to.  Feel free to close this issue if you don't.

**Comment by pevik** [comment]
> It could be interesting to consider adding a flag like fping's `-m` flag. That might be a pretty significant change given the current codebase, though, and might not be worth the effort if fping is already available.

`fping` has significantly different output based on passed switches (flags):

```
$ fping ::1
::1 is alive

$  fping  -c1 ::1
::1 : [0], 64 bytes, 0.031 ms (0.031 avg, 0% loss)

::1 : xmt/rcv/%loss = 1/1/0%, min/avg/max = 0.031/0.031/0.031
```
But `ping` has very similar output regardless passed switches. Thus I'm not against adding it, but output would need to be thought carefully. But I have other priorities with my limited time than this.
