### ISSUE TITLE
Translation to brazilian portuguese

### ISSUE THREAD

**Issue by julianofischer** [iputils/iputils#38]
I would like to contribute translanting the man pages to brazilian portuguese.
Please, could you gently tell me how could I do it?

Thank you.

**Comment by okias** [comment]
Hello, currently building man pages is kinda tricky and ugly. Right now we prefer to convert whole man pages to something modern.

After we dead with this, we'll appreciate translation. I'll keep this bug open for now and we'll contact you, when it will be ready :)

**Comment by okias** [comment]
Good news, since be0657da8842e90db446b10fbb9335d9033c54f2 we have docs in XML and we're able process them with xsltproc, which opens possibilities to translations.

If you considering to do some translations, feel free to go ahead! :)

**Comment by julianofischer** [comment]
Very nice, @okias.
Thanks.
