### ISSUE TITLE
arping receives potentially vlan encapsulated packets without any indication of such

### ISSUE THREAD

**Issue by jmaimon** [iputils/iputils#415]
This for example results in incorrect reporting of duplicate address detected in DAD mode, should the interface receive tagged traffic and at the same time arping was run with -D mode a host on another vlan happens to reply or announce its ARP and happens to have the targeted IP.

Apparently some more socket work is needed to ensure that a received packet was not originally 802.1q encapsulated.

**Comment by pevik** [comment]
@jmaimon Thanks for your bug report. Would you mind to provide way to reproduce the bug? Ideally via using network namespaces (e.g. https://github.com/iputils/iputils/issues/300, https://github.com/iputils/iputils/pull/391).

**Comment by jmaimon** [comment]
Its fairly straightforward. In fact I have already experimentally patched to produce mostly correct behavior.

I have a box with ens192 which has many vlan subinterfaces. ARP replies ARE received with -I ens192 that either come from the subinterface (with FROM->sll_ifindex different than ctl->device.ifindex) or from any other vlan present on the network. This is because ens192 port on the network switch is a "vlan trunk" port.

If they happen to have the same IP address as the target in -D mode, a duplicate address is detected, wrongly.

If you have a network with multiple vlans and can trunk your port, it should be trivial to reproduce. Produce arp replies in one vlan and arping -D on the trunk port.

**Comment by jmaimon** [comment]
This is an experimental patch. There may be some useful nuggets in there, but mostly it should serve to illustrate what I am trying to detect and correct. In particular, netlink_devinfo_query to obtain a vlan tag associated with an interface doesnt work properly at all.

**Comment by jmaimon** [comment]
fixed up a bit
[arping-vlan-tag.patch.txt](https://github.com/iputils/iputils/files/9129524/arping-vlan-tag.patch.txt)

**Comment by jmaimon** [comment]
Here is a set of patches, available and described here

http://www.jmaimon.com/misc/stuff/iputils/

**Comment by pevik** [comment]
I'm sorry I haven't had time for this yet.
