### ISSUE TITLE
clockdiff in docker container shows "clockdiff: nice: Permission denied"

### ISSUE THREAD

**Issue by xyziven** [iputils/iputils#422]
The base docker image is alpine, the iputils package was installed through the command "apt add iputils"

\# clockdiff -o destination
clockdiff: nice: Permission denied

**Comment by Vogtinator** [comment]
There appear to be two different issues:

```
clockdiff: nice: Permission denied
```

That's probably because the process in the container has a nice level of 0, so would require `CAP_SYS_NICE` to set it to -16.

```
clockdiff: socket: Operation not permitted"
```

That's because of `CAP_NET_RAW` missing. What I don't understand is that this happens only when running it in an interactive shell, but not with `podman exec`.

**Comment by xyziven** [comment]
It appears some system calls in docker  are blocked by default. 
https://docs.docker.com/engine/security/seccomp/

**Comment by pevik** [comment]
> It appears some system calls in docker are blocked by default. https://docs.docker.com/engine/security/seccomp/

Yes, but none of `socket` and `nice` are listed there. But obviously creating any `SOCK_RAW` socket is forbidden by default (also `arping` fails with permission).

Trying to run podman` with `--security-opt seccomp=unconfined` does not help:

```
# podman run -it --security-opt seccomp=unconfined alpine:latest /bin/sh 
/ # apk add iputils
....
/ # clockdiff -o 10.10.0.1
clockdiff: socket: Operation not permitted
```

```
$ podman --runtime=/usr/bin/crun run -it  --security-opt seccomp=unconfined opensuse/tumbleweed /bin/bash
zypper in -y iputils
...
clockdiff -o 10.10.0.1
clockdiff: socket: Operation not permitted
```
@xyziven can you try it with `docker`? But probably it will not work either, not sure what else needs to be changed to allow creating `SOCK_RAW` socket.

**Comment by xyziven** [comment]
> 

Replying with your previous question regarding how I ran the container.
The containers is brought up by docker-compose. 
Actually I started the server "metersphere" which is in this repo: https://github.com/metersphere/metersphere

version: "2.1"
services:
  ms-server:
    image: ${MS_IMAGE_PREFIX}/metersphere:${MS_IMAGE_TAG}
    container_name: ms-server
    environment:
        _<... environments_variaables>_
    ports:
      - ${MS_SERVER_PORT}:8081
      - ${MS_TCP_MOCK_PORT}:${MS_TCP_MOCK_PORT}
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8081"]
      interval: 6s
      timeout: 10s
      retries: 20
    restart: always
    volumes:
      - ms-conf:/opt/metersphere/conf
      - ms-logs:/opt/metersphere/logs
      - ms-data:/opt/metersphere/data
#    mem_limit: 1024m
    networks:
      - ms-network

**Comment by 6eh01der** [comment]
As [themoses](https://github.com/themoses) mentioned in #326 `build_aux/setcap-setuid.sh` contains only cap_net_raw+p. So maybe we just need to change it as `cap_net_raw,cap_sys_nice+ep` ? Something like [336cf88](https://github.com/6eh01der/iputils/commit/336cf881dc091853645c9b02d9bdd6bb897867d5)

**Comment by pdostal** [comment]
I've tried few commands with Podman:

1) Running the container normally as root
```
$ sudo podman run -it --rm opensuse/tumbleweed
aadb1461df07:/ # zypper -qn in iputils
The following 4 NEW packages are going to be installed:
  chkstat iputils permissions permissions-config
4 new packages to install.
Overall download size: 581.7 KiB. Already cached: 0 B. After the operation, additional 1.6 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
aadb1461df07:/ # clockdiff -o 10.10.0.1
clockdiff: nice: Operation not permitted
```

2) Running the container as root with extra capabilities
```
$ sudo podman run -it --rm --cap-add cap_net_raw,cap_sys_nice opensuse/tumbleweed
d768f432de36:/ # zypper -qn in iputils
The following 4 NEW packages are going to be installed:
  chkstat iputils permissions permissions-config
4 new packages to install.
Overall download size: 581.7 KiB. Already cached: 0 B. After the operation, additional 1.6 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
d768f432de36:/ # clockdiff -o 10.10.0.1
clockdiff: 10.10.0.1 is down
```

3) Running the container as normal user
```
$ podman run -it --rm --cap-add cap_net_raw,cap_sys_nice opensuse/tumbleweed
6c238d8ea745:/ # zypper -n in iputils
The following 4 NEW packages are going to be installed:
  chkstat iputils permissions permissions-config

4 new packages to install.
Overall download size: 581.7 KiB. Already cached: 0 B. After the operation, additional 1.6 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
6c238d8ea745:/ # clockdiff -o 10.10.0.1
clockdiff: nice: Operation not permitted
```

**Comment by pevik** [comment]
@pdostal Thanks for teaching me podman :).
@6eh01der Yep, both `cap_net_raw` and `cap_sys_nice`, going to merge your fix.

@xyziven Would you please share your real name and email, so that I can add your `Reported-by` tag?
(https://www.kernel.org/doc/html/latest/process/submitting-patches.html#using-reported-by-tested-by-reviewed-by-suggested-by-and-fixes)
No problem if you don't want to share, just please let me know.

**Comment by pevik** [comment]
@xyziven Commit prepared, waiting for your real name and email to add it to git commit.

**Comment by 6eh01der** [comment]
The first who mentioned this issue (not enough capabilities) was [themesos](https://github.com/themoses) [here](https://github.com/iputils/iputils/issues/326).

**Comment by pevik** [comment]
@xyziven In the end merged without your credentials. It should be fixed, if not, please let us know.
