### ISSUE TITLE
Document or correct "mdev" in summary output

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#43]
Forwarded from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=477569

Quoting the Debian bug report:

> After a successful sequence of ICMP echo responses, ping outputs values
> labelled;
> 
> min, mean, max, mdev
> 
> for the round trip times, "min", "mean" and "max" being self
> explanatory but documented.
> 
> I believe it would be desirable to clarify what "mdev" is because;
> 
> Wikipedia ping article suggests it is mean deviation, and that mdev is 
> a common or accepted abbreviation for mean deviation.
> 
> The release notes hint it may be "mean deviation" as they mention mean
> deviation when referring to IPv6 (I believe this to be an error in the
> release notes).
> 
> The code calculates: sqrt( mean of squares - square of mean).
> 
> Which is a quick method of calculating standard deviation from a running
> sequence of values.
> 
> I'm not aware of the abbreviation "mdev" being used for standard 
> deviation outside of this implementation of ping.

**Comment by pavlix** [comment]
So what change are you proposing here?

**Comment by viisauksena** [comment]
for consistency it should be clarifying documentation, so output stays untouched

**Comment by okias** [comment]
Does this docs (man) correction seems OK with you guys?
