### ISSUE TITLE
ping6 (and possibly others) does not support decimal representation of an IP address

### ISSUE THREAD

**Issue by zviratko** [iputils/iputils#439]
The following should ping Google.com, but it doesn't

$ ping6 55827987829242797944873063636453564430
ping6: 55827987829242797944873063636453564430: Name or service not known

this is a regression from the ipv4 version:

$ ping 2398823566
PING 2398823566 (142.251.36.142) 56(84) bytes of data.
64 bytes from 142.251.36.142: icmp_seq=1 ttl=116 time=9.17 ms

**Comment by pevik** [comment]
Thanks for your report. I'm just about to release new iputils version, thus this will have to wait till next version.
I wonder if this ever worked (likely not).

**Comment by pevik** [comment]
NOTE for myself: `55827987829242797944873063636453564430` => `2a00:1450:4014:80a:0:0:0:200e`

**Comment by gault** [comment]
> The following should ping Google.com, but it doesn't
> 
> $ ping6 55827987829242797944873063636453564430 ping6: 55827987829242797944873063636453564430: Name or service not known

Is there a documentation somewhere that specifies how to write IPv6 addresses in decimal?
Which other tools implement that?

> this is a regression from the ipv4 version:
> 
> $ ping 2398823566 PING 2398823566 (142.251.36.142) 56(84) bytes of data. 64 bytes from 142.251.36.142: icmp_seq=1 ttl=116 time=9.17 ms

That doesn't sound like a regression. IPv4 addresses have their own format (see inet_aton(3)) which obviously differ from the IPv6 ones (see RFC 5952).

Let's imagine that this feature was implemented. Then, on systems where ping can handle both IPv4 and IPv6, how should it interpret decimal integers smaller than 2^32? As IPv4 or IPv6 addresses?

And finally, the plain decimal form isn't the only format that has no equivalent with IPv6. IPv4 accepts decimal (default), octal (prefixed by 0) and hexadecimal (prefixed by 0x) notations. You can even use a different base in each part of the numbers-and-dots notation (and also use 0, 1, 2 or 3 dots). For example, 012.0.0.1, 01200000001, 10.0.0.1, 10.1, 0xa.0.0.1 and 0xa.0.1 all represent the same IPv4 address.

The IPv4 plain decimal notation used in your example is just a particular case of that complex notation scheme, which can't fit with the existing IPv6 notations for many reasons (hex number have a prefix in IPv4 but not in IPv6, the IPv4 '.' separator has different semantic than the ':' IPv6 one, etc.).

Honestly, let's not try to partially mimic the IPv4 notations in IPv6. This doesn't seem to have any benefit but is guaranteed to bring ambiguities, unexpected behaviours for users and interoperability problems in the future.

**Comment by pevik** [comment]
Well, I agree that IPv6 is not suitable for implementing this due valid reasons @gault mentioned (hex number have a prefix in IPv4 but not in IPv6, the IPv4 '.' separator has different semantic than the ':' IPv6 one, etc.).
