### ISSUE TITLE
'git shortlog' |Document the command for queries made outside a repository

### ISSUE THREAD

**Issue by Ricky-Tigg** [iputils/iputils#442]
Hello. A relevant initiative currently informs along with each [release](https://github.com/iputils/iputils/releases), various informations via `git shortlog` in respect to credit. Nevertheless the syntax involved appears to solely apply to queries made while being within a repository. Though a more practical scenario is a query from outside a repository. Then according commands would better match real world case. Here is in this regard an approximation command model: `git shortlog <options> -- <GitHub_path_to_repository>`.

**Comment by pevik** [comment]
To be honest, I didn't get what exactly you want and why? Why to change `git shortlog` which is just info for changelog? Feel free to be more specific.

**Comment by Ricky-Tigg** [comment]
Closing to be honest.
