### ISSUE TITLE
Ping6 link-local address with -I interface is throwing warning source address might be selected on device other than

### ISSUE THREAD

**Issue by Kottapalli-Naveen** [iputils/iputils#460]
Can someone tell why would ping6 look for a different source address when -I is mentioned?

Output:

root@1-1:~# ping6 fe80::929:cbb4:d6ad:4498 -I vEth1
ping6: Warning: source address might be selected on device other than: vEth1
PING fe80::929:cbb4:d6ad:4498(fe80::929:cbb4:d6ad:4498) from :: vEth1: 56 data bytes
From fe80::250:56ff:fe8d:d8c0%vEth1 icmp_seq=1 Destination unreachable: Address unreachable
From fe80::250:56ff:fe8d:d8c0%vEth1 icmp_seq=2 Destination unreachable: Address unreachable
From fe80::250:56ff:fe8d:d8c0%vEth1 icmp_seq=3 Destination unreachable: Address unreachable

Using below version of ping:

root@1-1:~# ping6 -V       
ping from iputils s20190709

**Comment by Kottapalli-Naveen** [comment]
@pevik Thanks for the reply.  Can you tell in what circumstances does kernel {{need to}} pick a different address other than the interface mentioned?

In the above example, the interface mentioned has a link-local address and GUI assigned

root@1-1:~# ifconfig vEth1
vEth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.42.3.92  netmask 255.255.255.0  broadcast 10.42.3.255
        inet6 fe80::250:56ff:fe8d:d8c0  prefixlen 64  scopeid 0x20<link>
        inet6 2003::92  prefixlen 64  scopeid 0x0<global>
        ether 00:50:56:8d:d8:c0  txqueuelen 1000  (Ethernet)
        RX packets 978515  bytes 299267034 (299.2 MB)
        RX errors 0  dropped 168  overruns 0  frame 0
        TX packets 24886  bytes 2366944 (2.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by pevik** [comment]
Well, if you use `ip` to print IPv6 addresses, many of them are `scope link` (see [RFC 4007](https://www.rfc-editor.org/rfc/rfc4007):

```
$ ip -6 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
...
228: vnet15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UNKNOWN qlen 1000
    inet6 fe80::882:64ff:fe1f:16c9/64 scope link 
       valid_lft forever preferred_lft forever
229: cni-podman0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 state DOWN qlen 1000
    inet6 fe80::702b:87ff:feb9:7c3c/64 scope link 
       valid_lft forever preferred_lft forever
```

Normally you should ping them with `%` notation:
```
$ ping -c1 fe80::fc54:ff:fe87:c84f%vnet14 
PING fe80::fc54:ff:fe87:c84f%vnet14(fe80::fc54:ff:fe87:c84f%vnet14) 56 data bytes
64 bytes from fe80::fc54:ff:fe87:c84f%vnet14: icmp_seq=1 ttl=64 time=0.042 ms

--- fe80::fc54:ff:fe87:c84f%vnet14 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.042/0.042/0.042/0.000 ms
```

But for some reason, `ping` also allows to ping them via interface `-I vnet14` (we added warnings in https://github.com/iputils/iputils/issues/398 https://github.com/iputils/iputils/pull/405):
```
$ ping -c1 fe80::fc54:ff:fe87:c84f -I vnet14 
ping: Warning: IPv6 link-local address on ICMP datagram socket may require ifname or scope-id => use: address%<ifname|scope-id>
ping: Warning: source address might be selected on device other than: vnet14
PING fe80::fc54:ff:fe87:c84f(fe80::fc54:ff:fe87:c84f) from :: vnet14: 56 data bytes
64 bytes from fe80::fc54:ff:fe87:c84f%vnet14: icmp_seq=1 ttl=64 time=0.042 ms

--- fe80::fc54:ff:fe87:c84f ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.042/0.042/0.042/0.000 ms
```

Using different interface causes problems:
```
$ ping -c1 fe80::fc54:ff:fe87:c84f%vnet15
PING fe80::fc54:ff:fe87:c84f%vnet15(fe80::fc54:ff:fe87:c84f%vnet15) 56 data bytes
From fe80::882:64ff:fe1f:16c9%vnet15 icmp_seq=1 Destination unreachable: Address unreachable

--- fe80::fc54:ff:fe87:c84f%vnet15 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

$ ping -c1 fe80::fc54:ff:fe87:c84f -I vnet15
ping: Warning: IPv6 link-local address on ICMP datagram socket may require ifname or scope-id => use: address%<ifname|scope-id>
ping: Warning: source address might be selected on device other than: vnet15
PING fe80::fc54:ff:fe87:c84f(fe80::fc54:ff:fe87:c84f) from :: vnet15: 56 data bytes
From fe80::882:64ff:fe1f:16c9%vnet15 icmp_seq=1 Destination unreachable: Address unreachable

--- fe80::fc54:ff:fe87:c84f ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms
```

IMHO for some reason is unknown on which interface is the source address, that's why is the warning printed. But I'd like myself to know more details.

**Comment by pevik** [comment]
@nmeyerhans any input, please?

**Comment by nmeyerhans** [comment]
Unless it's specified explicitly, the source address is chosen by the kernel based on interface address assignment and routing tables. Binding to a specific interface without specifying a source address means you're still letting the kernel pick the source address, and if the preferred route to the destination happens to use a different interface than the one you specified, the kernel will choose a source address from that interface, not from yours.

I think we've discussed in the past the possibility of making the warning a bit clearer by identifying which interface provided the kernel's chosen address and only showing the warning if there's a mismatch.  I'm not sure it's worth it, though.

**Comment by Kottapalli-Naveen** [comment]
@nmeyerhans Can you tell what piece of code the kernel pick another interface even if -I <interface> is given?  And how is it different from providing interface name with `%`?

**Comment by pevik** [comment]
You should search in these files:
* ICMP datagram socket (`SOCK_DGRAM`): [`net/ipv4/icmp.c` (IPv4)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/icmp.c?h=v6.3), [`net/ipv6/icmp.c` (IPv6)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/icmp.c?h=v6.3)
* raw socket (`SOCK_RAW`): [`net/ipv4/raw.c` (IPv4)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/raw.c?h=v6.3), [`net/ipv6/raw.c` (IPv6)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv6/raw.c?h=v6.3)

`ping -c1 -v 127.0.0.1` will show you what socket you use.

**Comment by Kottapalli-Naveen** [comment]
@pevik I see below output.  What from the below output signify the interface or source address selection?

root@benu-bng-up-1-1:~# netstat -anop | grep ping
raw   213504      0 0.0.0.0:1               0.0.0.0:*               7           32571/ping        off (0.00/0/0)
raw6    5376      0 :::58                   :::*                    7           32571/ping        off (0.00/0/0)

**Comment by pevik** [comment]
FYI `ifconfig` and `netstat` are legacy tools which I haven't used for years, they are replaced by `ip` and `ss`.
IMHO you will not see interface from `netstat` nor `ss`.

**Comment by Kottapalli-Naveen** [comment]
As per ping specification, whenever the destination is an IPv6 link-local address, the link specification is required which can be specified using -I device or %device in our code.  When device name is mentioned using -I, below code of ping is causing the issue.

206         if (rts->device) {
207             struct ifaddrs *ifa0, *ifa;
208 
209             if (getifaddrs(&ifa0))
210                 error(2, errno, "getifaddrs");
211 
212             for (ifa = ifa0; ifa; ifa = ifa->ifa_next) {
213                 if (!ifa->ifa_name || !ifa->ifa_addr ||
214                     ifa->ifa_addr->sa_family != AF_INET6) <<<<<<<<
215                     continue;
216                 if (!strcmp(ifa->ifa_name, rts->device) &&
217                     IN6_ARE_ADDR_EQUAL(&((struct sockaddr_in6 *)ifa->ifa_addr)->sin6_addr,
218                                &rts->source6.sin6_addr))
219                     break;
220             }
221             if (!ifa)
222                 error(0, 0, _("Warning: source address might be selected on device other than: %s"), rts->device);
223 
224             freeifaddrs(ifa0);
225         }

When the system call getifaddrs returned all the interfaces available with addresses, it appears that all the devices that are configured in the box are of family type AF_PACKET rather than AF_INET6 though the interfaces have both v4 and v6 address configured.

Not sure why that check is added for AF_INT6.  Instead a check if a link-local address is present shouldn't that be picked?

@pevik @nmeyerhans Is the above question correct?

**Comment by pevik** [comment]
Actually, it's the behavior of [`getifaddrs()`](https://man7.org/linux/man-pages/man3/getifaddrs.3.html), but [`getaddrinfo()`](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html), which is called much earlier):

https://github.com/iputils/iputils/blob/b3ba3ddcb4af52fb10d42d02cceb6fde9854e626/ping/ping.c#L635-L652

Both functions are actually libc implementations (e.g. [glibc](https://www.gnu.org/software/libc/), [musl](https://musl.libc.org/), [uClibc-ng](https://uclibc-ng.org/), [bionic](https://android.googlesource.com/platform/bionic/), that's why BTW are in section 3 in man pages), therefore they are *not* system calls (nothing to do with the Linux kernel or other kernel). 

And `getaddrinfo()` mentions the need to use *address%scope-id notation for specifying the IPv6 scope-ID*, where *scope-id* is device name. Therefore e.g. musl does not support searching without *scope-ID* (it simply fails to find anything). That's one reason we encourage to use it instead of passing it via `-I`.

Other problem is that it works out of box only on raw socket. On ICMP datagram socket it required some fixes to behave the same like raw socket in this context (e.g. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=35a79e64de29e8d57a5989aac57611c0cd29e13e, again see more in https://github.com/iputils/iputils/issues/398 and https://github.com/iputils/iputils/pull/405). These were missing in 4.9 LTS where it was unfixable easily (https://lore.kernel.org/netdev/YppqNtTmqjeR5cZV@pevik/), but that's now EOL.

=> We agreed with @gobenji, that trying to avoid the recommended way (*scope-ID*) is not a good idea and trying to be smart to replace `address -I NIC` with `address%NIC` is also not good (https://github.com/iputils/iputils/pull/399).

**Comment by Kottapalli-Naveen** [comment]
Mentioning scope id `%` works when there is no VLAN configured.  For example, in the below case the default gateway is reachable over VLAN 4001.


B       ::/0 [20/0]
        via fe80::f2d4:e2ff:fe57:8ba, network, eth0/16:4001 <<<<<<<<<

@pevik Can you tell how to mention VLAN to ping?

**Comment by pevik** [comment]
No idea, can you please try `-I`? If it does not work best would be to create reproducer - ie the steps how you created your virtual network.

I also have long term plan to create testsuite using network namespaces: https://github.com/iputils/iputils/issues/243.

**Comment by Kottapalli-Naveen** [comment]
Though there is no solution for pinging the link-local address over a VLAN and is not related to the main issue described in the issue, closing the issue for now.

@pevik @nmeyerhans If we have to discourage using {{-I device}} for link-local addresses, let me know if I can do that change and generate a PR.

**Comment by pevik** [comment]
IMHO  discourage using `-I device` for link-local addresses was done in https://github.com/iputils/iputils/pull/405. If you think it should be further improved, please discuss it there or create PR.

Without replicating your setup I'm not able to further help you with your VLAN issue. Feel free to open new issue where you document how to create your setup.
