### ISSUE TITLE
Create distribution tarballs

### ISSUE THREAD

**Issue by thesamesam** [iputils/iputils#479]
Would it be possible for iputils releases to be accompanied by distribution tarballs? Meson can generate these with `meson dist`.

The reason I'm asking is to have pre-generated documentation (man pages) in the tarball without needing additional dependencies to build them, but there's some other advantages like being able to sign them & not relying on github's auto-generated source tarballs which are unstable (they've changed a few times over the years).

I can do the wiring up for the man pages if you're up for it.

**Comment by pevik** [comment]
Thanks a lot! This makes sense, but I'd start from the new release.

I'll update docs and create release script (there is already a lot of copy pasting from the docs).

**Comment by thesamesam** [comment]
Thank you, this will be a big help!

**Comment by pevik** [comment]
@thesamesam can you please have a look on https://github.com/iputils/iputils/pull/492?

**Comment by pevik** [comment]
Fixed in 83f011ab2a1e8ebf6f6e9b00494ceb069ac42a63, 72a36873cc909abe51d3d57053fb786402ef734a.

**Comment by pevik** [comment]
@thesamesam I'm sorry, I overlooked the main reason for this, to get pregenerated man pages.

**Comment by pevik** [comment]
Finally found that simple `CC` pointing to cross compile toolchain was the problem, fixed and merged. Thanks!
