### ISSUE TITLE
some translation is a bit confusing

### ISSUE THREAD

**Issue by yvs2014** [iputils/iputils#481]
Sorry, haven't found the proper place where a translation question could be asked
Wouldn't it better not to use a machine translation?

Under the impression of this 'ECHO-IMPULSE 127.0.0.1'
```
$ ping 127.0.0.1
ЛУНА-ІМПУЛЬС 127.0.0.1 (127.0.0.1) 56(84) байтів даних.
```
https://github.com/iputils/iputils/blob/ee0a515e74b8d39fbe9b68f3309f0cb2586ccdd4/po/uk.po#L825-L826

**Comment by pevik** [comment]
@yurchor Can you please comment?

**Comment by yurchor** [comment]
Hi,

That was not a machine translation.

Thanks for your comment. Your opinion is very important.

**Comment by yurchor** [comment]
Just for reference (all the mechanisms that lead to this translation are explained):

https://uk.wikipedia.org/wiki/Ping

**Comment by yvs2014** [comment]
From the mentioned wiki page there's "Пінг (англ. PING)[1] — ..."
and nothing about "ECHO-IMPULSE/ЛУНА-ІМПУЛЬС" .  I can get some connection between PONG and ECHO and ЛУНА, but idk it's something like using GAZILLION-PIONEER instead of GOOGLE.  This kind of renaming of established words (especially short ones like ПІНГ/PING) is interesting, but certainly will confuse many people.  Look at this comment for example https://blog.tivasyk.info/blog/2020/10/15/ping.html . Good thing that iputils gettext-translation is already disabled for example in ubuntu (I got that IMPULSE only with manualy iputils-ping built).

Why just not to leave PING as PING/ПІНГ such as in other languages (not trying to replace it with PONG in long explanatory way)?

**Comment by yurchor** [comment]
> From the mentioned wiki page there's "Пінг (англ. PING)[1] — ..." and nothing about "ECHO-IMPULSE/ЛУНА-ІМПУЛЬС" . I can get some connection between PONG and ECHO and ЛУНА, but idk it's something like using GAZILLION-PIONEER instead of GOOGLE. This kind of renaming of established words (especially short ones like ПІНГ/PING) is interesting, but certainly will confuse many people. Look at this comment for example https://blog.tivasyk.info/blog/2020/10/15/ping.html . Good thing that iputils gettext-translation is already disabled for example in ubuntu (I got that IMPULSE only with manualy iputils-ping built).
> 
> Why just not to leave PING as PING/ПІНГ such as in other languages (not trying to replace it with PONG in long explanatory way)?

Because this is not a dictionary word. You cannot say that "ping" is what the "ping" does. The message is for the response, not for the request. That's my reasoning. The term was used in linux.org.ua long before I started translating (20 years ago). Something around 1998-2000.

Does it really-really hurt you? I bet "renaming of established words" is from Russian terminology, right?

**Comment by yvs2014** [comment]
> The term was used in linux.org.ua before ..

never seen that and not heard before working with unix tools, but that's not the point

> "renaming of established words" is from Russian terminology, right?

No idea where it came from, it's Q for those who follow that ECHO-IMPULSE renaming.
I can only say it certainly catch the eyes.

Don't want to argue on this PONG and just left my opinion (as a Ukrainian speaker) on that odd translation, plus the first one from the Internet.  It's not a problem to run "LANG=C ping" when it would need.

**Comment by yurchor** [comment]
> > The term was used in linux.org.ua before ..
> 
> never seen that and not heard before working with unix tools, but that's not the point
> 
> > "renaming of established words" is from Russian terminology, right?
> 
> No idea where it came from, it's Q for those who follow that ECHO-IMPULSE renaming. I can only say it certainly catch the eyes.
> 
> Don't want to argue on this PONG and just left my opinion (as a Ukrainian speaker) on that odd translation, plus the first one from the Internet. It's not a problem to run "LANG=C ping" when it would need.

So what is the point? Do you want to give some arguments for me to change the translation or just want to inform us that you will use "LANG=C ping"? Or just want to insult me for no reason?

Will you change the title of this report if I change it to "ПІНГ" or just close it?

**Comment by yvs2014** [comment]
> if I change it to "ПІНГ"

 at least this option looks reasonable and doesn't catch the eyes, of course from my point of view

**Comment by yurchor** [comment]
> > if I change it to "ПІНГ"
> 
> at least this option looks reasonable and doesn't catch the eyes, of course from my point of view

Ok. You will see in the next release. Please close the report.

Please be more specific the next time you will decide to rant or bike-shedding somewhere.

**Comment by yvs2014** [comment]
> Please close the report

thanks, done
