### ISSUE TITLE
switch iputils to Meson build system

### ISSUE THREAD

**Issue by martinbark** [iputils/iputils#51]
@okias,

Would you be interested in either a cmake or autotools build system if i sent a pull request?

The reason i ask is the the two pull requests i made (#42 and #50) are both about linking against the correct libraries. A better solution might be to have a configure stage to check which libraries are needed to link against.

What do you think?

BTW, thanks for maintaining iputils.

**Comment by okias** [comment]
Well, that would be great!

Generally I prefer CMake, but I'm open to any better solution than current state :)

**Comment by martinbark** [comment]
OK then I'm happy to work on adding a CMake build system for you.

**Comment by pavlix** [comment]
On the other hand I generally prefer autotools but that doesn't mean much.

**Comment by pavlix** [comment]
We talked about it with @okias and I'm going to switch iputils to autotools. In the mean time any patches in that direction are welcome.

**Comment by okias** [comment]
Well, as time passes, we got Meson build system, which seems like successor of autotools.

So new way leads to Meson :)

**Comment by okias** [comment]
I created _experimental_ https://github.com/iputils/iputils/tree/meson branch. You can test build, improvements welcome! :) It works very well, now we need cover all corner cases.

**Comment by kerolasa** [comment]
Meson build work is done & merged.
