### ISSUE TITLE
Capability issue with ping -m

### ISSUE THREAD

**Issue by JJ-Meng** [iputils/iputils#515]
Currently, `ping` is configured with `CAP_NET_RAW`, which generally suffices for most operations. However, we encountered a permission issue when using the `-m` option to mark outgoing packets.

I’ve tested it on the newest release(20231222).

```shell
$ /usr/sbin/getcap ping
ping = cap_net_raw+p

$ ./ping www.debian.org -m1
./ping: WARNING: failed to set mark: 1: Operation not permitted
PING www.debian.org (130.89.148.77) 56(84) bytes of data.
./ping: WARNING: failed to set mark: 1: Operation not permitted
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=1 ttl=48 time=288 ms
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=2 ttl=48 time=288 ms
``` 

Accroding to the capability [man-page](https://www.man7.org/linux/man-pages/man7/capabilities.7.html),  setting `SO_MARK` needs `CAP_NET_ADMIN`. So I would like to ask which is better, using root to execute the `ping` or adding `CAP_NET_ADMIN` to the `ping`?

**Comment by pevik** [comment]
> Accroding to the capability [man-page](https://www.man7.org/linux/man-pages/man7/capabilities.7.html), setting `SO_MARK` needs `CAP_NET_ADMIN`. So I would like to ask which is better, using root to execute the `ping` or adding `CAP_NET_ADMIN` to the `ping`?

Safer is to add `CAP_NET_ADMIN` (only a specific privilege, than using root, which is full privilege).

**Comment by JJ-Meng** [comment]
Thanks for the explanation. I also found it kind of weird to use root for a capability-aware program like `ping`. So would you consider adding `CAP_NET_ADMIN` to it? It'd make things more consistent and user-friendly.

**Comment by pevik** [comment]
It looks to be a regression when the feature was added in ce7be0e0f91d70b5af8fb6fc3c108c7cd880d7eb (released in s20100214).

**Comment by pevik** [comment]
Hm, but we already do set `CAP_NET_ADMIN` via `enable_capability_admin()`:
https://github.com/iputils/iputils/blob/c04828ab8cc671d2a383f544f49a4d721bdec8fc/ping/ping_common.c#L458-L471

I tested on current kernels (Debian kernel 6.6 and openSUSE Tumbleweed kernel 6.7) and obviously only root can set mark `1`. I need to study more about possible values in both raw and ICMP datagram socket.

**Comment by JJ-Meng** [comment]
I think it has to do with the authorization formula for capability. 

In short, when the caller is not root(uid≠0), the process's capability depends on the capability configuration on the executable. The complete formula can be found on the [man-page](https://www.man7.org/linux/man-pages/man7/capabilities.7.html).

Now, ping only has net_raw in permitted set.
```shell
$ /usr/sbin/getcap ping
ping = cap_net_raw+p
``` 

Permitted set is a limiting superset for the effective set. And effective set is the set of capabilities that are actually held by the process and used by the kernel for privilege checking.

When `enable_capability_admin`(or `modify_capability`) tries to set `CAP_NET_ADMIN` in effective set, it first uses `cap_get_flag` to check whether `CAP_NET_ADMIN` is in the process’s permitted set, and it fails because it's not there.

https://github.com/iputils/iputils/blob/056bf444419c56686c6390a8366de80921c96df5/ping/ping_common.c#L142-L161

In order for `enable_capability_admin` to work,  first we need to give `CAP_NET_ADMIN` to the ping file. I tested it on Debian and it works.

```shell
sudo /usr/sbin/setcap cap_net_admin,cap_net_raw+p  ping

./ping www.debian.org -m1
PING www.debian.org (130.89.148.77) 56(84) bytes of data.
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=1 ttl=48 time=287 ms
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=2 ttl=48 time=287 ms
64 bytes from klecker-misc.debian.org (130.89.148.77): icmp_seq=3 ttl=48 time=287 ms
``` 

It doesn't seem to add risk to the system. Since when `setsockopt` is done, `disable_capability_admin` revokes `CAP_NET_ADMIN` from the effective set, so this capability is only enabled when it is used.

https://github.com/iputils/iputils/blob/056bf444419c56686c6390a8366de80921c96df5/ping/ping_common.c#L458-L468

**Comment by pevik** [comment]
@JJ-Meng Can you please have look on https://github.com/iputils/iputils/pull/517? Also, could you please send me or post here your real name and email? I would like to add you credit `Reported-by:` which requires real name and real email (https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin).

**Comment by JJ-Meng** [comment]
> @JJ-Meng Can you please have look on #517? Also, could you please send me or post here your real name and email? I would like to add you credit `Reported-by:` which requires real name and real email (https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin).

I think this PR would fix my issue. Also, my name is Jingzi Meng <mengjingzi18@foxmail.com>. Thx :)

**Comment by pevik** [comment]
@nmeyerhans FYI

**Comment by pevik** [comment]
@JJ-Meng Out of curiosity, which kernel do you run (`uname -a`)? I suppose it must be < 5.17, right?

And which socket do you use? (`sysctl net.ipv4.ping_group_range` and `ping -c1 ::1 -v`)

**Comment by pevik** [comment]
> I ran my test on a qemu vm. The kernel is `6.6.9-60589-ga44dffaa70e5` from the linux stable brach.

I'm a bit surprised that 6.6.9+ kernel would be having this issue with `cap_net_raw+p` (it shouldn't have).
Anyway fixes merged.
