### ISSUE TITLE
ping: potential wrong exit code ?

### ISSUE THREAD

**Issue by ggs67** [iputils/iputils#528]
While looking through the ping code to implement the exit condition feature I cam e across one occurrence which returns wrong exit IMHO.

in node_info.c ,  niquery_option_subject_name_handler() calls errexit: (via goto) on errors. This code exits with exit(1)  which should be 2 IMHO, in accordance with the ping man page which states that 0/1 are reserved for ICMP related status while all other errors should return 2, to allow scripts to detect host "presence". With the exit code documented here, scripts could inadvertently assume hosts to be down while another  error is the cause (like memory allocation)

There is also an error(1,...) in the same code as well as in ping.c for usage error if no address is given, which IMHO should both return 2, while the latter is debatable, I agree.

**Comment by pevik** [comment]
BTW only ping uses this approach we should probably adapt it for other tools (exit code 1 is only for "some replies did not arrive", exit code 2 for anything else).

**Comment by pevik** [comment]
@ggs67 Very good point, thanks for reporting. Please have look here. I also dared to add your RBT (`Reported-by:` tag with your email).
