### ISSUE TITLE
Unable to build man pages

### ISSUE THREAD

**Issue by ggs67** [iputils/iputils#529]
In an attempt to update the man pages with the suggested -x option  I am simply unable to get them build.

I have trryed several methods, the most promising being this one:

- make clean
- meson configure builddir -DBUILD_MANS=true -DBUILD_HTML_MANS=true
- make

during make I get the following relevant messages:

```APPLICATIONS (build)
man: false   <--------------
HTML man: false    <-------------------
arping: true (capability or suid: false)
clockdiff: true (capability or suid: false)
ping: true (capability or suid: false)
tracepath: true
```

and at the end:

```
  User defined options
    BUILD_HTML_MANS: true
    BUILD_MANS     : true
```

The doc direrctory ios never mentioned during the build

**Comment by yvs2014** [comment]
a way of dealing with xsltproc introduced in https://github.com/iputils/iputils/commit/cb799d9

test running commands:
https://github.com/iputils/iputils/blob/master/doc/meson.build#L42-L43

p.s. It needs `xsltproc` and correspondent stylesheets to get those pages built. For example, in debian distros it requires two extra packages to be installed: `apt install xsltproc docbook-xsl-ns`

**Comment by pevik** [comment]
Yes, you currently need `xsltproc docbook-xsl-ns` for building man pages. You can have look for the package names for other distros in https://github.com/iputils/iputils/tree/master/ci.

FYI I hopefully find soon time to finish this effort for including pre-generated man pages in release tallbars: https://github.com/iputils/iputils/pull/520.

**Comment by ggs67** [comment]
Thanks for your help!

I did figure out about "xsltproc" during my testing before posting, but missed the requirement for "docbook-xsl-ns". Once installed the docs did build.
