### ISSUE TITLE
Unsolicited arping exit delayed 1s since "arping: use signalfd() and timerfd() rather than signals"

### ISSUE THREAD

**Issue by cjebpub** [iputils/iputils#536]
Issue:
Commit 67e070d08dcbec990e1178360f82b3e2ca4f6d5f introduced 1s poll() delay for unsolicited arpings.

Found in 20210202

Steps to Reproduce:
```
strace -rTvyy -o /tmp/arping.strace arping -q -c 1 -A -I eth0 [ip addr of interface in -I option]
```

Results in strace output:
```
 unsolicited arp is sent
 followed by poll() returning timer event, delaying return by 1s
 read of timer event 
0.000035 sendto(3<socket:[98461]>, "\0\1\10\0\6\4\0\2RT\0\227\254\342\300\250z*RT\0\227\254\342\300\250z*", 28, 0, {sa_family=AF_PACKET, sll_protocol=htons(ETH_P_ARP), sll_ifindex=if_nametoindex("enp1s0"), sll_hatype=ARPHRD_ETHER, sll_pkttype=PACKET_HOST, sll_halen=6, sll_addr=[0xff, 0xff, 0xff, 0xff, 0xff, 0xff]}, 20) = 28 <0.000058>
0.002935 poll([{fd=4<anon_inode:[signalfd]>, events=POLLIN|POLLERR|POLLHUP}, {fd=5<anon_inode:[timerfd]>, events=POLLIN|POLLERR|POLLHUP}, {fd=6<anon_inode:[timerfd]>, events=POLLIN|POLLERR|POLLHUP}, {fd=3<socket:[98461]>, events=POLLIN|POLLERR|POLLHUP}], 4, -1) = 1 ([{fd=5, revents=POLLIN}]) <0.994472>
0.997690 read(5<anon_inode:[timerfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000106>
```

Prior to commit commit 67e070d08dcbec990e1178360f82b3e2ca4f6d5f,  following unsolicited arping there was no poll() and no read() and thus no 1s delay.

The code was:

```c
send_pack(s, src, dst,
		  (struct sockaddr_ll *)&me, (struct sockaddr_ll *)&he);
if ((sent == count) && unsolicited)
		/* We usually wait for an extra iteration
		 * after sending the last request to see if we
		 * get a reply, but we don't need to in
		 * unsolicited mode */
		finish();  ->> goes straight to exit for unsolicited case.

```

Now the poll loop in event_loop() seems irrelevant for unsolicited ping but causes arping to delay 1s before returning.

I believe the exit_loop condition should include `!unsolicited` condition:
e.g.
```diff
-        while (!exit_loop) {
+        while (!(exit_loop || unsolicited)) {
```

**Comment by pevik** [comment]
Correct, 67e070d08dcbec990e1178360f82b3e2ca4f6d5f contained `if ((ctl->sent == ctl->count) && ctl->unsolicited)` condition.

I created PR to fix this: https://github.com/iputils/iputils/pull/541, could you please reveal your real name and email address, so that I can put it into the `Reported-by:` and `Suggested-by:` tags (e.g. for your credit :)).

**Comment by cjebpub** [comment]
> could you please reveal your real name and email address, so that I can put it into the `Reported-by:` and `Suggested-by:` tags (e.g. for your credit :)).

Profile updated: Curtis Taylor c j e b p ub@gmail.com
