### ISSUE TITLE
Cannot run multiple arping simultaneously

### ISSUE THREAD

**Issue by shuangye** [iputils/iputils#538]
Our system used an old iputils. It can run multiple `arping` simultaneously:

```console
./arping -I ethlmp0 -c 2 -w 10 192.168.255.126 &
./arping -I ethlmp0 -c 2 -w 10 192.168.255.126 &
[1]-  Done                    ./arping -I ethlmp0 -c 2 -w 10 192.168.255.126
[2]+  Done                    ./arping -I ethlmp0 -c 2 -w 10 192.168.255.126
Version: s20160308
```

We updated it to a new version recently. I found that the behavior changed. Only the last arping succeeded:

```console
arping -I ethlmp0 -c 2 -w 10 192.168.255.126 &
arping -I ethlmp0 -c 2 -w 10 192.168.255.126 &
[1]-  Exit 1                  arping -I ethlmp0 -c 2 -w 10 192.168.255.126
[2]+  Done                    arping -I ethlmp0 -c 2 -w 10 192.168.255.126
Version: 20211215
```

Then I compiled the latest release 20240117. Now both failed:

```console
/usr/local/bin/arping -V
arping from iputils 20240117
libcap: no, IDN: no, NLS: yes, error.h: yes, getrandom(): yes, __fpending(): yes

sudo /usr/local/bin/arping -I eth0 -c 2 -w 10 10.0.0.1 &
sudo /usr/local/bin/arping -I eth0 -c 2 -w 10 10.0.0.1 &
[1] 3008
[2] 3009
ARPING 10.0.0.1 from 10.0.0.201 eth0
ARPING 10.0.0.1 from 10.0.0.201 eth0
Unicast reply from 10.0.0.1 [10:0C:6B:D5:ED:9A]  2.436ms
Unicast reply from 10.0.0.1 [10:0C:6B:D5:ED:9A]  2.465ms
Unicast reply from 10.0.0.1 [10:0C:6B:D5:ED:9A]  2.765ms
Sent 1 probes (1 broadcast(s))
Received 2 response(s)
Unicast reply from 10.0.0.1 [10:0C:6B:D5:ED:9A]  2.800ms
Sent 1 probes (1 broadcast(s))
Received 2 response(s)

[1]-  Exit 1                  sudo /usr/local/bin/arping -I eth0 -c 2 -w 10 10.0.0.1
[2]+  Exit 1                  sudo /usr/local/bin/arping -I eth0 -c 2 -w 10 10.0.0.1
```

I wenght through the release notes. Seems this behavior is not mentioned. Is this a deliberate change? If it is, we have to redesign our system behavior too.

**Comment by shuangye** [comment]
Add Linux kernel info:

- The first 2 tests run in our self-made Linux:
     - `Linux HOSTNAME 5.15.148-6124c37634 #1 SMP PREEMPT Wed May 8 11:45:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- The last test runs in WSL2:
    - Ubuntu 22.04.3 LTS running in WSL2, Windows 10
    - `Linux HOSTNAME 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by pevik** [comment]
For me 67e070d08dcbec990e1178360f82b3e2ca4f6d5f (released s20190324) broke `-c1`, but higher works for me:


```
# ./builddir/arping -c1 -I wlp3s0 192.168.1.1 -w10 & ./builddir/arping -c1 -I wlp3s0 192.168.1.1 -w10 &
[1] 234367
[2] 234368
ARPING 192.168.1.1 from 192.168.1.133 wlp3s0
ARPING 192.168.1.1 from 192.168.1.133 wlp3s0
Unicast reply from 192.168.1.1 [50:EB:F6:87:9D:D0]  1.728ms
Unicast reply from 192.168.1.1 [50:EB:F6:87:9D:D0]  1.721ms
Sent 1 probes (1 broadcast(s))
Sent 1 probes (1 broadcast(s))
Received 1 response(s)
Received 1 response(s)
[ ENTER ]
[1]-  Exit 1                  ./builddir/arping -c1 -I wlp3s0 192.168.1.1 -w10
[2]+  Exit 1                  ./builddir/arping -c1 -I wlp3s0 192.168.1.1 -w10
```
=> broken both (e.g. even in 67e070d08dcbec990e1178360f82b3e2ca4f6d5f it did not work properly)

```
# ./builddir/arping -c2 -I wlp3s0 192.168.1.1 -w10 & ./builddir/arping -c2 -I wlp3s0 192.168.1.1 -w10 & 
[1] 234474
[2] 234475
ARPING 192.168.1.1 from 192.168.1.133 wlp3s0
ARPING 192.168.1.1 from 192.168.1.133 wlp3s0
Unicast reply from 192.168.1.1 [50:EB:F6:87:9D:D0]  1.743ms
Unicast reply from 192.168.1.1 [50:EB:F6:87:9D:D0]  1.733ms
Unicast reply from 192.168.1.1 [50:EB:F6:87:9D:D0]  2.014ms
Unicast reply from 192.168.1.1 [50:EB:F6:87:9D:D0]  2.039ms
Sent 1 probes (1 broadcast(s))
Received 2 response(s)
Sent 1 probes (1 broadcast(s))
Received 2 response(s)
[ ENTER ]
[1]-  Done                    ./builddir/arping -c2 -I wlp3s0 192.168.1.1 -w10
[2]+  Done                    ./builddir/arping -c2 -I wlp3s0 192.168.1.1 -w10
```
=> working both

It was certainly not a deliberate change, but I have no idea what could be wrong.

**Comment by pevik** [comment]
Well, the real change was in 84ca65ca980315c73f929fed8b6f16bbd698c3a0 (which is a short fix of 67e070d08dcbec990e1178360f82b3e2ca4f6d5f):

```diff
diff --git a/arping.c b/arping.c
index a1ec231..77c9c56 100644
--- a/arping.c
+++ b/arping.c
@@ -792,7 +792,7 @@ static int event_loop(struct run_state *ctl)
        close(tfd);
        freeifaddrs(ctl->ifa0);
        rc |= finish(ctl);
-       rc |= !(ctl->brd_sent != ctl->received);
+       rc |= (ctl->sent != ctl->received);
        return rc;
 }
 
```

IMHO the change is correct: in 027c47ee07339e5e1aadf67b5b79289f23ee18de (prior all the changes) I get:

```
# ./builddir/arping -c2 -I eth0 192.168.255.1 -w10 & ./builddir/arping -c2 -I eth0 192.168.255.1 -w10 & 
[1] 253249
[2] 253250
ARPING 192.168.255.1 from 192.168.255.133 eth0
ARPING 192.168.255.1 from 192.168.255.133 eth0
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.703ms
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.746ms
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.940ms
Sent 1 probes (1 broadcast(s))
Received 2 response(s)
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.973ms
Sent 1 probes (1 broadcast(s))
Received 2 response(s)
[ ENTER ]
[1]-  Done                    ./builddir/arping -c2 -I eth0 192.168.255.1 -w10
[2]+  Done                    ./builddir/arping -c2 -I eth0 192.168.255.1 -w10
```

=> sent 1 probe and get 2 responses - that i wrong.

But in 84ca65ca980315c73f929fed8b6f16bbd698c3a0 it does not allow to get more responses than what was sent:

```
# ./builddir/arping -c2 -I eth0 192.168.255.1 -w10 & ./builddir/arping -c2 -I eth0 192.168.255.1 -w10 & 
[1] 253703
[2] 253704
ARPING 192.168.255.1 from 192.168.255.133 eth0
ARPING 192.168.255.1 from 192.168.255.133 eth0
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.722ms
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.726ms
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.910ms
Unicast reply from 192.168.255.1 [50:EB:F6:87:9D:D0]  1.915ms
Sent 1 probes (1 broadcast(s))
Sent 1 probes (1 broadcast(s))
Received 2 response(s)
Received 2 response(s)
[ ENTER ]
[1]-  Exit 1                  ./builddir/arping -c2 -I eth0 192.168.255.1 -w10
[2]+  Exit 1                  ./builddir/arping -c2 -I eth0 192.168.255.1 -w10
```

I would prefer to keep this behavior. Why do you need to run simultaneously more arping on the same address?

ICMP protocol (for ping) uses Identifier and Sequence Numberto match the reply to the client (https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol#Timestamp).  I don't know the protocol enough, but I don't see anything like this in ARP protocol (https://en.wikipedia.org/wiki/Address_Resolution_Protocol). Also ARP spoofing (https://en.wikipedia.org/wiki/Address_Resolution_Protocol#ARP_spoofing_and_proxy_ARP) suggests there is nothing like unique identification (and authentification).

**Comment by pevik** [comment]
I asked: https://networkengineering.stackexchange.com/questions/85691/missing-icmp-identifier-equivalent-in-arp-protocol-and-desired-arping-behavior

**Comment by shuangye** [comment]
Thank you for your explanation. We run multiple arping to the same IP address just as a robust test. We will further discuss that thether we should allow this in real use scenario.

**Comment by pevik** [comment]
@shuangye FYI I'll probably revert to the old behavior. Hopefully I'll find time next time to fix it.
BTW could you send me your email address and your real name? I'd like to add your credit as a reporter to the fix.

**Comment by shuangye** [comment]
Hello Petr,




Thank you for keeping tracking of this issue. The discussion is still ongoing in our organization. Since it's between different teams in different places, communication did not go well.

If you would choose to revert to old behavior, we can at least have more time to review our SW.

My real name is Mingyang Liu, ***@***.***



Best regards







At 2024-05-30 03:26:05, "Petr Vorel" ***@***.***> wrote:

@shuangye FYI I'll probably revert to the old behavior. Hopefully I'll find time next time to fix it.
BTW could you send me your email address and your real name? I'd like to add your credit as a reporter to the fix.

**Comment by pevik** [comment]
@shuangye Any change you could write me directly to pvorel@suse.cz so I get your email address unfiltered?

**Comment by michalsieron** [comment]
Hi there @pevik, I checked the fix you provided, and it doesn't seem to revert to previous behavior.

@shuangye seems to have similar findings based on their comment under your commit.

With the change as it is, `rc` will indicate error when you receive more responses than sent requests.
If you were to reverse the comparison, it would return an error when you get fewer replies than requests, which would work more like the old behavior.

**Comment by pevik** [comment]
@shuangye @shuangye Could you please test it?

NOTE: all tools should change `-1` exit code for capability to `2` ("other error") and maybe create constants for exit codes for readability (e.g. `IPUTILS_RC_SUCCESS 0`, `IPUTILS_RC_ERR_NO_REPLY 1`, `IPUTILS_RC_ERR_OTHER 2`), but that's for later.

**Comment by shuangye** [comment]
With this commit https://github.com/iputils/iputils/pull/546/commits/dd8d23e377c9154ea8c0b83bd975762efba2ee5d
The test can pass. All arping instances succeeded.
