### ISSUE TITLE
Cannot ping IPv4 addresses when SOCK_DGRAM is not supported

### ISSUE THREAD

**Issue by sodz** [iputils/iputils#54]
Pinging IPv4 addresses fails when the kernel is too old to support SOCK_DGRAM ICMP socket (actually OpenVZ 2.6.32-042stab113.11).
```
# strace ./ping -v -4 127.0.0.1

socket(PF_INET, SOCK_DGRAM, IPPROTO_ICMP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
[snip]
write(2, "ping: socket: Address family not supported by protocol\n", 55) = 55
```
However, it is okay to ping IPv6 addresses:
```
# strace -s 99 ./ping -v -6 ::1

socket(PF_INET6, SOCK_DGRAM, IPPROTO_ICMPV6) = -1 EPROTONOSUPPORT (Protocol not supported)
[snip]
write(2, "ping: socket: Protocol not supported, attempting raw socket...\n", 63) = 63
socket(PF_INET6, SOCK_RAW, IPPROTO_ICMPV6) = 3
[snip]
sendto(3, ...) = 64
recvmsg(3, ...) = 64
```

Apparently it is deliberately instructed in the code not to retry for a raw socket when the errno is EAFNOSUPPORT, which is the return value for IPv4 sockets with SOCK_DGRAM.

I don't understand why or when that condition is necessary, but removing it makes ping work fine.

```diff
diff --git a/ping.c b/ping.c
index 4455091..fd3c20b 100644
--- a/ping.c
+++ b/ping.c
@@ -115,7 +115,7 @@ static void create_socket(socket_st *sock, int family, int socktype, int protoco
        sock->fd = socket(family, socktype, protocol);

        /* Attempt creating a raw socket when ping socket failed */
-       if (sock->fd == -1 && errno != EAFNOSUPPORT && socktype == SOCK_DGRAM) {
+       if (sock->fd == -1 && socktype == SOCK_DGRAM) {
                if (options & F_VERBOSE)
                        fprintf(stderr, "ping: socket: %s, attempting raw socket...\n", strerror(errno));
                create_socket(sock, family, SOCK_RAW, protocol, requisite);
```
```
# ./ping -v -4 8.8.8.8
ping: socket: Address family not supported by protocol, attempting raw socket...
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=0.587 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=58 time=0.682 ms
```

**Comment by okias** [comment]
@pavlix could you check it?

**Comment by xse** [comment]
same issue here, archlinux stuck with a 2.6.32-pvu kernel (proxmox)

**Comment by pavlix** [comment]
I folks. Thanks for the bug report. I submitted the patch that causes this. The patch fixes a problem with IPv4 only kernels (e.g. using ipv6.disable=1 kernel command line) where EPROTONOSUPPORT was returned for IPv6. Therefore when we have a fix ready, we also have to check it on a (recent) kernel with IPv6 disabled.

**Comment by pavlix** [comment]
Can anyone please explain the difference between EAFNOSUPPORT and EPROTONOSUPPORT? Those are apparently two distinct error codes.

    /usr/include/asm-generic/errno.h:#define	EAFNOSUPPORT	97	/* Address family not supported by protocol */
    /usr/include/asm-generic/errno.h:#define	EPROTONOSUPPORT	93	/* Protocol not supported */
