### ISSUE TITLE
[PATCH] broken "-I <ifname>" option

### ISSUE THREAD

**Issue by bd46** [iputils/iputils#55]
In Debian/testing, "ping -I..." from package 3:20150815-2 is not working.
Following patch fixes it:

--- iputils-master/ping.c.orig  2016-04-05 19:44:37.000000000 +0300
+++ iputils-master/ping.c       2016-04-15 18:00:08.000000000 +0300
@@ -570,7 +570,7 @@
                        strncpy(ifr.ifr_name, device, IFNAMSIZ-1);

                        enable_capability_raw();
-                       rc = setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
+                       rc = setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
                        disable_capability_raw();

                        if (rc == -1) {

**Comment by jsynacek** [comment]
What does "not working" mean? Do the packets go through another interface? Also, could you please reformat the patch using the correct markup?

**Comment by jsynacek** [comment]
Oh, I see now. Basically s/probe_fd/sock->fd/. And I can confirm it works as expected. Without the patch, the -I option is just not honored.

**Comment by jsynacek** [comment]
Btw, this should probably be fixed for IPv6 as well.

**Comment by pavlix** [comment]
Like this?

 diff --git a/ping.c b/ping.c
 index 4455091..b8140bc 100644
 --- a/ping.c
 +++ b/ping.c
 @@ -569,7 +569,7 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
  			strncpy(ifr.ifr_name, device, IFNAMSIZ-1);
  
  			enable_capability_raw();
 -			rc = setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
 +			rc = setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
  			disable_capability_raw();
  
  			if (rc == -1) {

**Comment by pavlix** [comment]
Like this?

 diff --git a/ping.c b/ping.c
 index 4455091..b8140bc 100644
 --- a/ping.c
 +++ b/ping.c
 @@ -569,7 +569,7 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
  			strncpy(ifr.ifr_name, device, IFNAMSIZ-1);
  
  			enable_capability_raw();
 -			rc = setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
 +			rc = setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
  			disable_capability_raw();
  
  			if (rc == -1) {

**Comment by bd46** [comment]
On Fri, Aug 19, 2016 at 01:06:24PM -0700, pavlix wrote:
> Like this?
> 
>  diff --git a/ping.c b/ping.c
>  index 4455091..b8140bc 100644
>  --- a/ping.c
>  +++ b/ping.c
>  @@ -569,7 +569,7 @@ int ping4_run(int argc, char **argv, struct addrinfo *ai, socket_st *sock)
>   			strncpy(ifr.ifr_name, device, IFNAMSIZ-1);
>   
>   			enable_capability_raw();
>  -			rc = setsockopt(probe_fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
>  +			rc = setsockopt(sock->fd, SOL_SOCKET, SO_BINDTODEVICE, device, strlen(device)+1);
>   			disable_capability_raw();
>   
>   			if (rc == -1) {
> 

 Yes.
-- 
 Eugene Berdnikov

**Comment by n3ph** [comment]
#56 fixes both - Interface and IP Address binding and works here as expected.
