### ISSUE TITLE
remove -g from default CFLAGS

### ISSUE THREAD

**Issue by okias** [iputils/iputils#6]
it's useful only for debuging, is it needed by default?

Some results for gcc 4.8.2
Default (CFLAGS="-g -O3"):
149K ping 
160K ping6

Without -g (CFLAGS="-O3"):
47K ping
51K ping6

Without -g and with -lto (CFLAGS="-O3 -lto"):
44K ping
49K ping6

**Comment by pavlix** [comment]
In my opinion, the default `CFLAGS` are useful only for debugging and therefore I would prefer `CFLAGS="-ggdb"` over `CLFAGS="-O3"`. Especially when iputils lack a configure script.
