### ISSUE TITLE
what is the purpose of traceroute6 and what shall we do with it?

### ISSUE THREAD

**Issue by pavlix** [iputils/iputils#61]
We're removing all IPv6 specific software that can be merged into originally IPv4 but now generic variants. But traceroute6 doesn't fit this scenario because there is no traceroute in the package. I would be happy if someone could explain that so that I can proceed with the necessary changes.

**Comment by okias** [comment]
At least by quick look into debian bug tracker, it seems this utility has still users [1].

Maybe at some moment when there will be replacement with full functionality or simple TODO, how to switch from traceroute6 to some alternative.

Closing for now. Feel free to reopen in case of some progress.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863824
