### ISSUE TITLE
 traceroute6: sendto: Invalid argument

### ISSUE THREAD

**Issue by nmeyerhans** [iputils/iputils#68]
Forwarded from Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843264

traceroute6 does not work at all:

tglase@tglase:~ $ sudo traceroute6 -n www.teckids.org
traceroute to  (2a02:a00:1022:9846::74) from 2a01:4f8:150:946c::42:3, 30 hops max, 24 byte packets
sendto: Invalid argument
 1 traceroute: wrote  24 chars, ret=-1
 *sendto: Invalid argument
traceroute: wrote  24 chars, ret=-1
^C
130|tglase@tglase:~ $ ping6 www.teckids.org
PING www.teckids.org(terra.teckids.org (2a02:a00:1022:9846::74)) 56 data bytes
64 bytes from terra.teckids.org (2a02:a00:1022:9846::74): icmp_seq=1 ttl=54 time=24.6 ms
^C
--- www.teckids.org ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 24.670/24.670/24.670/0.000 ms

The other implementation on the system, however, does:

tglase@tglase:~ $ traceroute6.db -6 -n www.teckids.org
traceroute to www.teckids.org (2a02:a00:1022:9846::74), 30 hops max, 80 byte packets
 1  2a01:4f8:150:946c::42:1  12.458 ms  12.460 ms  12.460 ms
 2  * * *
 3  2a01:4f8::a:15:b  12.445 ms  12.614 ms  12.621 ms
 4  2a01:4f8:0:3::1c5  12.624 ms 2a01:4f8:0:3::1c1  12.628 ms 2a01:4f8:0:3::1c5  12.815 ms
 5  2a01:4f8:0:3::a  16.829 ms 2a01:4f8:0:3::da  17.050 ms  17.059 ms
 6  2001:7f8::62cb:0:1  17.286 ms  16.609 ms  16.616 ms
 7  2a00:13c8:1:d::2  22.053 ms  22.064 ms  21.994 ms
 8  2a01:170:0:2:3:1:0:c18  23.436 ms  23.446 ms  23.652 ms
 9  2a01:170:0:2:3::2  21.965 ms  21.933 ms  21.749 ms
10  2a02:a00:1022:9846::74  24.218 ms  24.003 ms  24.150 ms

**Comment by nmeyerhans** [comment]
The bug was introduced in 37953bfbe4bd1b4c2be26d837dcfa2934d5a4e16. We initialize the "port" field our destination sockaddr_in6 structure at traceroute6.c:447:
	to->sin6_port = htons(port);
But later, on line 464, we overwrite that entire structure with a result from `getaddrinfo()`:
	memcpy(to, result->ai_addr, sizeof *to);

result->ai_addr contains '0' in the port field, when we finally call sendto, we do so with UDP port 0 as the destination, as seen in strace:

    sendto(4, "\0\0 I\0\0\0\1z\353#X\0\0\0\0\342\17\f\0\0\0\0\0", 24, 0, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "2607:f8b0:400a:800::2004", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)

This is fixed setting the port value after the memcpy() call.

**Comment by vvidic** [comment]
And now the port is 0 when you send to and IPv6 address directly, so better move port setup after the whole if block.

```
# traceroute6.iputils ::1
traceroute to ::1 (::1) from ::1, 30 hops max, 24 byte packets
sendto: Invalid argument
 1 traceroute: wrote ::1 24 chars, ret=-1
 *sendto: Invalid argument
traceroute: wrote ::1 24 chars, ret=-1
 *sendto: Invalid argument
traceroute: wrote ::1 24 chars, ret=-1
 *
sendto: Invalid argument
 2 traceroute: wrote ::1 24 chars, ret=-1
 *sendto: Invalid argument
traceroute: wrote ::1 24 chars, ret=-1
```

```
# strace traceroute6.iputils ::1
sendto(4, "\0\0\1\232\0\0\0\3\227\327.Y\0\0\0\0\202\237\7\0\0\0\0\0", 24, 0, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)
```

**Comment by vvidic** [comment]
Here is a fix that works:
```
--- a/traceroute6.c
+++ b/traceroute6.c
@@ -444,7 +444,6 @@
        (void) memset((char *)&whereto, 0, sizeof(whereto));
 
        to->sin6_family = AF_INET6;
-       to->sin6_port = htons(port);
 
        if (inet_pton(AF_INET6, *argv, &to->sin6_addr) > 0) {
                hostname = *argv;
@@ -465,6 +464,7 @@
                hostname = result->ai_canonname;
                freeaddrinfo(result);
        }
+       to->sin6_port = htons(port);
        firsthop = *to;
        if (*++argv) {
                datalen = atoi(*argv);
```

**Comment by vvidic** [comment]
Seems this is fixed already, we just need to pull it into the Debian package.
