### ISSUE TITLE
ping -Q184 fails with "Invalid tclass"

### ISSUE THREAD

**Issue by posch** [iputils/iputils#70]
Worked fine with ping from iputils-s20121221, does not work with ping from iputils-s20160308.

**Comment by okias** [comment]
Quick fix for you should be converting decimal number to HEX and it should work fine.

DEC numbers worked only for ping ipv4, so probably in merge process was decimal support accidentally lost.

This will be fixed in next release.

Thank you for bug report :)

**Comment by okias** [comment]
@posch, feel free to retest branch https://github.com/iputils/iputils/commits/tos_fix

@pavlix can you recheck? Also I planning drop hextoui function now used only for "-F"
