### ISSUE TITLE
Make iputils localizable

### ISSUE THREAD

**Issue by hanklank** [iputils/iputils#72]
From what I understood, iputils isn't localizable today. Suggestion is to do like coreutils, use gettext and then hand over the translation work to https://translationproject.org/html/welcome.html

**Comment by pavlix** [comment]
@hanklank  Are you going to participate on that change in any way?

**Comment by hanklank** [comment]
@pavlix  Sorry, I don't have the skills for that.

**Comment by pavlix** [comment]
@hanklank Fair enough.

@okias Is there any motivation to make this happen in the community?

**Comment by okias** [comment]
@pavlix I don't think so, even locales makes issues, because ping is used in many scripts.

@hanklank At this moment, I don't see any gains. Ping is small simple utility and English language is widely used in IT field..

If someone propose some way, to enable it at build-time and send pull request, I'll probably accept it.

**Comment by hanklank** [comment]
@okias Thanks for the reply, We have some free time for doing open source stuff at work. I will certainly look into it when time allows, but don't know when, (and I'm super rusty at C),  so if someone else is reading this and thinking about it, just go ahead.

**Comment by okias** [comment]
@hanklank I'd recommend you to check https://github.com/mikeecb/ring project (which maybe at some point will be used in iputils), and try make it part of it

**Comment by tomop-tg** [comment]
Hi.

Please see #124 .

**Comment by kerolasa** [comment]
Thanks to @tomop-tg localization support is done.

aeec6a0a5247a2526306479f57f987bf6c09f3d8
1c9f77ac19f1ec645d81e4feab2fb7f5e2bba86d
