### ISSUE TITLE
Add support for IPPROTO_ICMP

### ISSUE THREAD

**Issue by robsmith11** [iputils/iputils#73]
I'm running a system with restricted user capabilities, so I am unable to use ping:
```
$ ping google.com
ping: socket: Operation not permitted
```
Would it be possible to add support for the new socket type that does not require special user capabilities as described in the link below?
https://lwn.net/Articles/420799/

**Comment by pavlix** [comment]
1) I wouldn't call socket protocols `IPPROTO_ICMP` and `IPPROTO_ICMPV6` new as they've been around for quite some time.

2) We do support them and when refactoring the respective part of the code I also verified it works as long as you configure your kernel to allow it. See the comments in the source code (via the following link) regarding kernel configuration.

https://github.com/iputils/iputils/blob/master/ping.c#L126

**Comment by pavlix** [comment]
Feel free to reach me on IRC Freenode (e.g. in #vpsfree or #gentoo) for more details.

**Comment by robsmith11** [comment]
Thanks for the link pavlix.  For anyone else trying to get it to work, it seems that most distros disable the ping socket by default, but it's easy to enable for all users as shown below:
```
# echo "1 2147483647" > /proc/sys/net/ipv4/ping_group_range
```
