### ISSUE TITLE
ping 100% cpu

### ISSUE THREAD

**Issue by kolorafa** [iputils/iputils#85]
It's the third time that i did left `ping -O 8.8.8.8` running for few days and i get 100% cpu usage from it.

![](https://download.dlk.pl/screenshots/2017-05-10-11-38-18-vv1B9GWNuv02suvI.png)

i did run strace on ping, and 5s of strace is 20MB of log
https://www.dropbox.com/s/93bl3lkhowopco0/ping_strace.log?dl=1

Arch Linux
ping utility, iputils-s20161105

Is there something i can do to help debug this?

**Comment by jsynacek** [comment]
I smell overflows. It would be nice to get a backtrace when this happens. If that happens again, please attach gdb to the process (gdb -p <ping pid>) and run "bt full".

**Comment by soheilhy** [comment]
What's your kernel version? If it's 4.10+ it smells like: https://github.com/iputils/iputils/issues/74

**Comment by kolorafa** [comment]
Now i'm on 4.10.13. But i could be on 4.10.x when that happend.
After updates it didn't happen again so probably fixed.

**Comment by soheilhy** [comment]
No, I had a partial fix it in 4.10.13 which fix this issue in *some* cases but not always.
