### ISSUE TITLE
Bug in ipv6 ping -I

### ISSUE THREAD

**Issue by Bog999** [iputils/iputils#88]
In ping6_run() there is an if statement which is supposed to set the IPV6_PKTINFO and SO_BINDTODEVICE options, but only the first setsockopt will be executed because there is && instead of || (ping6_common.c line 798)

**Comment by okias** [comment]
@Bog999 can you provide some test-case?

Thank you

**Comment by Bog999** [comment]
connect eth1 and eth2 to two networks (or to the same network). There should be a host with the address 2001::2/64 to perform the test on.

ip -6 addr add 2001::1/64 dev eth1
ip -6 addr add 2001::222/64 dev eth2

"ping 2001::2" - Works as expected
One of these tests will fail because ping ignores the -I flag - The packets will go out of the wrong interface.
ping 2001::2 -I eth1 - Expected: Ping goes out of eth1
ping 2001::2 -I eth2 - Expected: Ping goes out of eth2

**Comment by pevik** [comment]
Confirmed

**Comment by pevik** [comment]
@okias @pavlix I fixed this issue in pull request, but the question it is actually better than the previous behavior, when IP is accessible, but not from the iface we specified.

**Comment by Bog999** [comment]
I believe that this is the functionality for IPv4
