### ISSUE TITLE
Move from libidn to libidn2 (or add possibility to select between them)

### ISSUE THREAD

**Issue by msva** [iputils/iputils#91]
Hi there!

It would be nice if you consider to move from libidn to libidn2:
https://www.gnu.org/software/libidn/#libidn2

**Comment by okias** [comment]
it will be possible to use libidn2 in future, but it will be build time choice.

Would be also good, if you pointed to some advantages over using libidn

**Comment by okias** [comment]
Ongoing work here: https://github.com/iputils/iputils/pull/97

**Comment by nmav** [comment]
Note that there is no reason to keep compatibility with libidn. libidn implements an old standard (IDNA2003), while libidn2 implements the current standard (IDNA2008) in internationalized names.

**Comment by pevik** [comment]
@okias It seems it's done now.
