### ISSUE TITLE
Ping packetloss% upgrade

### ISSUE THREAD

**Issue by Envy3689** [iputils/iputils#94]
Hello, Really new to github sorry for putting this here if it doesn't belong there. 

Using a ping command I realised the % for packetloss upgrade was not really accurate. Actually if you make like 30 000 pings and received 29 950 of them, since u did not hit the 1%, the output missleads you and tell you that you have 0% packet loss. 

I'd love to see a slight improvement for this with a symbol (>/=) for results between 0 and 1% for example : 

> 30000 packets transmitted, 29950 received, >0% packet loss, time 0ms
> and
> 30000 packets transmitted, 30000 received, =0% packet loss, time 0ms

English is not my native language either so please do not bash me :D 

Thank you for your time.

**Comment by okias** [comment]
Well, maybe we could use number with floating point, but not sure about compatibility with scripts.

Maybe we could do this "smart" enough, to show float only when it's in range 0-1 and 99-100.

What do you think @pavlix ?
This shouldn't broke any existing scripts and in case when they rely on 0 or 100 value and it's not 0 or 100 they probably has been showing invalid value anyway..

**Comment by okias** [comment]
```
# ping -f 10.0.0.5
....
4929 packets transmitted, 4928 received, 0% packet loss
```
Verified - it's bug.

**Comment by okias** [comment]
```
# ping -f 10.0.0.5
....
1558 packets transmitted, 1557 received, 0.0641849% packet loss, time 2699ms
```
We have shiny fix, @Envy3689 feel free to test https://github.com/iputils/iputils/tree/accuracy_fix branch

**Comment by Envy3689** [comment]
Looks awesome thank you :)
