### ISSUE TITLE
make iputils Rusty!

### ISSUE THREAD

**Issue by okias** [iputils/iputils#96]
Since iputils codebase is pretty old, using many formating styles and there is really small amount people, which are able to understand code, I'd like open discussion about slowly replacing codebase with Rust based code.

Goals:
- simplify code
- make it more understanble to newcomers
- Rust itself make it much more robust, more secure
- maybe even some performance gains, but that's only small bonus for us

So, there is ongoing process to rewrite iputils ping [1], feel free to watch this repository and in point, when it will have functionality parity with our ping and testing done, I vote for replacing old-one C89/GNU89 code with Rusty one :)

At this moment is repository [1] in ongoing WIP development, so in case you'll want contribute, pull request are welcome.

[1] https://github.com/mikeecb/ring

**Comment by jsynacek** [comment]
My humble opinion below. Note that I mainly write about ping, as it is arguably the most used program of the iputils suite.

> Goals:
>
>    simplify code

Yes, this is a great reason and I like it. That's the only good reason to rewrite iputils, especially ping.

>    make it more understanble to newcomers

Why? Newcomers to what? It doesn't make any sense. 

>    Rust itself make it much more robust, more secure

It doesn't actually matter if it's Rust or C. The ping code was quite robust IMO before it turned into spaghetti mess. And I don't think that there is anything insecure about ping code. Insecure things would probably pop up from lower layers, like capabilities. Also, ping needs very specific APIs (mainly various setsockopts to make ping really work) that, last time I checked, only C libraries provided. That's not a problem, of course.

>    maybe even some performance gains, but that's only small bonus for us

I really doubt it. Plus, what do you really want to improve about ping's performance? In 99% of cases, it does something every second. And I think that ping flooding is already fast enough to cause DoS if firewall is not set up correctly.

**Comment by kerolasa** [comment]
I think switching from one language to another is different project. Assuming iputils-rust is better I'm sure distributions will switch using it rather than C implementation.

Meanwhile this project seems to be having trouble getting pull requests merged (or rejected), and issues closed. @okias do you want / need maintainer help? For example https://github.com/iputils/iputils/pull/75  should be merged to fix https://github.com/iputils/iputils/issues/74 and there are few other that just need a little maintainer time & project rights.

**Comment by okias** [comment]
@kerolasa some maintainer help would be appreciated. I'm working full time, so I don't have much spare time.

Feel free to write me, if you're interested.

David

**Comment by pevik** [comment]
Rust is fancy and modern, but it lack support for many archs:
https://lwn.net/Articles/771355/
So please, if anyone plans to work on Rust implementation, create separate project for it.

**Comment by pevik** [comment]
@okias can we close this ticket?
